### ISSUE TITLE
[Feature] Reload widget periodically

### ISSUE THREAD

**Issue by Hawkedon** [jurialmunkey/skin.arctic.horizon.2#100]
Hi @jurialmunkey, don't know if it's possible to reload a widget periodically (with a setting to control how often to do this) from the skin or TMDB helper addon. Currently I'm using ReloadSkin() to do that manually, but this reload is for whole skin, it's better if there is a way to reload specific widgets automatically.

**Comment by jurialmunkey** [comment]
Not really possible from skin side.

Kodi handles when containers refresh. That happens when wither you finish watching something or the path of the widget changes.

You can leverage the path changing to force specific widgets to reload. Generally you would do this by adding a fake additional param on the end of the path tied to a window property

Eg
`plugin://plugin.video.themoviedb.helper?info=popular&tmdb_type=movie&reload=$INFO[window(home).property(reload_popular)]`

Because the reload param doesn't mean anything to that plugin it just ignores it. However now if you change that property value, kodi will think it is a new path and reload.

So you can force that widget to reload byy doing `setproperty(reload_popular,$INFO[System.time],home)`

Problem is that different plugins use different param systems, so there's no standardised way for the skin to manage this for you. Also skins don't really have any scripting functions, so any method would be incredibly hacky and overly complex. It would have to be an all or nothing approach and there's not much point to that because mapping a button or shortcut to reloadskin() already achieves the same thing - it's only worth it if you can control individual widgets independently.

**Comment by Hawkedon** [comment]
Thanks @jurialmunkey for the detailed explanation. It seems a support from Kodi itself for this is the best solution.

**Comment by jurialmunkey** [comment]
> Thanks @jurialmunkey for the detailed explanation. It seems a support from Kodi itself for this is the best solution.

Yeah I really wish there was some better controls for reload and loading priority for widget containers because at the moment it is frustratingly basic.

The inverse with reloading is also true: some widgets would be better off refreshing _less_ frequently than they do currently! For instance, widgets with randomised items are better suited to be reloaded on a timed interval (e.g every few hours) rather than on an event trigger like playback stop (so annoying when a randomised widget reloads after watching a trailer for instance!).

Same with loading priority. Sometimes some essential library based containers get stuck waiting for a plugin to load because the plugin got in first and took the last available thread handle. Really wish there was some way to say which containers have priority and which containers can wait until everything else is done first!
