### ISSUE TITLE
[BUG] Some films display wrong director in fullscreen widget and in list view infoline

### ISSUE THREAD

**Issue by kandykarter** [jurialmunkey/skin.arctic.horizon.2#1000]
### Skin section

Library Views

### Current Behavior

For *most* movies the skin behaves normally, but for the occasional movie it shows a Second Unit or other "lower" director, rather than the actual director of the film. In the attached image, you'll see the movie Ishtar (I know, I know) showing "Michael D. Moore" as the director, where the film's actual director is Elaine May. Elaine May shows as the director in the metadata, in fact I had to go to IMDB to find out what role Michael D Moore had in the production, as he's not mentioned in any nfo files or other metadata that I can find in my kodi install. 

This is happening on two instances of Kodi I'm running. Both up-to-date, one is running on Linux Mint, the other on an Android TV.

### Expected Behavior

This field in the fullscreen widget should show the Director of the film. 

### Steps To Reproduce

1. Navigate to Ishtar in widget or in list view, see that it shows the wrong director (this happens with other films occasionally also)

### Screenshots and Additional Info

![PXL_20231202_202518253](https://github.com/jurialmunkey/skin.arctic.horizon.2/assets/107814899/95c5120a-6512-4a3a-b49c-ef5ed2f559da)
![PXL_20231202_203619987 MP](https://github.com/jurialmunkey/skin.arctic.horizon.2/assets/107814899/9f3d9564-00f7-4a4f-978c-4d5b1be4beec)
![PXL_20231202_203639528](https://github.com/jurialmunkey/skin.arctic.horizon.2/assets/107814899/6b0d2c70-25b3-4852-aca6-c63da70894da)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by kandykarter** [comment]
![PXL_20231202_204846821](https://github.com/jurialmunkey/skin.arctic.horizon.2/assets/107814899/84139cb0-4e66-4d28-bb52-b9b2dfd36acd)
Here it is again with Debra Hill showing as the director of John Carpenter's Assault On Precinct 13, a film she was an Assistant Editor and Script Supervisor on.

**Comment by ChocOranger** [comment]
The information for director is coming from the TMDB helper plugin.

The skin should, but doesn't, use local information for some static credits like director rather than using information from TMDB. This sometimes leads to inconsistencies like you've found.
Rating, for example, should be updated as it's liable to change.

You can also see for Ishtar the genre isn't the first one listed in the local info (Adventure) but the first one listed in TMDB (Comedy). This is also the TMDB helper plugin.

If you are happy editing templates I can give you fixes to use local information.

**Comment by kandykarter** [comment]
Hey, that'd be fantastic. It drives me a little nuts when I see stuff I KNOW is wrong. Drives me a little nuts that TMDB is providing incorrect info, but I'll refrain from tilting at windmills.

**Comment by jurialmunkey** [comment]
> Drives me a little nuts that TMDB is providing incorrect info

It isn't providing "incorrect" info. There are multiple people with credits for "Directing" in these movies. Similarly, there are multiple Genres. The skin simply takes the first listed as it doesn't have room to display more than one field in this location (consider if you have a movie with multiple directors and multiple genres then the line will get long).

The reason as to why it uses TMDbHelper instead of the local information is because Kodi gives no method for skinners to separate genres/directors/writers/studios etc into individual values. So using local information is a case of all or nothing (and all is too long for the space here).

**Comment by kandykarter** [comment]
Granted it does sound like this is a feature jurialmonkey included under duress, so he's probably not incredibly concerned with its accuracy, I agree with your assessment that TMDB has made some very weird choices about how they categorize directors. .

Earlier you mentioned you might have a way I could set the infoline to use local info via a template edit, can you tell me a bit more about that? 

Thanks!

**Comment by ChocOranger** [comment]
>Hey, that'd be fantastic. It drives me a little nuts when I see stuff I KNOW is wrong. Drives me a little nuts that TMDB is providing incorrect info.

Firstly, take into consideration what jurialmunkey said about the line getting very large very quickly, especially with multiple directors.
Secondly, take into account the fact that the directors are very often wrong as I posted above. I don't show directors on that line for that reason. If I wanted directors on that line I'd use two lines for the information, I didn't think it was worth it.
Thirdly, All my data is in .nfo files associated with the movies and served via Jellyfin. You mileage may vary but I'd expect it to work...

If you want Genres listed from local, and as jurialmunkey said you can't split these in a skin so all genres are listed (3 if you scrape from OMDB which are the same as IMDB's)

Edit Includes_Info.xml and change 

```
<!-- Genres = TMDb Split (movie / tvshow) -->
<include content="Info_Line_Label" condition="!$PARAM[player] + Skin.HasSetting(Infoline.EnableGenre)">
    <param name="controltype" value="$PARAM[controltype]" />
    <param name="label" value="$INFO[$PARAM[container]ListItem.Property(Genre.1.Name)]" />
    <param name="visible" value="!String.IsEmpty($PARAM[container]ListItem.Property(Genre.1.Name)) + [String.IsEqual($PARAM[container]ListItem.DBType,tvshow) | String.IsEqual($PARAM[container]ListItem.DBType,movie)]" />
    <param name="textcolor" value="$PARAM[colordiffuse]_90" />
</include>
<include content="Info_Line_Label" condition="!$PARAM[player] + Skin.HasSetting(Infoline.EnableGenre)">
    <param name="controltype" value="$PARAM[controltype]" />
    <param name="label" value="$INFO[Container(99950).ListItem.Property(Genre.1.Name)]" />
    <param name="visible" value="String.IsEmpty($PARAM[container]ListItem.Property(Genre.1.Name)) + !String.IsEmpty(Container(99950).ListItem.Property(Genre.1.Name)) + [String.IsEqual($PARAM[container]ListItem.DBType,tvshow) | String.IsEqual($PARAM[container]ListItem.DBType,movie)]" />
    <param name="textcolor" value="$PARAM[colordiffuse]_90" />
</include>
```

to

```
<include content="Info_Line_Label" condition="!$PARAM[player] + Skin.HasSetting(Infoline.EnableGenre)">
    <param name="controltype" value="$PARAM[controltype]" />
    <param name="label" value="$INFO[$PARAM[container]ListItem.Genre]" />
    <param name="visible" value="!String.IsEmpty($PARAM[container]ListItem.Genre) + [String.IsEqual($PARAM[container]ListItem.DBType,tvshow) | String.IsEqual($PARAM[container]ListItem.DBType,movie)]" />
    <param name="textcolor" value="$PARAM[colordiffuse]_90" />
</include>
```

For me it looks like
![assault13](https://github.com/jurialmunkey/skin.arctic.horizon.2/assets/77179521/d76763f6-8d5a-4946-adcf-8500a73c0213)


For Directors and keep in mind this will list ALL genuine directors. The line may get big!

```
<!-- Genres = TMDb Split (movie / tvshow) -->
<include content="Info_Line_Label" condition="!$PARAM[player] + Skin.HasSetting(Infoline.EnableGenre)">
    <param name="controltype" value="$PARAM[controltype]" />
    <param name="label" value="$INFO[$PARAM[container]ListItem.Property(Genre.1.Name)]" />
    <param name="visible" value="!String.IsEmpty($PARAM[container]ListItem.Property(Genre.1.Name)) + [String.IsEqual($PARAM[container]ListItem.DBType,tvshow) | String.IsEqual($PARAM[container]ListItem.DBType,movie)]" />
    <param name="textcolor" value="$PARAM[colordiffuse]_90" />
</include>
<include content="Info_Line_Label" condition="!$PARAM[player] + Skin.HasSetting(Infoline.EnableGenre)">
    <param name="controltype" value="$PARAM[controltype]" />
    <param name="label" value="$INFO[Container(99950).ListItem.Property(Genre.1.Name)]" />
    <param name="visible" value="String.IsEmpty($PARAM[container]ListItem.Property(Genre.1.Name)) + !String.IsEmpty(Container(99950).ListItem.Property(Genre.1.Name)) + [String.IsEqual($PARAM[container]ListItem.DBType,tvshow) | String.IsEqual($PARAM[container]ListItem.DBType,movie)]" />
    <param name="textcolor" value="$PARAM[colordiffuse]_90" />
</include>
```

to

```
<include content="Info_Line_Label" condition="!$PARAM[player] + Skin.HasSetting(Infoline.EnableGenre)">
    <param name="controltype" value="$PARAM[controltype]" />
    <param name="label" value="$INFO[$PARAM[container]ListItem.Genre]" />
    <param name="visible" value="!String.IsEmpty($PARAM[container]ListItem.Genre) + [String.IsEqual($PARAM[container]ListItem.DBType,tvshow) | String.IsEqual($PARAM[container]ListItem.DBType,movie)]" />
    <param name="textcolor" value="$PARAM[colordiffuse]_90" />
</include>
```
For me this looks like
![assault13_with_dir](https://github.com/jurialmunkey/skin.arctic.horizon.2/assets/77179521/9fa9c1c3-e8cf-4711-b666-cbc2bbc94567)

My suggestion would be to disable directors in the options (Settings > Details> Customise Info Line).
The directors will be correctly displayed in the Movie's info screen.

Let me know if you need help.

**Comment by kandykarter** [comment]
That's really helpful, thanks a lot. I'm also doing the Jellyfin thing and my metadata only seems to have one person in the director fields, so hopefully this works for me. Thanks again!

**Comment by kandykarter** [comment]
I appreciate the additional insight into *why* the choices were made the way they were. There's a lot of grey areas here that I wouldn't have considered, and I understand why you would have the feature work the way it does. I still prefer how it works now that I've edited the template to use local information as a) I have very few movies with more than 2 directors, so it appears it only breaks a few (as opposed to QUITE a few when using tmdb data), and b) it's revealed a few cases where my local metadata is wrong. For example, Talk To Me (2022) had the two Casting Directors for the film show up on the Director line with the actual Directors of the film.

Anyway, I want to thank you both for the help and the information, it's helped iron out the single, minor, whiny little complaint I had about my far-and-ahead favourite Kodi skin.

Cheers!

**Comment by ChocOranger** [comment]
@jurialmunkey thanks for the information.

However, the vast majority of users won't think that a script supervisor is the director no matter how 'accurate' the information is.
Imagine if Spielberg wasn't the 'director' of ET or Jaws.

Since TMDbHelper is already capable of parsing the fields correctly why not use it to split directors correctly to work around Kodi's lack of string handling?

https://github.com/jurialmunkey/plugin.video.themoviedb.helper/blob/6f62df981a2cf8e9e96ae675bbeb6d101be62a01/resources/tmdbhelper/lib/api/tmdb/mapping.py#L56-L57

eg use Director_1, Director_2 etc
Then all skins get a proper breakdown. You could keep the current director field for backwards compatibility..

**Comment by jurialmunkey** [comment]
> However, the vast majority of users won't think that a script supervisor is the director no matter how 'accurate' the information is. Imagine if Spielberg wasn't the 'director' of ET or Jaws.

That's the point though, the list is the "directing department" not "directors". And yes bad naming on my part to call the property `Director.X` instead of `Directing.X` but that's unseen by the user so not worth breaking backwards compatibility over.

It's basic taxonomy: All ducks are birds, but not all birds are ducks. All directors work in the directing department, but not everyone working in the directing department is a director.

The "job" property tells you if they are *the* director.

> Since TMDbHelper is already capable of parsing the fields correctly why not use it to split directors correctly to work around Kodi's lack of string handling?

I have a strict rule that adding new properties must add previously unavailable information, else the number of custom properties balloons out of control.

TMDbHelper sets upwards of 1000 custom properties per item. The department split alone adds ~350 custom properties for each ListItem: 7 departments x 10 people (max set by me) x 5 properties (name, thumb, role, department, ID) = 350.

There's no reason for TMDbHelper to waste cycles adding even more properties that will for the most part will remain unused when there is already a property available for the skin to check if the person in the directing department is *the* director

```xml
<variable name="TheOneTrueDirector">
	<value condition="String.IsEqual(Container(99950).ListItem.Property(Director.1.Job),Director)">$INFO[Container(99950).ListItem.Property(Director.1.Name)]</value>
	<value condition="String.IsEqual(Container(99950).ListItem.Property(Director.2.Job),Director)">$INFO[Container(99950).ListItem.Property(Director.2.Name)]</value>
	<value condition="String.IsEqual(Container(99950).ListItem.Property(Director.3.Job),Director)">$INFO[Container(99950).ListItem.Property(Director.3.Name)]</value>
	[etc...]
</variable>

<label>$VAR[TheOneTrueDirector]</label>
```
