### ISSUE TITLE
Some little glitch's and missing text when using heebo font

### ISSUE THREAD

**Issue by SubEdict** [jurialmunkey/skin.arctic.horizon.2#121]
Hi J
Mesmerizing skin, can't stop playing with it. :)

Just some small layout issue with the heebo font (PC Windows, Kodi 19.4).
1. Button text overflow to right.
2. Pic 2-3: Missing the OK (Confirm) text below the Cancel button (Confirm Hebrew should read: **אישור**)

<a href="https://imgur.com/uH1E1wT"><img src="https://i.imgur.com/uH1E1wT.jpg" title="source: imgur.com" /></a>
<a href="https://imgur.com/i6gk64d"><img src="https://i.imgur.com/i6gk64d.png" title="source: imgur.com" /></a>
<a href="https://imgur.com/zHCJwP3"><img src="https://i.imgur.com/zHCJwP3.png" title="source: imgur.com" /></a>

That's all, everything else for now works amazing!

**Comment by jurialmunkey** [comment]
I can't fix the button text overflow issue. It is a kodi bug with autosizing buttons in rtl languages.

If that is the skinshortcuts dialog with the empty button, that's a problem with skinshortcuts not the skin (it happens in English too). It's because skinshortcuts doesnt properly support the new custom button control in that dialog.
