### ISSUE TITLE
[Bug] [Video OSD] Episode list is not sorted by episode number

### ISSUE THREAD

**Issue by Blurayx** [jurialmunkey/skin.arctic.horizon.2#136]
Preview Episodes are not in numerical order. All shows are unwatched.

https://user-images.githubusercontent.com/2873112/173167348-09773484-bed9-47a9-b718-5e3ae9bea8dd.mov

Thanks

**Comment by jurialmunkey** [comment]
@Blurayx - Check that you don't have shuffle enabled in playlist queue. If you have shuffle on and choose "play from here" or "play" on a whole season/tvshow then Kodi will queue the episodes in random order.

Example:

Episodes initially out of order after clicking "Play" from context menu on Brooklyn Nine Nine because I had enabled shuffle on a previous playlist queue:

![Honeyview_screenshot00055 (2)](https://user-images.githubusercontent.com/4618719/179383384-e9bf1c5a-d5b2-44f6-abef-0d1d5b8e738e.jpg)

Go back to library while episode is playing and go to the now playing queue:

![Honeyview_screenshot00056 (2)](https://user-images.githubusercontent.com/4618719/179383394-b2c476f0-8bfc-428a-ab49-8dd8d9848fe5.jpg)

Open side menu from now playing queue and see shuffle is enabled:

![Honeyview_screenshot00058 (2)](https://user-images.githubusercontent.com/4618719/179383411-297698c5-ab52-47f9-be8d-2547d9012cd6.jpg)

After disabling shuffle my episode queue is in numerical order

![Honeyview_screenshot00057 (2)](https://user-images.githubusercontent.com/4618719/179383427-44dd6747-a3c0-45df-9a14-2cdd5ba1e49c.jpg)

**Comment by Blurayx** [comment]
very odd It was already set to off. toggled on/off, Now showing in the correct order.

Thanks
