### ISSUE TITLE
[Bug] [Feature] [Music OSD] Full screen music features / issues

### ISSUE THREAD

**Issue by dm2912** [jurialmunkey/skin.arctic.horizon.2#14]
First up, great job so far, looks really good. I appreciate its alpha and so far the work looks to have been focused on video, pvr etc which is understandable.

Issues found with full screen music playing (I use kodi a lot for music)

Some of this im pretty sure is on the roadmap in
https://github.com/jurialmunkey/skin.arctic.horizon.2/issues/5

![screenshot00015](https://user-images.githubusercontent.com/25871666/172007150-0ceb588c-5de9-41c9-9563-122385bfb35d.png)

+ Artist Slideshow Options (show/remove text, filters etc)

+ Settings icon does nothing when you press it

+ Playlist icon brings empty screen that says number of songs but does not list them

+ No next/previous track buttons (appreciate with a vertical menu next to album art this may not be possible and a playlist is the best way to select tracks once that works)

+ Lyrics brings up huge dialog box 

+ Bringing up on screen controls sometimes causes song to restart or rewind 5-10 seconds

**Comment by jurialmunkey** [comment]
> No next/previous track buttons (appreciate with a vertical menu next to album art this may not be possible and a playlist is the best way to select tracks once that works)

Actually, this is rolled into the stop and play buttons:

- Left/Right on Play will FF/RW (press multiple times to increase speed)
- Left/Right on Stop will skip to Next/Prev track

And yeah, its because there's not enough vertical space, so keeping things to most frequent options as main buttons. Will fix the playlist issue soon (also planning a playlist quick nav pop-up similar to how tvshow episodes display on video-osd).

> Bringing up on screen controls sometimes causes song to restart or rewind 5-10 seconds

This is odd... Are you maybe accidentally pressing Left/Right when you open the controls (i.e. like what I mentioned above with play/stop buttons)? That's the only possible cause I can think of.

**Comment by jurialmunkey** [comment]
Okay 0.1.36 should make some significant improvements for playlist handling
https://github.com/jurialmunkey/skin.arctic.horizon.2/releases/tag/v0.1.36

I've still got a few things I want to add to the playlist window -- e.g. buttons to move/delete individual songs -- but important thing is that it is working properly now. I'll probably also turn this playlist view into a standard library songs view too.

![Honeyview_screenshot00117](https://user-images.githubusercontent.com/4618719/173301735-ba142829-733a-4e08-85b2-0355832ba291.jpg)
