### ISSUE TITLE
[Bug] Disabling item on power menu does not remove it. 

### ISSUE THREAD

**Issue by dm2912** [jurialmunkey/skin.arctic.horizon.2#15]
Disabling an item on the power menu does not seem to remove it. 

Disabled favourites:
![screenshot00017](https://user-images.githubusercontent.com/25871666/172009049-461a43d4-2007-47b1-a845-7db357430119.png)

Still there, and persisted after reboot as well
![screenshot00016](https://user-images.githubusercontent.com/25871666/172009059-a0bbed5f-18bd-4b17-8eac-b9b9ea733758.png)

**Comment by dm2912** [comment]
oh. it does nothing when you press it

so its physically disabled, but not visually disabled

**Comment by jurialmunkey** [comment]
> oh. it does nothing when you press it
> 
> so its physically disabled, but not visually disabled

Hahaha, oh that is completely useless, definitely not the intended behaviour! It should remove the item from being built, I just never thought to test disabling/enabling items specifically in the powermenu since it was working in other parts.

Pretty sure I can fix it so that the template will skip building the disabled items.

**Comment by ShibajiCh** [comment]
Thank you!
