### ISSUE TITLE
[BUG] Can't remove the first submenu item

### ISSUE THREAD

**Issue by Hawkedon** [jurialmunkey/skin.arctic.horizon.2#172]
Hi @jurialmunkey, the first submenu item for a main menu item seems to be the same as the main menu item, and it can't be changed/removed. I tried to uncheck the "Submenu widget" setting and added a new submenu widget, but the first item is still the same. Is there any way to remove this item?

**Comment by jurialmunkey** [comment]
It is only there out of necessity because the submenu widget requires at least one item to be visible at all times to ensure that the other submenu items update correctly and the widget doesn't hide.

The problem as follows:

- Items in widget containers update if either a dynamic content path changes or a static item visibility changes.
- Skinshortcuts builds all the submenus as one giant combined list of static items. Each static item in the list has a visibility condition based on a property of the focused mainmenu item so that it only displays for the correct menu.
- Because the mainmenu properties need to update first for the submenu item visibility to be true, there is brief moment when switching menus where *all* submenu items' visibility evaluate to false.
- Normally this wouldn't be a problem as a submenu is usually only opened on an action (e.g. onup) by which time the new mainmenu item is already active.
- However, in the case of a widget, the container is hidden if it has no items and has finished loading because we don't want gaps with empty widgets. 
- Since the submenu contains static content it is loaded as soon as the container is visible. As a result, the widget container momentarily has no items and thus hides. 
- Once a container is hidden, Kodi will only update the items on a forced refresh such as stopping playback or reloading the skin, so the submenu will never become visible again unless forced.
- To prevent the submenu widget from hiding and never returning, it is necessary to add a static item that is always visible (the main menu item).

**Comment by Hawkedon** [comment]
Thanks @jurialmunkey for the detailed explanation! There is no this issue for AH1. Isn't AH1 submenu implemented as a widget? How does submenu work there?

**Comment by jurialmunkey** [comment]
> Thanks @jurialmunkey for the detailed explanation! There is no this issue for AH1. Isn't AH1 submenu implemented as a widget? How does submenu work there?

In AH1 I override the submenu widget container visibility to force it to be always visible. That creates the inverse problem - a submenu with no visible items leaves a gap for the empty widget. That's particularly confusing because the widget still takes focus normally since it is "visible" but you can't see where the focus is because it has no items.

The gap approach is fine IF your submenu items don't have any conditional visibility. It becomes a big problem once you want to hide certain items under certain conditions -- for example, on a kids profile.

**Comment by jurialmunkey** [comment]
Had to revert this change. Thought I'd found a solution but the bug re-appeared. Looking for a better approach.

**Comment by jurialmunkey** [comment]
Okay I'm pretty certain that 0.2.14 will properly fix this issue now.
