### ISSUE TITLE
[Feature] Autocompletion for virtual keyboard not working

### ISSUE THREAD

**Issue by ShibajiCh** [jurialmunkey/skin.arctic.horizon.2#177]
Autocompletion for virtual keyboard addon used to work in Arctic Horizon skin and was very helpful while searching long names. It's no longer working in this skin. Could you please add it in this skin too, if possible?

**Comment by jurialmunkey** [comment]
As far as I understand, the autocompletion addon in the official repo is broken and causes crashes for several systems.

**Comment by ShibajiCh** [comment]
Hi @jurialmunkey,

Yes, that's true but there was a patched version available which I used and it was working fine with Arctic Horizon 1 skin.

**Comment by drinfernoo** [comment]
There are a few versions floating around which apparently work, but nobody has taken the effort to actually contribute those fixes back to @phil65 *or* the official Kodi repository...

**Comment by ShibajiCh** [comment]
> There are a few versions floating around which apparently work, but nobody has taken the effort to actually contribute those fixes back to @phil65 _or_ the official Kodi repository...

Yes, I myself got the patched version from some Reddit post. If it was done by me I would've surely shared it with everyone. Recently I shared a code for Dolby Vision playback fix through Kodi in Reddit.

**Comment by ShibajiCh** [comment]
Hi @jurialmunkey,

Here's the link to the working Autocompletion addon from Reddit:
https://www.reddit.com/r/Addons4Kodi/comments/m6flxd/autocompletion_kodi_19/?utm_medium=android_app&utm_source=share

**Comment by ShibajiCh** [comment]
Hi @jurialmunkey,

So does this issue have nothing to do with Arctic Horizon 2 skin, because the Autocompletion addon was working fine in Arctic Horizon 1 skin? Please advise.

If nothing can be done then just ignore this issue,  because it's not like that we can't live without the Autocompletion addon. The Arctic Horizon 2 skin is already great without it. Thank you! 🙂

**Comment by jurialmunkey** [comment]
I had bug reports in AH1 about autocompletion causing crashes. If I put autocompletion in AH2 then Kodi will prompt to install the addon everytime the user attempts to use the keyboard.

There are ways around that occurring but I'm not sure I want to go to the trouble of supporting an addon that is not currently being maintained by someone willing to update it on the official repo. If no one updates it, then eventually it will either be marked broken or not updated for Nexus, at which point I have to remove it from the skin because I can't have a broken dependency. 

I honestly don't know why whoever is making the fixes is not submitting pull requests to get it fixed and updated on the official repo - honestly it is rather suspicious to force people to install a 3rd party repo and download modified versions of official modules rather than submitting a patch to get the real thing working.

**Comment by jurialmunkey** [comment]
Oops didn't mean to close. Clumsy fingers!

**Comment by Hawkedon** [comment]
Hi @jurialmunkey, the crash is related with busy dialog handling in Kodi, I submitted a bug report weeks ago at https://github.com/xbmc/xbmc/issues/21453, but no one work on it yet. I made a work around PR at https://github.com/xbmc/repo-plugins/pull/4044. This fixed the crash on Xbox for me.

**Comment by enen92** [comment]
Note (https://github.com/xbmc/xbmc/pull/21563) will certainly fix the issue you're trying to solve here. You might be interested in giving it a spin

**Comment by ShibajiCh** [comment]
Thank you @jurialmunkey !
