### ISSUE TITLE
[Feature] [PVR OSD] Simplified OSD for Live TV as an option

### ISSUE THREAD

**Issue by krzysztofwinnik** [jurialmunkey/skin.arctic.horizon.2#181]
**Is your feature request related to a problem? Please describe.**
Currently Video OSD and PVR OSD are the same. However, for Live TV there is no need to have PAUSE, RW, FF and respective key-bindings. Pressing left or right on remote accidently causes undesired behaviour, as it only rewinds / forwards stream buffer followed by skipped frames. 
I understand those features could be useful for catch-up TV, which in my experience works fine only for finished EPG items (that could be played as regular videos and have all controls in their OSD - there's even an option for this in PVR IPTV Simple settings). However, live TV is live by definition and in most cases can't be rewined or fast-forwarded. 

**Describe the solution you'd like**
I'd love to see an option in skin settings to enable simplified OSD for Live TV.
Simplified OSD would not have PAUSE, RW and FF buttons. There would be also no key-bindings for LEFT or RIGHT keys during playback.
This way Live TV could be played in more intuitive way.
Catch-up streams would still be possible to be played as regular videos with regular OSD with all controls including PAUSE, RW, FF.
Simplified OSD (as an option to be enabled/disabled in skin's settings) could be beneficial for:
- users who use Kodi for PVR playback, but have no catch-up / timeshift
- eldery users who have difficulties with consuming non-linear TV (like my parents)
- those, who would like to have simple, yet essential PVR experience ;-)

**Describe alternatives you've considered / Additional context**
I am aware this feature / enhancement is very specific and in Kodi environment I can't find any benchmark in Estuary or other skins. 
On the other hand, most custom tv boxes provided by telco companies in my country have different OSDs for live tv and catch-up.

**Comment by berkhornet** [comment]
Interesting suggestion. Any implementation would have to consider the features of the PVR clients. For example IPTV Simple Client supports timeshift on live and catch-up streams.  I would think a simple on/off OSD option would be the easiest solution to develop.

**Comment by jurialmunkey** [comment]
This would definitely need to be an optional setting due to the points Berkhornet makes.

To the point - I was already considering more specific pvr controls and I think an option to toggle to a more "basic" set would be great.

There's four slots available on the left. I would think channel up/down take place of jump forward/back (and stop stays as is of course).

What would replace play/pause?

Also to the point of keybindings - that's not a skin matter. You'd need to edit your keymap for that. I can only control the directional functions on the osd buttons themselves (eg up/down on play currently does ff/rw and up/down on seek does incremental steps forward/back). I can't change the general behaviour when the osd controls aren't visible.

**Comment by sabre6** [comment]
I think this is a good idea. Maybe for the final binding, it could be revert to "last channel", if that is an option?

And when brining up the OSD to start, perhaps it can focus on Stop, as that would likely be the most used binding in the group.

**Comment by krzysztofwinnik** [comment]
Could be "last channel". I was thinking about "guide" ("g" key, not epg).

**Comment by krzysztofwinnik** [comment]
It took me a while to think about an ideal OSD for PVR... How about:
(1) STOP
(2) DOWN
(3) UP
(4) REC
	- visible if PVR tuner has recording feature or 
(4alt.) - DOWNLOAD
	- visible if enabled in skin settings && playback is catch-up archive
	- needs IPTV Archive Downloader by tbrek on GitHub
	- action needs to be confirmed by @tbrek
SPACE
(5) GUIDE / EPG
	- on press: EPG
	- on up: Guide
	- on down: EPG
(6) INFO
(7) AUDIO
(8) SUBS
(9) SETTINGS

@jurialmunkey what do you think about it?

**Comment by sabre6** [comment]
I like the list, as long as STOP is the first button / in focus when the OSD comes up.

**Comment by jurialmunkey** [comment]
@krzysztofwinnik - Yeah I figured it makes sense to group all the channel switching stuff together on the left. That's probably what you want to have immediately on hand. Plus I found having up/down buttons weren't all that useful considering that can be done directly from the remote without needing the OSD.

One thing from the above that I was still going to look into was the IPTV Archive Downloader button - just haven't had a chance to check out that addon yet.

Other thing I was wondering about was if the FF/RW on the Play/Pause button was still a problem? I think maybe that's not as a bad now since I introduced the pop-up control that you need to navigate to first - makes accidental bumps much less frequent.
