### ISSUE TITLE
[Feature] Separate OSD clear logo and widgets clear logo

### ISSUE THREAD

**Issue by rizreflects** [jurialmunkey/skin.arctic.horizon.2#217]
Would it be possible to make it so we can set the clear logo for the homescreen and the clear logo for the video OSD separately? I've currently got the clear logos disabled when browsing through the homescreen because most of them are too small. However, I'd like to still see them when pausing a video. Currently, the only way to see the clear logo in the video osd is to set it on the homescreen. Could you possibly add an option to set these separately, so I can have clear logos when watching a video but normal text when browsing my homescreen?

**Comment by jurialmunkey** [comment]
If you think they are too small on the home screen, why would you want to display them on the video osd? The video osd clearlogo is exactly the same sizing as elsewhere in the skin.

**Comment by rizreflects** [comment]
I agree, some clearlogos do still look small in the video OSD, but this isn't a problem (for me). The sizing issue is more apparent when scrolling through widgets, as some clear logos are very large and others very tiny. However, when you're viewing it from the OSD you're no longer scrolling.  In my opinion, the clearlogos look fine in the video OSD. If you could possibly bring back clear art like in previous skins of yours, that would be even better than clearlogos.

**Comment by Nuklear92** [comment]
> If you think they are too small on the home screen, why would you want to display them on the video osd? The video osd clearlogo is exactly the same sizing as elsewhere in the skin.

Hey, Jurial I was going to make a post about the ClearLogos inconsistent sizing. Is there for some reason any hack you could do potentially in the near future to basically make all the logos similar in size and length. For example I'm not going to mention names here, but there are a particular third party streaming apk outside of Kodi that also does use ClearLogos by default in it's UI navigation. The Dev from that app seems to have done some magic coding perhaps because all of the ClearLogos logos are consistently the same height size, the only difference is they vary is in length depending on how long the content's title is. I have no clue if there's a limitation on Kodi about this or not but maybe something like a universal static size where all of the ClearLogos that are bigger than normal are sized down and all of the ClearLogos that are too small are sized up a little to have a little more consistency. 

Again, I'm not sure if a hack like that in coding could be possible I believe there is because like a I said there's an app outside of Kodi that consistently show ClearLogos on a similar size. My only first guessing is Kodi skinning limitations 🤷‍♂️

**Comment by jurialmunkey** [comment]
> Is there for some reason any hack you could do potentially in the near future to basically make all the logos similar in size and length

I already do everything I can. TMDbH uses python image library to crop all the transparent space around the logo to make sure that it maximises vertical space as much as possible.

The artwork choosen by TMDbH is the highest rated artwork available on FanartTV. If you disagree with it being the best artwork, then you should go to FanartTV and vote for something better so that everyone will benefit. I can't magic better artwork out of thin air -- that would require machine learning AI...

For TMDbH items, you can easily change art to something more suitable using the `Manage Artwork` context menu option. 

IF an item is not from TMDBH but TMDBH is supplying art via the service monitor, then the [TMDbH context menu add-on](https://github.com/jurialmunkey/context.themoviedb.helper) can be used to access the manage artwork function via the `TMDbHelper Options` context menu outside of TMDbH.

For example, here's an item in TMDbHelper where the "top" rated logo on fanart.tv is not great, so I changed it to something more suitable. 

![Honeyview_screenshot00126](https://user-images.githubusercontent.com/4618719/174438511-4bfc94eb-da15-4db7-aa7a-6dd19109386e.jpg)

![Uploading Honeyview_screenshot00127.jpg…]()

![Honeyview_screenshot00128](https://user-images.githubusercontent.com/4618719/174438525-48e7bf67-4ea1-49ae-bfd7-7b2c86e9ed78.jpg)

![Honeyview_screenshot00129](https://user-images.githubusercontent.com/4618719/174438528-4d095d75-b08e-44d4-9eea-7ecbd4d9e141.jpg)


There's not much more I can do. All the tools are there for people to get better artwork. Open source relies on people contributing. That can be as simple as voting for more suitable artwork on fanart.tv

**Comment by drinfernoo** [comment]
I actually don't get clearlogo on the player OSD... is there a setting now that I'm missing?

**Comment by jurialmunkey** [comment]
> I actually don't get clearlogo on the player OSD... is there a setting now that I'm missing?

Do you have clearlogo enabled in Appearance Settings? Also needs fanart.tv to be enabled for service monitor in TMDbH settings.

**Comment by jurialmunkey** [comment]
No longer relevant as larger recent versions use larger clearlogos.
