### ISSUE TITLE
% left to watch is blank

### ISSUE THREAD

**Issue by derrgoo** [jurialmunkey/skin.arctic.horizon.2#22]
This just shows circle. Looks like % graphic is missing.

**Comment by jurialmunkey** [comment]
I can't reproduce this issue. It displays correctly for me:

![](https://i.imgur.com/iiLalGt.jpg)

**Comment by derrgoo** [comment]
This is from a trakt tv watchlist. See pic below. It shows the circle but nothing inside. 

![image](https://user-images.githubusercontent.com/63697905/172039623-3884a76a-df06-4e30-9293-671dbe938ac7.jpeg)

**Comment by jurialmunkey** [comment]
Oh that's tvshows. Tvshows don't have progress, they have unwatched counts.

Looks like whatever is providing that list is missing ListItem.Property(UnwatchedEpisodes) which is what displays in that circle.

**Comment by derrgoo** [comment]
I see so must be a bit different from your eminence skin. It shows %on tv widgets. 

![image](https://user-images.githubusercontent.com/63697905/172048603-93a47c67-dfc4-44c9-841c-79a615586937.jpeg)

**Comment by jurialmunkey** [comment]
Hmmm that;s really strange. Plugins shouldn't be able to set progress for tvshows because progress is tied to a resume point (which only movies/episodes/videos have, not tvshows). That looks like plugin doing something it isn't meant to in order to force that behaviour.

**Comment by derrgoo** [comment]
It helps to have them especially when using Trakt Scrobbling. It shows easy which one you left off on and how much to still watch. Eminence does for tv episodes and movies the same.

**Comment by xyzfre** [comment]
Just noticed I'm having the same issue on my end as well the progress circle is there but blank

**Comment by xyzfre** [comment]
![image](https://user-images.githubusercontent.com/49699869/172064623-2cc8856d-09af-4273-a0ed-b5700a4e2736.jpeg) TV Shows

**Comment by xyzfre** [comment]
![image](https://user-images.githubusercontent.com/49699869/172064638-c1f5ff6b-9a2e-4f39-8858-f84b8c300a04.jpeg) Movies

**Comment by xyzfre** [comment]
In Progress TvShows working Properly 👍🏼![image](https://user-images.githubusercontent.com/49699869/172071525-45001e41-b6d2-4cea-ba90-1893014d5acd.jpeg)

**Comment by xyzfre** [comment]
In Progress Episodes ,Blank Icon ![image](https://user-images.githubusercontent.com/49699869/172071653-03754b06-1551-46d3-a6ae-0582f419efbf.jpeg)

**Comment by derrgoo** [comment]
Yes in progress tv shows works fine but I am also talking about in progress episodes blank. But eminence working as it should.  😅

**Comment by jurialmunkey** [comment]
Oh they are  episodes! I thought they were _tvshows_ not episodes because of the posters. A tvshow can't have progress because it is folder but an episode can because it is playable.

OK that makes a lot more sense! There must be a visibility condition somewhere that's got a small error like a missing bracket. I'll see if I can figure out what is causing it.

**Comment by derrgoo** [comment]
Thank you 🙏

**Comment by jurialmunkey** [comment]
I bet the plugin is incorrectly setting the IsResumable flag when PercentPlayed is 0%

Please test 0.1.11 as I've added a workaround for plugins that mess this up.
https://github.com/jurialmunkey/skin.arctic.horizon.2/releases/tag/v0.1.11

If that solves the issue, please report to the plugin author that they are incorrectly setting IsResumable to True despite PercentPlayed being 0%.

**Comment by derrgoo** [comment]
After testing v0.1.11 I don't even have the blank showing. Nothing highlights but when I play it still is resuming where left off. 

![image](https://user-images.githubusercontent.com/63697905/172162647-f2d747c5-cfc8-4ce0-8c0e-ead935ae4787.jpeg)

**Comment by xyzfre** [comment]
> I bet the plugin is incorrectly setting the IsResumable flag when PercentPlayed is 0%
> 
> 
> 
> Please test 0.1.11 as I've added a workaround for plugins that mess this up.
> 
> https://github.com/jurialmunkey/skin.arctic.horizon.2/releases/tag/v0.1.11
> 
> 
> 
> If that solves the issue, please report to the plugin author that they are incorrectly setting IsResumable to True despite PercentPlayed being 0%.
> 
> 
> 
> 
> 
> 

Going to give it a test keep you posted as soon as I can thank you @jurialmunkey

**Comment by jurialmunkey** [comment]
> After testing v0.1.11 I don't even have the blank showing. Nothing highlights but when I play it still is resuming where left off.
> 
> ![image](https://user-images.githubusercontent.com/63697905/172162647-f2d747c5-cfc8-4ce0-8c0e-ead935ae4787.jpeg)

Okay, so it is actually resumable but the plugin doesn't have local resume data stored in Kodi because it doesn't use setResolvedURL correctly so it is forcing the resume point on playback instead of it being attached to the listitem. Skin can only get data from the listitem.

Plugins can manual set playprogress to listitems in Matrix using this type of RPC method:
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/blob/1e39e111e1e6d31951ea85e63c30c7b91403ccd3/resources/lib/api/kodi/rpc.py#L112-L115

**Comment by jurialmunkey** [comment]
> I am not sure how because I don't know any coding but I do know if I load your eminence skin Trakt Scrobbling will show all episodes progress with graphic in all my devices. Even if I wipe the build and do fresh same applies.

But is it only 1 quarter piece for those items? Because Eminence shows that even if progress is 0% and isresumable is set.

Eminence shows 1 piece for 0-33%, 2 pieces for 33%-66% and 3 pieces for 66%-99% (then full for watched). So even if the progress value is at 0% like these items, it will still show one quarter piece -- but that doesn't mean anything because it the plugin isn't setting a progress value to match the resume point.

**Comment by derrgoo** [comment]
Okay, I think I am understanding better. I guess that one piece is fine with me because it reminds me easily which one I have in progress. So therefore, I would use the one that is blank which tells me basically the same information. An episode is in progress.

**Comment by xyzfre** [comment]
I tested the latest version the progress icon doesn't show up anymore but the resume point is there when you click on the episode ,,not a big deal do you think it's possible at least for us to get back the blank Progress circle so  we know that the episode I started watching I know I did not finish ,, if not no big deal ,,skin is coming along AMAZING thank you @jurialmunkey

**Comment by 123Venom** [comment]
<img width="910" alt="isResumable" src="https://user-images.githubusercontent.com/46383815/172236374-5b3c3e13-60b7-47c0-ba7f-2e110140b5f9.PNG">

Something very strange appears to be going on.  In this case the `percentplayed` was set but the value set was NOT `0` like the `Container.ListItem.PercentPlayed` says it is, I don't think case sensitive matters last I knew?.  I even logged it to be sure...`item.getProperty(percentplayed)=27.2`. `ResumeTime` is set but I'm not seeing it from `Devhelper web` here.  The `IsResumable` is set here to `true` and I do not set that myself and my belief is if Kodi sees a `resumetime` it sets that bool itself?  I'm not sure why in all cases yet the `percentplayed` says `0` when log data says that's not true...I'm digging..lol

**Comment by 123Venom** [comment]
<img width="1008" alt="devhelper_web3" src="https://user-images.githubusercontent.com/46383815/172240134-f7837821-0a23-48d1-8723-25a2747f0d53.PNG">
In the previous picture the setting to trick the skin into thinking it's a show list was active so I disabled it.  Now you can tell since thumbs are shown it's set as a true episode list.  I wanted to rule that trick out as the culprit as to why `PercentPlasyed` is always being reported as `0`.  No change.  Now I wonder does Kodi change that to `0` is `TotalTime` is not also set?  Something is causing that odd behavior.

**Comment by 123Venom** [comment]
<img width="661" alt="resumable2" src="https://user-images.githubusercontent.com/46383815/172246904-98bc75f6-7f9c-4bca-ab11-6c6c8a4840cf.PNG">

I decided to see what would happen if I set `ResumeTime` and `TotalTime` ONLY.  Now it has values for `PercentPlayed`.  Seems to me Kodi is handling that, plus `isResumable`, when those two properties are set.  It seems if a plugin does not set `TotalTime` Kodi makes all `PercentPlayed` values `0` even if you try to set that property.

The drawback with setting `TotalTime` is that it adds the Kodi context menu item `Resume from xxx`
<img width="529" alt="cm_resume" src="https://user-images.githubusercontent.com/46383815/172247844-94b6de8a-4aae-4014-bde9-7c60cc7d698e.PNG">

**Comment by jurialmunkey** [comment]
@123Venom - kodi is designed to handle resume points itself. That is why plugins are meant to use  the setresolvedurl method so that resume is stored locally. 

To update the locally stored playback percent manually you must use the jsonrpc method I mentioned earlier to update Kodi's playback database for the file. It is not possible to set it directly to the listitem because Kodi will override from its database to be able manage resume natively. 

The progress and resume points are stored based upon the playable path url of the listitem. So an rpc is the only way to update it.

**Comment by 123Venom** [comment]
I do use set `setResolvedUrl` to initiate playback.

I've never seen a plugin use the Kodi db for resume points, not that we shouldn't if the data exchange can be properly handled and seek assigned.  Some plugins use a Trakt scrobble and write the data to/from the plugins own managed database, as do I, and sync to Trakt, while some just do their own local resume point handling via again the plugins own db.  They then set the seek to resume point, that's pulled from plugins db, somewhere about the plugins player module for `onAVStarted()`, I stopped using `onPlaybackStarted()` per latest Kodi doc's suggesting to do so.

This is a bit confusing to me.
>>To update the locally stored playback percent manually you must use the jsonrpc method I mentioned earlier to update Kodi's playback database for the file (listitem path url). It is not possible to set it directly to the listitem because Kodi will override from its database to be able manage resume natively.

Because prior to that you said this...
>>I bet the plugin is incorrectly setting the IsResumable flag when PercentPlayed is 0%
So I'm scratching my head wondering the first part you said that `It is not possible to set directly` then how could the plugin incorrectly set something that's not possible?  It'd be ignored no?  if I attempt to set `item.setProperty('percentplayed', str(percent_played))`, even if I force it to `50.0` Devhelper reports `0` always so it's ignored.  Seems a plugin even trying to set that property is pointless?  I'm also thinking for a plugin to even try and set `isResumable` is also pointless because I've watched Devhelper show that flip from `true` to `false` and I've never ever set that property.

So we can not set the listItem property `PercentPlayed` or even perhaps 'isResumable`?  What values should be set via jsonrpc?

Sorry Jurial I'm not trying to be a pita.  I'm just trying to get to the bottom of this and do it properly.  It seems either something has changed with this mechanics or we've all been doing it wrong.  I'll gladly accept my tongue lashing for my faults but strive to make it right...lol





So If I was to use jsonrpc to set, `PercentPlayed`

**Comment by 123Venom** [comment]
Just to confirm before I start researching to change/test things

```
def set_playprogress(filename, position, total):
    method = "Files.SetFileDetails"
    params = {"file": filename, "media": "video", "resume": {"position": position, "total": total}}
    return get_jsonrpc(method=method, params=params)
```

    
`filename:  url path for setResolvedUrl`?
`position: PercentPlayed `?
`total: TotalTime`?

I really appreciate your help Jurial.  Hate to confess it but I'm starting to think many are doing this wrong, or least no suited for the latest changes.

**Comment by derrgoo** [comment]
It appears to seem as if all are doing it the same way. As jurialmunkey explained to me above, 

"_ The reason you see "progress" in Eminence is because Eminence shows 1 pie piece for 0%-33%, so it shows up even when it is 0%. The plugin is not setting progress, that's just the fallback icon for progress in Eminence and would show even if the resume point was in the credits._

I never realized this until now that it doesn't track exact progress but only that you were watching. 

Thank you @123Venom to explore this as well.

**Comment by 123Venom** [comment]
@derrgoo I'd love this to be the new norm...
<img width="998" alt="AH_unwatched count2" src="https://user-images.githubusercontent.com/46383815/172299336-93797e30-6e33-4aad-8d49-940cdc4990d2.PNG">

I added some hack methods to make a multi episode list show the unwatched count but also that the current ListItem episode, with a resume point, shows as a percent icon...look close for the colored circle change watched percent.  The biggest problem with this hack is that while the list is an episode list note than none are identified as such.  You see no `S01E01` etc to know wtf it is.  That's because the hack tricks it into thinking it's a show list.  It'd prob need a custom label.  May not be ideal, but looks cool as shit,  and Jurial seeing this might not agree with the method I did to achieve it.  More importantly it seems to me some plugins need to change their scheme and Jurial has a FAR better understanding of this than most imo!!  His input is the only way this gets resolved and move forward for the community.

**Comment by derrgoo** [comment]
Looks like a great start getting the circle to appear and not blank. As he refers to the plug-in does the code need to be changed in that or the skin? I am sure he will have great ideas how to move forward. 👍👍

**Comment by jurialmunkey** [comment]
@123Venom 

Not a PITA at all! I'm definitely no expert. I only learnt python after getting frustrated with the skinning engine and definitely write a lot of crap code sticky taped together. It's only because I've been making skins for 10+ years that I have a decent grasp on how Kodi works!

There's a few different issues at play here, so I'll try to respond to the key points:

> I've never seen a plugin use the Kodi db for resume points, not that we shouldn't if the data exchange can be properly handled and seek assigned.

That's because prior to Matrix it wasn't possible. In Leia, the jsonrpc method only worked for physical filepaths. 

When Kodi was mostly physical libraries, managing progress was as simple as sharing a database across network devices. Streaming complicates things because we might watch outside our local home network and need a way to sync progress (e.g. via the streaming service itself; or a third-party scrobbler like Trakt).

To deal with that scenario, the jsonrpc method was expanded in Matrix to allow scripts to update resume points for virtual plugin:// paths.

> They then set the seek to resume point, that's pulled from plugins db, somewhere about the plugins player module for onAVStarted()

Manually seeking by monitoring the Player() class is a hack used prior to Matrix to deal with the above scenario where Kodi's local resume point doesn't match Trakt's remote resume point (or if the plugin doesn't use setResolvedURL at all so it needs to force resume via a hack).

The "correct" method is to use setResolvedURL to allow Kodi to manage seeking playback to the resume point based upon its locally stored value.

> So we can not set the listItem property PercentPlayed or even perhaps 'isResumable`? What values should be set via jsonrpc?

 PercentPlayed is a special property that cannot be set via xbmcplugin to the ListItem. Instead, Kodi updates this value by matching the ListItem(path=url) to its local database of resume points.

The correct method is to use jsonrpc to update the database with the progress for the playable callback path url that you use for playing the item (i.e. the plugin://plugin.video/play virtual url). Then, when you create a ListItem that has the IsPlayable flag and a matching path, Kodi will attach the progress in the database to that ListItem.

> Just to confirm before I start researching to change/test things
> {"file": filename, "media": "video", "resume": {"position": position, "total": total}}

**filename** is the plugin:// callback path for the _ListItem_ that you use to call the plugin to play. 
It is NOT the final url that you pass to setResolvedURL

**total** is the duration of the item in seconds.

**position** is the position in seconds i.e.`int(total_seconds * (playback_percent // 100))`

https://kodi.wiki/view/JSON-RPC_API/v12#Files.SetFileDetails
https://kodi.wiki/view/JSON-RPC_API/v12#Video.Resume


> I added some hack methods to make a multi episode list show the unwatched count but also that the current ListItem episode, with a resume point, shows as a percent icon

I agree it looks great (and very useful for those types of "Your Next Episodes" views). I just wish there was a proper way to do this that didn't rely on hacks (which all have their downsides as you're finding).

I also wanted something similar for tvshows/seasons where it would show unwatched episode count + progress indicator that is watched/total. Really annoying that skins can't do math because otherwise it would be simple! 

The progress indicator just needs a property with a value out of 100 in order to support from the skin side of things. All it would take is for there to be a standardised property name -- e.g. a `ListItem.Property(WatchedEpisodePercent)` -- but without standardisation there isn't much point adding it.

**Comment by jurialmunkey** [comment]
@derrgoo @xyzfre - Could you test v0.1.14? It should now show a timer icon if isresumable is true even if progress is 0%. That way at least you get an indication that it is resumable.

**Comment by xyzfre** [comment]
![image](https://user-images.githubusercontent.com/49699869/172365065-0b874e83-061b-4e6f-a607-0d9d0bf6187e.jpeg) Yep ALL GOOD now ,I'm seeing the timer icon on every episode I haven't finished watching this feature really comes in handy GREAT JOB 🙌🏼Thank you @jurialmunkey

**Comment by derrgoo** [comment]
Awesome. I am out of the house but see screen shot. All check when I get home. Thank you @jurialmunkey. 🙏

**Comment by derrgoo** [comment]
> @derrgoo @xyzfre - Could you test v0.1.14? It should now show a timer icon if isresumable is true even if progress is 0%. That way at least you get an indication that it is resumable.

Great stuff👍👍
