### ISSUE TITLE
[Feature] Media Info or Media Info 2 view

### ISSUE THREAD

**Issue by ReconVirus** [jurialmunkey/skin.arctic.horizon.2#245]
### Is your feature request related to a problem? Please describe.

no

### Describe the solution you'd like

Display episodes using the Media Info or Media Info 2 view from your horizon skin you did back on kodi 17 

### Screenshots and Additional Info

would go great when using [Icons Info for seasons](https://github.com/jurialmunkey/skin.arctic.horizon.2/issues/320)

Media Info 
![Kodi 7_8_2022 1_04_54 AM](https://user-images.githubusercontent.com/43733760/177946835-72f9e187-2d18-4152-b124-171ed71bdcc8.png)

![Screenshot 2022-06-20 190108](https://user-images.githubusercontent.com/43733760/174717369-2a7a1f55-f150-4e40-b868-a664c61741ff.png)

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by ReconVirus** [comment]
Horizon skin working on Matrix by bartolomesoriano for reference code

https://github.com/bartolomesoriano/skin.horizon

**Comment by jurialmunkey** [comment]
> Horizon skin working on Matrix by bartolomesoriano for reference code
> 
> https://github.com/bartolomesoriano/skin.horizon

Considering I made that skin I'm pretty sure I know how it works.

**Comment by ReconVirus** [comment]
I was thinking the code itself differ from 17 to 19 wasnt really sure and figure this would have made it easier to port it over instead of writing the code itself from scratch not sure how this all works  to be honest

**Comment by jurialmunkey** [comment]
> I was thinking the code itself differ from 17 to 19 wasnt really sure and figure this would have made it easier to port it over instead of writing the code itself from scratch not sure how this all works to be honest

Skin xml is not significantly different between kodi versions. Just occasionally there are breaking changes because control ids change or dialogs get made redundant because multiple dialogs get combined into a single new one etc (eg dialogconfirm combined dialogprogress, dialogyesno, and dialog ok all into one). The basic approach to skinning remains the same in every version - anything you can do in an earlier version you can do in a later version.

Regardless, it is not possible to simple copy a view over from another skin because all the assets and underlying code is different. Plus I wouldn't do that anyway because it wouldn't fit. I will be adding a similar view but it won't look identical - it will just follow the same basic premise but with an Arctic Horizon flavour.
