### ISSUE TITLE
[Feature] Widget Aspect Ratio option per Widget

### ISSUE THREAD

**Issue by ray2301** [jurialmunkey/skin.arctic.horizon.2#254]
### Is your feature request related to a problem? Please describe.

When aspect ratio for a view is defined by the skin, it's usually "scale" so everything fits in the box.
But since we use many addons that have different kinds of icons, many times scaled view will do overscaling of the icon so "keep" would look much better if that was an option when defining a widget look.

### Describe the solution you'd like

If possible, i would like to be able to choose (override default) aspect ratio per widget in the same widget configuration window where i setup the widget.

If combined with a possibility to also choose between available art for the selected item (choose to show icon instead of fanart) would make them great addition to customizing the view of all the add-on widgets.

for example, radio de addon can only be shown as a square widget if i want to show my stations. but the icons are not consistent - some are wide, some are square so some stretch too much. if i choose landscape view, station icons will not show because addon fanart will show on the landscape widget. but putting it to landscape, choosing aspect ratio to keep and selecting "icon" for art would solve that everlasting problem with add-on views on widgets.

is that even possible to do per addon/path?

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
I'd rather deal directly with the scenarios where a different aspectratio is required rather than adding an override. An override will complicate and limit my ability to make design choices. 

If there is a specific scenario where scale is being used but it is not appropriate, please report it separately. I will deal with it in the skin _unless_ it is an issue with the add-on itself not setting an artwork/dbtype correctly, in which case it will be a matter of reporting to the add-on author.

Either way, scaling of artwork is not a choice to be made by the end user. Artwork scaling should adapt automatically to the scenario according to the design specifications of the skin.

**Comment by ray2301** [comment]
that's ok. it was just an idea i had at 3 AM while putting some widgets on my home screen.
plugin authors don't really think about views in many cases.
