### ISSUE TITLE
[Feature] cast in recommendation-reduce items

### ISSUE THREAD

**Issue by georgew21** [jurialmunkey/skin.arctic.horizon.2#255]
### Is your feature request related to a problem? Please describe.

Hello, thanks for enabling the option to disable recommendation lists. 

When we view the cast in recommendations lists, there are often over 60 actors because the widget loads all the members of cast.

 I think that it delays the loading because it loads the photos of all cast members and there are so many items.

### Describe the solution you'd like

It would be nice to have the option on settings to choose of 5, 10 or all members of cast. 

If we choose 5 we could see the main actors of the film, without waiting to load all the actors, as usually the main actors of a film is less than 10. 

Furthermote, there could be a last item to view more (something like next page), if someone wants to explore more of the cast and loads .

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Kodi's container item limits do not work like that. Assigning an item limit in the skin will not change loading times at all.

The plugin will still load the entire list regardless of whatever limit value you set in Kodi. The limit is only applied *after* the plugin has loaded its content.

For any limit to reduce loading time, it has to be done plugin side. In TMDbHelper (which provides the cast list), you will not get much performance benefit from limiting because the TMDb API provides the entire cast list data from the server in the same request.

The only thing which will improve performance of cast loading in real terms is to ensure that "aggregate cast list" is disabled in skin settings because that takes longer for the TMDb server to provide that call via the API rather than the standard non-aggregated cast list.

**Comment by jurialmunkey** [comment]
This issue will largely be solved by #204

**Comment by xyzfre** [comment]
I use a Nvidia shield 2019 Pro and with the new cast API method The cast loads on my end pretty fast,, I love the way now you get to see especially for TV show episodes the special cast members for each episode I was very impressed with this new feature and love the way it works 💯💯
