### ISSUE TITLE
[BUG] Movie plot autoscroll issues

### ISSUE THREAD

**Issue by rizreflects** [jurialmunkey/skin.arctic.horizon.2#285]
### Current Behavior

When scrolling left and right through the widgets, the movie plot resets to starting position every time (which is correct). However, if scrolling up or down (rather than left or right) the movie plot does not reset and keeps scrolling. In order to view the plot from the start, you must scroll right and then back left again. Sorry if my explanation is not great. I could probably send you a video if I'm not clear enough.

### Expected Behavior

Movie plot should reset to starting position each time when scrolling up or down, same as scrolling left or right

### Steps To Reproduce

Scroll up or down the widgets on the main homescreen.

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
I can't really reset the scroll due to how Kodi handles textboxes but I've added an option to disable textbox scrolling
`Skin Settings > Behaviour > Autoscroll textboxes`

As much as I would prefer to find a way to reset the scroll position on refocus, I can't seem to find any reliable way to do so.
