### ISSUE TITLE
[Feature] Add widget style that is the size of Landscape but uses full image like Big Landscape

### ISSUE THREAD

**Issue by eengert** [jurialmunkey/skin.arctic.horizon.2#290]
### Is your feature request related to a problem? Please describe.

After seeing the new Apps style, I wondered if you could also create a similar style that is sized between Apps and Big Landscape.

### Describe the solution you'd like

I like the Apps style for certain cases, but it's too small for other cases, such as a landscape widget for TV show episodes.  I find Big Landscape is too big for that.  I like the size of Landscape, but I want the image to cover the entire item like Apps and Big Landscape do and not have text at the bottom of the item under the image.  This text is redundant anyway when you have expanded info on.  Would it be difficult to create a new style like that - essentially Landscape style without the text?

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Different heights are problematic because Kodi grouplist position options are not great. Just try to use expand info with the Apps/Buttons view and youll see one of the already existing problems. 

The submenu size isn't too bad on this front due to its use pattern not really requiring info, so I include it. But larger widgets with different heights are going to be problematic.
