### ISSUE TITLE
Support for multiart posters and  clearart 

### ISSUE THREAD

**Issue by ctanyp** [jurialmunkey/skin.arctic.horizon.2#305]
### Is your feature request related to a problem? Please describe.

No problem.  Your work, the skin is wonderful in every sense of the word) Thank you very much for the opportunity to use and enjoy it as much as you:)  Just personal preferences which you might like...)

### Describe the solution you'd like

I would like if possible that you would add support for multiart posters and multiart clearart in the info dialog, similar to how it looks in Aeon Tayo. That is, the posters rotate and the clearlogo is replaced by clearart. I really like this feature and I would like you if possible, also add this feature if possible without giving you any difficulties!  And I also can’t help but ask because I’ve been waiting for this opportunity for a very long time!) Could you please change the type of music text also for something colorful and beautiful :)  

3>And the last! I apologize in advance!) You can make it so that when you scroll through the artists in Fullscreen mode, the albums of the artist will automatically turn on, and when you scroll through the album widgets, the album that is in focus will turn on) I also really like it!) Maybe you too :) In the presence of technical difficulties / impossibilities, you can of course ignore requests for musical features) But please, I would really like what I described very first. That is, the ability to rotate posters and change the logo to clearart in the information dialog like Aeon Tayo *

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
> add support for multiart posters

What is the benefit of having multiple posters? It sounds like it would be really annoying to have the poster constantly changing.

If you want to look at other artwork for the item, that is already possible via the posters and fanart gallery widgets in the recommendations window (press down from info dialog).

>  Could you please change the type of music text also for something colorful and beautiful :)

I have no idea what this means.


> You can make it so that when you scroll through the artists in Fullscreen mode, the albums of the artist will automatically turn on, and when you scroll through the album widgets, the album that is in focus will turn o

This sounds like a really bad idea. 

It would mean that whenever you go to the home screen, whatever you were listening to or watching would stop and something else would start playing. It would also make navigation a nightmare because playback would be constantly starting and stopping which will slow things down.

**Comment by ctanyp** [comment]
Hi    I just got up ..) Therefore, I'm sorry that I'm only now answering.
As for the possibility of posters, I really don’t think it’s unpleasant, on the contrary :) Well, I’m not saying of course that it’s absolutely necessary. I just wanted something like that at your own request ..) Of course, you decide here, if you support the idea, then you embody it!) If not, then of course I will not bother you with such requests and will treat you with understanding :) And if instead of the possibility of multi-art posters insert spinning diskart animation? Is it possible to shove it somewhere? Of course, so that it would not spoil the overall design and design =)
   And I agree with you about music! In fact, yesterday I also thought about it .. Maybe this is really not a good idea)) The music would turn off when switching and it would be annoying and create a real nightmare in use))) Musical text, that is, I meant the lyric text of the music. I would like a colorful design :) I also wanted to write that sometimes and even more often when switching songs in the playback window, for some reason I just get thrown out of the kodi..

**Comment by jurialmunkey** [comment]
You need to provide justification for the feature request. What purpose does having multiple posters serve? I don't just add random things for no reason to have resource wasting "bling" everywhere. This is the wrong skin if you're looking for spinning things and flashing lights. 

Lyrics support will be added. I just havent got to it yet.

**Comment by ctanyp** [comment]
Sorry then. In fact, there is no justification for the request for this feature, I just visually like this feature :) But even without this, for me this is the best skin of all!) And it's okay if you don't like the idea..) You are the owner here, it's up to you)
As for the lyrical style, thank you very much!) And I also wanted to know if you ever plan to add flixart? I just saw on the very first page that a similar function was supposed to come out

**Comment by krzysztofwinnik** [comment]
About the lyrics @jurialmunkey... I am a true fan of your designs since AZ2 through AH and now AH2, but one thing I just can't understand was the fancy colourful lyrics approach you had in your previous skins. Totally not in-line with simplicity in other views. Colourful letters might look good for pop music, but I just can't imagine how could it possible be OK while listening to David Bowie or Arctic Monkies. For me a good benchmark of how lyrics should be displayed is PlexAmp mobile app - are you familiar with it?

**Comment by ctanyp** [comment]
As for the lyrical part, you could do something similar by the way :) Of course, if you like this design.
![roku_lyrics_active](https://user-images.githubusercontent.com/108543572/177004124-488935f7-00fd-4fff-9ef8-1eb1fa8f3c53.png)

**Comment by ctanyp** [comment]
I don't listen to Taylor Swift)) This is a picture from the Internet if that)

**Comment by jurialmunkey** [comment]
> About the lyrics @jurialmunkey... I am a true fan of your designs since AZ2 through AH and now AH2, but one thing I just can't understand was the fancy colourful lyrics approach you had in your previous skins. Totally not in-line with simplicity in other views. Colourful letters might look good for pop music, but I just can't imagine how could it possible be OK while listening to David Bowie or Arctic Monkies. For me a good benchmark of how lyrics should be displayed is PlexAmp mobile app - are you familiar with it?

That lyrics bit was not actually made by me. It is a skin add-in called "Videolyrics" by manfeed: https://forum.kodi.tv/showthread.php?tid=308626

And yes I agree about it not really fitting which is the reason why I didn't port it over to AH2. Still not quite sure what I'm going to do for lyrics just yet which is why there's no lyrics support currently (rather make something that fits the style properly rather than just dump in videolyrics again - which I think is an amazing piece of work by manfeed but not really fitting here).

**Comment by ctanyp** [comment]
You arrange everything in the skin settings in such a way that it is worthy of respect and admiration) Thank you very much for this!) Take your time about the lyrical part. You are right of course .. When you find your suitable option that you really like, then decide what and how to do) Once again, thank you very much for your work, your creation can be said :) I have not seen anything more beautiful anywhere on the Internet. It's like some sort of future. +_+
