### ISSUE TITLE
[Feature] Disable auto scrolling text

### ISSUE THREAD

**Issue by Tee77** [jurialmunkey/skin.arctic.horizon.2#329]
### Skin section

Home Widgets

### Feature description

Option to disable auto scrolling text on home screen widgets. For longer programme descriptions, open information window to read full synopsis. When opened, synopsis in info window resets to first line. 

### Why is this feature needed? Please justify and explain.

Completely subjective, but feel static text on home screen gives a cleaner, less distracting presentation. 

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Yeah I was thinking that myself before. Also fewer scrolling elements is better performance because fewer screen redraws. Would also fix this issue https://github.com/jurialmunkey/skin.arctic.horizon.2/issues/285 in a roundabout way.

Would be the inverse of this request https://github.com/jurialmunkey/skin.arctic.horizon.2/issues/21 so would need to be at least three options: None, Some, All.

**Comment by Tee77** [comment]
Nice. Was also planning to reference #285 but couldn’t find it.

**Comment by xyzfre** [comment]
This would be a really GREAT idea specially adding the options ,, None, Some , All ,, personally I like seeing the movie or TV show plot on the Home Screen widgets,, AH2 Is definitely the best skin I ever tried in so many years thank you for all your hard and amazing work @jurialmunkey

**Comment by jurialmunkey** [comment]
`Skin Settings > Behaviour > Autoscroll Textboxes / Autoscroll Labels`
