### ISSUE TITLE
[Feature] PVR channels widget - highlight style

### ISSUE THREAD

**Issue by Tee77** [jurialmunkey/skin.arctic.horizon.2#334]
### Skin section

PVR and Live TV

### Feature description

I'm currently using 800x450 transparent tv channel logos. When highlighting a channel on last played/ all channels widget, the highlight colour fills the whole item, as shown here..
![screenshot](https://user-images.githubusercontent.com/62660160/179044647-5e591cbd-4911-4b82-be5e-0b049d0a431f.png)

Ideally, I'd like this to behave the same as movie/ tv shows artwork, highlighting only borders and information at the bottom. I thought transparent icons were potentially causing the issue, so created a background fill for BBC Two just to test...

![screenshot1](https://user-images.githubusercontent.com/62660160/179045266-3daf2228-a77a-4bfd-8d8e-684f68e89264.png)

Also tried creating a rough opaque 450x450 BBC One icon and using a square style widget...
![screenshot4](https://user-images.githubusercontent.com/62660160/179084196-7133d570-f710-4aaf-8247-8c54ddf30287.png)

Clearly neither are any good, and I'm way off in terms of my understanding re. how this works. 

Finally, here's a photo I took when I was grabbing programme artwork (programmes on BBC One and BBC Two had no programme artwork available, but a 16:9 image for BBC Two's logo was grabbed as artwork). This is exactly what I'd love to see.
![image3](https://user-images.githubusercontent.com/62660160/179052834-60073302-80ff-4678-9ab6-256f74bcc190.jpg)

I'm guessing Kodi's required aspect ratio for channel icons means they'll never fit as I'd like into your current widget dimensions, but wanted to ask if any other options exist? If not, still looks great, but when you create something so close to perfection it's the little things that stand out, you know? 

### Why is this feature needed? Please justify and explain.

Highlighting a channel icon could look better.

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Yeah this is always a struggle because there's no way for the skin to inspect the image and determine ratio or whether it has transparency etc. So it has to guess based on context.

The current approach for pvr items is that if epgeventicon is available then aspect is set to scale without a border since these are generally 16x9 thumbs (or close enough) and so scaling won't cut off edges. 

If event icon is empty the assumption is a logo where aspect ratio could vary wildly, so keep aspect is applied to avoid cutting off edges. Additionally, I found some transparent logos pushing up against the edges looked bad, so a border is applied to shrink them down a bit.

So the current approach is very much a compromise to try to accommodate as many different setups as possible in all widget types. I could add a toggle to force scale for pvr widgets (in which case you'd need to modify all your logos to have an opaque background and has the correct 16x9 ratio).  I'm not really a fan of adding options to change skin design as ideally the skin should handle those types of decisions without user intervention. However, for pvr,it might be the case that it's the only way to handle things.

**Comment by jurialmunkey** [comment]
Yeah I'm trying a few things out but it is really a struggle to get it working nicely

Here's scale aspect. You can see how it is a real mixed bag -- works exceptionally well for some items and looks terrible for others. The logo for CNA works well because it is already padded and has good aspect, but other logos in landscape with less padding or a different aspect ratio look just as bad as the ones you can see in the square aspect here.

![Honeyview_screenshot00040](https://user-images.githubusercontent.com/4618719/179132614-6077a297-1685-42e3-8ce2-76923c665cf5.jpg)


Switching to an opaque background things get a bit better but we start running into issues with clarity -- e.g. CNA icon struggles for readability as it uses a dark grey and in spots the definition against the window background gets a bit murky

![Honeyview_screenshot00050](https://user-images.githubusercontent.com/4618719/179136951-552eeb4f-bb35-480e-993b-0b0cd5c703b3.jpg)

And for comparison, here's the current approach. There's still issues with clarity in some places but at least we have good definition against the window background and we've got a consistent look that works for most scenarios

![Honeyview_screenshot00047](https://user-images.githubusercontent.com/4618719/179137028-5b48459c-cd68-4693-be8d-e27bef97fbdb.jpg)

**Comment by jurialmunkey** [comment]
@Tee77 - Could you try the version in the linked PR #335 
https://github.com/jurialmunkey/skin.arctic.horizon.2/archive/refs/heads/pvr_opaque_focus.zip

Adds an option: 
`Skin Settings > Appearance > Opaque texture for focused PVR widgets`

It's not 100% perfect but I think it works quite nicely. Ideally I would keep the transparency but it requires creating diffuse masks for the selectbox for every scenario. Using an opaque texture mask instead is easier to implement and more adaptable to different circumstances but with the tradeoff of not being a 1:1 for perfect match in colour. I've got the colour match pretty close to the default background settings but with different background settings it isn't going to be as good.

![Honeyview_screenshot00051](https://user-images.githubusercontent.com/4618719/179147323-f240b7a0-08a7-4ca9-aeaa-2673d9bd06c7.jpg)

**Comment by Tee77** [comment]
Ah thanks man, this is really nice!
