### ISSUE TITLE
[Feature] Extra MetaData Info similar to "Extras" Window in "Ezra Addon"

### ISSUE THREAD

**Issue by Mr-7mdan** [jurialmunkey/skin.arctic.horizon.2#340]
### Skin section

Video Info Dialog

### Feature description

Let's take this movie as an Example : "The Man from Nowhere"
Currently, the video info window appears like this,
![image](https://user-images.githubusercontent.com/9439671/179226123-899567dc-352c-4292-a9fe-f06ff78d421b.png)
Note: Pay attention that below the movie title, next to the release year, the MPA rating is missing

Now, in the proposed extra's window from "Ezra Addon", it shows the following extra information:
![image](https://user-images.githubusercontent.com/9439671/179226691-69d3a4b9-37a8-4127-9bfd-376c65a5fe9e.png)
![image](https://user-images.githubusercontent.com/9439671/179226802-ed21b73b-e0b2-4259-b0bb-6413cf1bbeb6.png)
![image](https://user-images.githubusercontent.com/9439671/179226882-690f5136-bfa3-4eec-9a12-2a8a333ed281.png)
And much more.

### Why is this feature needed? Please justify and explain.

Advantages on top of current implemenation:
1- Noticeably faster in pulling up the meta data.
2- Versatility in configuring the window content/sections [Cast, Recommended, Review, Trivia, Blunders, Parental Guide, Posters, Fanart, More from Year, More from Network, More from Collections]
![image](https://user-images.githubusercontent.com/9439671/179227262-25de2d44-e508-4b62-8670-855fe0d13c06.png)
3- Ability to dig deeper by clicking on keywords, network, genre, director, etc.
4- Parental Guide details; Violance, Nudity, Language, etc. It enables you to click and view the details of each section.

Although, some of these sections are included in AH2, but the speed at which the details are pulled, and the parental guide section, and the reviews sections (Review, Trivia, Blunders) are the main points that gives it some advantage.

Major downside, it doesn't look as nice and AH2 implementation.

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
> 2- Versatility in configuring the window content/sections [Cast, Recommended, Review, Trivia, Blunders, Parental Guide, Posters, Fanart, More from Year, More from Network, More from Collections]

Already exists:
`Skin Settings > Details > Customise Recommendations`


> 3- Ability to dig deeper by clicking on keywords, network, genre, director, etc.

Also already exists. Movies from studio is a list displayed in recommendations window ondown. You can click on any crew member or cast member or keyword to browse those categories.

>  Note: Pay attention that below the movie title, next to the release year, the MPA rating is missing

Also already exists. I cannot help if the add-on you're using doesn't supply this information to the skin.

![Honeyview_screenshot00053](https://user-images.githubusercontent.com/4618719/179248493-5afc4c6c-409a-4e29-8c26-f4b4d29af9a6.jpg)

> 4- Parental Guide details; Violance, Nudity, Language, etc. It enables you to click and view the details of each section. (Review, Trivia, Blunders) 

All this data is stolen from IMDb against their terms of use.

The IMDb API is **not** free to use and scraping their website in this way is not permitted. Just because it is possible to do something doesn't mean it is legal. 

Please don't ask for features from banned piracy add-ons.

**Comment by jurialmunkey** [comment]
> it is TMDB helper, i viewed the movie from trakt watchlist inside tmdb helper addon.

You need to enable retrieving additional details from TMDb in TMDbhelper settings.

> I didn’t know that. I would pay for the API if this feature is included in AH2.

Do you have a spare $400,000? Because that's how much a full license costs for 12 months

https://aws.amazon.com/marketplace/pp/prodview-nzspap6vaousm?sr=0-3&ref_=beagle&applicationId=AWSMPContessa#overview

Just the trivia/goofs api is $40,000 a year
https://aws.amazon.com/marketplace/pp/prodview-oscqg7q2ierx6?sr=0-12&ref_=beagle&applicationId=AWSMPContessa#offers

This is serious commercial data. Commercial use licences cost serious money.

> Whats your take on why it is faster especially when you pull down to the cast and recommendation section.

Scripted windows can control exactly how and when content loads, so it can load it in the order it wants and do pre-caching etc.

Tmdbhelper is not a scripted window so kodi attempts to load all the lists at the same time. That makes things feel slower because there is no organisation. The benefit in using native skin functions is that it all uses the same video info dialog for a consistent style/look/navigation throughout the skin and is much more flexible in terms of skinning. 

The downside with a native skinning approach is that it uses individual widgets, so there's no real no way to precache these results or tailor the data collection specifically to the window.. Kodi only starts loading the content after you click to open the recommendations window, whereas I assume Ezra starts pulling this data immediatly.

Btw if you want speed do NOT turn on expand info for recommendations (ie ratings+plot on info dialog widgets). That requires the service monitor to start in the recommendations window which slows things down. Same goes for aggregated cast/crew list - it is much slower because more data pulled.

> And people like me are just proposing much needed improvements that would enrich their daily experiences.

I am always happy to hear suggestions but they need to be legal!

I would love to have this information as it is very useful but that's also why it costs so much to license it from IMDB.

I already contribute thousands of hours of my time for free. I'm not interested in anything that might cause me legal troubles or cost me money.

**Comment by Mr-7mdan** [comment]
@jurialmunkey, Thank you for your reply and for all the hard work you are doing

> I am always happy to hear suggestions but they need to be legal!

As i suggested earlier, we can use free resources like;
[Kids-In-Mind](http://www.kids-in-mind.com/)
[Common Sense Media](http://www.commonsensemedia.org/)
[The Dove Foundation](http://www.dove.org/)
[Movie Guide](http://www.movieguide.org/)

it has been done before in the below addon, but it is no longer working since it relies on Python 2. It might assist if you changed your mind in the future.

https://github.com/robwebset/script.suitability

**Comment by jurialmunkey** [comment]
I'm not going to include data from religious websites (so no Dove or MovieGuide) and the other two sites explicitly state in their terms of use that reproduction and/or scraping is not permitted. 

Scraping Common Sense Media is not permitted by their terms of use
https://www.commonsensemedia.org/about-us/our-mission/site-terms-use

> [...] you will not [...] Use any robot, spider, site search/retrieval application or other manual or automatic device or process to retrieve, index, “scrape,” “data mine” or in any way gather Site content, or reproduce or circumvent the navigational structure or presentation of the Site or its contents. 


Same goes for Kids in Mind
https://kids-in-mind.com/terms.htm

> Copyright Policy - Folks, our features are copyrighted [...]  reproduction of anything appearing within this site without our written permission is illegal and in really bad taste -- and, yes, we will come after you.


Once again, as I said before, just because it is possible to do something does not mean that it is legal. Generally unless there is an API which explicitly states that it is free to use, taking data from other websites and reusing it is against copyright law in most countries (and definitely is where I live).
