### ISSUE TITLE
Focus bug in infoview for PVR items & context menu in File Manager

### ISSUE THREAD

**Issue by krzysztofwinnik** [jurialmunkey/skin.arctic.horizon.2#352]
### Skin section

Video Info Dialog

### Current Behavior

The latest commits have caused some interface elements to display incorrectly.

### Expected Behavior

As it was before

### Steps To Reproduce

For PVR info bug:
1. Go to EPG
2. Press i for info dialog
3. Press right to focus the last button
4. Press right again

For File Manager context menu bug:
1. Go to File Manager
2. Select any item
3. Press c for context menu

### Screenshots and Additional Info

![BBF7F917-FDB3-40A9-A136-79564B627DA3](https://user-images.githubusercontent.com/679205/179910573-c0e14b6a-c7e8-4c97-852b-9ab4e4c140ce.jpeg)
![Uploading DEB24EB0-E0E2-43FD-9142-15DF3C57499F.jpeg…]()
![CC668497-C0ED-417B-90C4-8FAB7A1B0C1C](https://user-images.githubusercontent.com/679205/179910909-fe82bb21-9db9-4bb1-9a42-49f785db7f7b.jpeg)

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
I knew about the context menu bug - latest commit will fix it.

The other bug I think always existed - it's because you're focusing the side menu but it has no items so Kodi gets confused about which control has focus. I've worked in a "fix" to prevent onright calling the menu when it is empty -- it doesn't fix the underlying issue but at least will prevent the most common scenario where it happens.
