### ISSUE TITLE
[Feature] Load Widgets based on selection of another main widget item

### ISSUE THREAD

**Issue by Mr-7mdan** [jurialmunkey/skin.arctic.horizon.2#358]
### Skin section

Home Widgets

### Feature description

Hi, the idea is to have a sub layer in the home menu that behaves very similar to the main menu.

Lets imagine the following:
Main menu items : Movies, Trakt, TV Shows
Main Widget in Movies menu item: Genres
Each genre has (Latest, and Trending widgets)

Currently; When user selects Movies, the widgets respond/load to his selection and the home screen loads only The Movies widgets. 

Proposed: After user selects movies, he goes down to the main widget and highlights/or clicks one of genres lets say Kids. Now, the proposed behavior, is to load sub-widgets for the selected genre (Latest Cartoon, Trending Anime, etc). 

I imagine that we need to create another Home dialog without the menu items. And move back the genres main widget up the screen to same location of the menu items in the Home Dialog. Then load the sub-widgets like you would load them in the current implementation.

I think we can do it without another dialog, if we reload the sub-widgets based on the selection in the main widget. Similar to what drinfernoo did in (Next Path and refresh single widget in his addon)

Also, the VideoInfoDialog can be used, to load a new sub-dialog thats display the said sub-widgets.

i understand that this means, that the main widget should have a different type that regular widgets.

### Why is this feature needed? Please justify and explain.

It expands the functionality of this skin, and enables the user to enjoy navigating the menus in a less restricted mannar.

This skin is shaping to be the best skin ever created for kodi. Adding new innovative features like this would set a new benchmark in the community.

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
This sounds very similar to a planned feature I have for "hub" windows.

Basically the hub windows will be a separate window with a fullscreen widget and set of widgets underneath. So you could make eg one hub for anime, another for kids and so on. 

Then in your submenu on the homescreen you would add a shortcut to that hub. When you click the shortcut it takes you to that hub window.

It would be nicer all on the homescreen but separating it into a separate hub window helps loading. every separate section we add on the home screen makes loading slower because Kodi tries to load every widget in the window at the same time. Whereas if these sections are they are separated into another window as a hub then Kodi will only load it when it is activated

**Comment by Mr-7mdan** [comment]
@jurialmunkey , this sounds amazing. I am super excited to try it out. Hubs sound like what i described. The behavior of the hubs while in focus or clicked would change the whole experience. 

I will try to visually demonstrate the concept I have in my mind. We might get more ideas regarding the final implementation & the options available.

**Comment by Mr-7mdan** [comment]
I do agree to have it as window, to save load time, You can make it load in the background when the hub is in focus by setting the visibility of the dialog to false, and if clicked, the visibility is changed to true.

When selecting a "Action" Genre hub:
![image](https://user-images.githubusercontent.com/9439671/180451731-b0f55527-a908-426b-96ba-e56ba905c429.png)

When selecting "Horror" Genre hub:
![image](https://user-images.githubusercontent.com/9439671/180451637-d880bc38-2478-4d37-beac-54911b5dafa3.png)

After a 2nd though, I think you've already done that in the keywords section of the VideoInfoDialog, the widget responds to the user selection and changes as the user changes his selection.

Best of luck my friend

**Comment by Liquidrag** [comment]
I'm also looking forward to hubs. Would be great to have hubs for my favorite genres with widgets pointed to many trakt lists.

**Comment by jurialmunkey** [comment]
@Mr-7mdan - I know it's been a long time coming but next version adds ability to have "stacked widgets"

`Choose Widget > Stacked`
![screenshot00246](https://user-images.githubusercontent.com/4618719/215237962-fe9307ae-1f91-4122-b753-2957775f46ab.jpg)

The "Stacked" widget will display the folder of the item focused in the widget above it. For instance, here is my "in-progress tvshows" and it is displaying the seasons as posters underneath in the stacked widget:
![screenshot00244](https://user-images.githubusercontent.com/4618719/215237993-e7e3fa92-105b-4c9c-9e9e-7b2327fc663e.jpg)

You can even stack multiple together. For instance, here is a second stacked widget underneath the seasons to display the episodes of the season of the inprogress show:
![screenshot00245](https://user-images.githubusercontent.com/4618719/215238041-9ec37f46-721f-4175-aa1b-0535604ff926.jpg)

**Comment by Mr-7mdan** [comment]
@jurialmunkey This is perfect. It is exactly what i had in mind. I tested it already and i am so excited to make different setups with this feature.

I would like to ask you couple of questions instead of opening separate issues for them. 
Firstly, How can we customize the “Hub - Custom”? I was able to do my own by editing the XML for now. Will we be able to use them as a menu item in the future or will it remain as “End of row action”?

Secondly, do you have plans for bringing the “hubs stacked poster row view” as a widget that can used anywhere else? 

![922DD774-EF06-459F-9E4E-A6A4E08198C0](https://user-images.githubusercontent.com/9439671/215255392-86ba06f7-03b9-4f61-8f8d-42b572729edf.jpeg)

**Comment by jurialmunkey** [comment]
> Firstly, How can we customize the “Hub - Custom”?  Will we be able to use them as a menu item in the future or will it remain as “End of row action”?

Set it as the main menu item and then options will appear underneath to customise it.

Choose item for menu > Common > Hub - Custom

It uses hidden submenus attached the main menu item, so you can make as many custom hubs as main menu items.

![screenshot00260](https://user-images.githubusercontent.com/4618719/215267641-ce941c05-e306-476c-a937-460c2379e921.jpg)


> Secondly, do you have plans for bringing the “hubs stacked poster row view” as a widget that can used anywhere else?

It's not feasible on the home screen. It needs special code which is really difficult to manage with all the different variables for the home screen. It only works in the hub because I've got more control over the layout and the IDs in use -- it's also partly why it is locked to landscape aspect only.
