### ISSUE TITLE
[BUG] External subtitle's country flag disappears after movie info is refreshed

### ISSUE THREAD

**Issue by Aemstel2** [jurialmunkey/skin.arctic.horizon.2#359]
### Skin section

Library Views

### Current Behavior

When a movie with external subtitles (.srt) is scanned into the library for the first time, it will correctly show the sub's country flag. But when refreshing the movie's info, or removing it and rescanning it into the library, it no longer shows the external sub country flag. There's no way of getting it to show again either, not even by removing the source and doing a complete rescan of the library.

### Expected Behavior

Always show the external sub's country flag. Also update correctly after a refresh, in case an external sub is added or removed at a later time.

### Steps To Reproduce

1. Scan a movie that has an external (.srt) subtitle into the library.
2. Go to the library view and notice that the sub's flag is correctly shown.
3. Refresh the movie's info or remove it from the library and do a new library scan and notice that the external sub's country flag has disappeared.

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [ ] I have confirmed that this bug does not occur in the default skin.

**Comment by Aemstel2** [comment]
I have not actually confirmed that this bug does not occur in the default skin. This is not possible, because the default skin does not show any subtitle country flags at all.

**Comment by jurialmunkey** [comment]
Confirming I can reproduce this issue. The `ListItem.SubtitleLanguage` and `ListItem.Property(SubtitleLanguage.1)` fields are blank after refreshing movie info. Scraper doesn't appear to matter.

Definitely not skin related. Looks like there's a bug report about this issue here: https://github.com/xbmc/xbmc/issues/19184

**Comment by jurialmunkey** [comment]
Here's a workaround. It involves exporting your library data as `.nfo` files and then manually editing the `<fileinfo>` details to add your external subs

1. Go to `Settings > Media > Library > Export Library` 
NOTE: Must have setting level Advanced or higher to see this option

2. Choose **Separate** when asked if you want to export separate files or a single file. 
This will export each movie's library metadata to a `.nfo` file in its folder.

3. Choose **No** when asked if you want to export thumbnails and fanart.
This option exports artwork from the cache, which is compressed, and not the original artwork. Plus we don't need the artwork anyway for this purpose, so no need to waste time and disk space exporting it.

4. Choose **Yes** to overwrite old files. 
Since Kodi imports `.nfo` data on library scan, overwriting them is fine because you're just exporting the same data back to them. The only reason to choose No here is if you have special .nfo files that you need to preserve but most of the time this is unlikely.

After following that process, you will have a `.nfo` file in every movie folder containing all its details. It will have the same name as the movie, just with `.nfo` on the end. Open that in a text editor

You're looking for the `<fileinfo>` part. It will look something like this (details will depend on your file of course).

```xml
<fileinfo>
    <streamdetails>
        <video>
            <codec>mpeg4</codec>
            <aspect>1.761905</aspect>
            <width>592</width>
            <height>336</height>
            <durationinseconds>5701</durationinseconds>
            <stereomode></stereomode>
        </video>
        <audio>
            <codec>mp3</codec>
            <language></language>
            <channels>2</channels>
        </audio>
    </streamdetails>
</fileinfo>
```

Now all you need to do is  add `<subtitle>` tags into the `<streamdetails>` section after the `</audio>` section. For example:

```xml
[...]
        </audio>
        <subtitle>
            <language>ENG</language>
        </subtitle>
        <subtitle>
            <language>ITA</language>
        </subtitle>
    </streamdetails>
</fileinfo>
```

Now go back to the movie in Kodi and choose "Refresh". When asked if you want to ignore local information choose "No" as that will get Kodi to load the data from the .nfo file instead of the internet.

If you ever want to refresh/update the info from the internet for whatever reason then you can choose "Yes" instead and then do the export/edit process again to add your external sub flags.

It's a bit of a pain and seems like a lot of work but it is actually super quick to do. Once you get used to using this method of library management you probably won't go back to the old way because it gives you *way* more control over your library metadata -- and you can still use it in tandem with normal scraper look-ups.

**Comment by Aemstel2** [comment]
Alright, thanks a lot for looking into it and the detailed solution! Hopefully they'll fix it someday.
