### ISSUE TITLE
[Feature] TMBDHelper background loading in Information page

### ISSUE THREAD

**Issue by JacopoV** [jurialmunkey/skin.arctic.horizon.2#367]
### Skin section

Video Info Dialog

### Feature description

It would be nice, if possible, to open up an option in the skin settings to allow, in the Information Page, to load all the TMDBHelper data in the background, while reading the plot and other informations.

At that point, by pressing the arrow down to access all the extra info (for example : cast, seasons, director, fanart etc), there won't be any loading and the information available straight away. 

### Why is this feature needed? Please justify and explain.

It would be nice to have, especially on mid/low spec devices such as Android TV/Shield, which take a chunk of time loading all the data.

At that point as soon as the user is done reading the plot or rating or other infos, by pressing arrow down, informations would be accessible without any loading time. 

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
I'm not sure if it would really save that much time. 

Sure, maybe occasionally people are just browsing and take their time but I think most of the time users go to the info dialog for a specific reason. If their intention is to view cast or recommendations etc. then they probably press down almost straight away.

Pre-loading the list in a hidden container could also make things worse. For instance, if the hidden container hasn't finished loading and the user presses down, then that list won't be cached in TMDbHelper. So when Kodi asks for the list again in the recommendations window, TMDbHelper is going to have to load it from scratch because it isn't in the cache.

I think a different approach is needed -- e.g. an option to show widgets in a type of combined view with buttons for each list and when the user clicks the button the list loads underneath.

**Comment by JacopoV** [comment]
They seem reasonable good points, def you have a better understanding of the possible side effects 😉

Well thanks anyways for your time 👌you can close this one if you want 👍

**Comment by jurialmunkey** [comment]
I'll leave it open for now, as improving loading of recommendations is something I've definitely been thinking about -- just don't know what the optimal solution is.

Honestly, I had exactly the same thinking as you about a week ago and was almost about to implement something similar. That's the only reason I had these downsides ready to go -- because I'd thought about them last week!

**Comment by JacopoV** [comment]
Well then sounds good.

It's not crazy slow on Shield (roughly 3/5 seconds) so that's why I thought the background loading was worth it anyway.

But I ll leave it to you when you find a proper solution and you get higher priorities done.

Thanks a lot again!

**Comment by jurialmunkey** [comment]
> It's not crazy slow on Shield (roughly 3/5 seconds) so that's why I thought the background loading was worth it anyway.

What's the time like once it is cached? e.g. if you go to one movie, go down and let everything load, then go to another movie and load recommendations, then go back to the first one does it then load practically instantly?

Because that's essentially the same as pre-loading them -- and if there's still a significant delay, it might not be the way to getting better loading and it might be due to something else on Android (e.g. if the python interpreter is slow to load on Android, nothing in the skin or plugin is going to make that faster).

**Comment by JacopoV** [comment]
i would say that there's no caching at all both on Android TV and Shield (tried both).

If i go to info page for movie A > info page > arrow down >load everything, back out and pick movie B > info page > arrow down > load everything, and then go back to movie A, movie A starts from scratch. The same if moving back to movie B. 

On Win/OSX is it different ?

**Comment by jurialmunkey** [comment]
TMDbHelper definitely caches everything. Loading the list a second time should be considerably faster because all the requests are saved to disk.

There is a short delay while Kodi initialises the python interpreter and calls TMDbHelper -- but once TMDbHelper is running, the time spent on sending a cached list to Kodi is barely nothing.

For instance, here is TMDbH's directory timer report for retrieving cast the first time for Shutter Island:
```
info=cast&nextpage=false&fanarttv=false&cacheonly=true&type=movie&imdb_id=tt1130884
------------------------------
get_list       :   1.215 sec
add_items      :   0.103 sec
------------------------------
Total          :   1.319 sec
```

And then loading the same cast list for Shutter Island again now that it is cached after I looked at the cast for The Departed to refresh the listing:
```
info=cast&nextpage=false&fanarttv=false&cacheonly=true&type=movie&imdb_id=tt1130884
------------------------------
get_list       :   0.010 sec
add_items      :   0.076 sec
------------------------------
Total          :   0.087 sec
```

You can see that getting the cached list is about 15x faster. On windows, if the items are already cached you start seeing the lists almost immediately. 

There's still a bit of a delay between each subsequent list showing up on screen where Kodi hits a bottleneck loading the items into the GUI but because the lists show up in order it isn't very apparent (e.g. Cast will show practically immediately and then Recommendations will take a moment longer and so on as you go down).

If you're having long loading times on Android even after TMDbH has cached the items that indicates that the issue isn't caching and there's something else going on. My guess is that on Android Kodi is taking much longer to load the python interpreter before TMDbHelper is even started.

**Comment by JacopoV** [comment]
Apologies, i must have used the "caching" term in an inappropriate manner. 
Def TMDBHelper is caching, because when starts building all the lists (like cast for example), all the images popups up instantly. 
It's the lists creation, that it's taking time for sure. Because i see the spinner loading from Kodi, and once it's done, all the images are already there, on the fly. 

That's why i suggested these background loading (for the lists at this point) to buy some time. 

I tried clearing the cache and it's def taking much more time the first round. After that, it's working as intended (the cache per se).

**Comment by jurialmunkey** [comment]
TMDbHelper only adds metadata. Once you see items on screen then TMDbHelper is already finished (even if the artwork is blank). TMDbHelper only supplies the URL to the image, then Kodi downloads that artwork later after the items are created.

Basically, a skin will defines a list container which has an itemlayout defining the look of each item and a content path with a plugin:// URI for the list

When Kodi sees that list, the following happens:

1. Kodi starts the python interpreter and calls that plugin by passing it the plugin:// URI parameters
2. The plugin uses the plugin:// URI parameters to determine what list it should load, then looks up the metadata for the items, formats it appropriately, passes the items back to Kodi and then exits.
3. After the plugin exits, Kodi fills the list with the listitems.
4. Kodi then displays those listitems according to the itemlayout definition in the skin.
5. Once the items are on-screen, Kodi will load the artwork defined in the itemlayout by downloading it from the URL for that artwork type in the listitem metadata (or Kodi will load it from the texture cache if that image was previously downloaded)

Steps 1-3 happen while the busy spinner is on.

Only Steps 2 & 5 benefit from a list being preloaded (2 because metadata is stored in TMDbH cache; and 5 because images are stored in Kodi texture cache). Steps 1,3&4 must happen every time. So if you are still having a significant amount of time with the busy spinner on the second time a list loads then preloading the list will not help because the problem is either Step 1 or 3 which are both on the Kodi side of things.

**Comment by JacopoV** [comment]
Thanks for the detailed clarification 😉

Well then there's not much to do considering it's landing on Kodi side!

Thanks anyways ✌️ I thought it was a bit simpler 😅

**Comment by jurialmunkey** [comment]
Yeah I really wish I had a Shield or some other Android device of some type to test on because I'd be interested to know on which side the delay is -- practically everyone with a Shield reports it. 

From what I've seen from people's logs it is the startup of the python interpreter in Step 1 that takes the time rather than the adding of the items in Step 3 -- but it is always more difficult to work via other people's logs than to have an actual device in front of you to test things on!

**Comment by JacopoV** [comment]
I recently moved to Shield because the Android TV hardware on the TV is way too underpowered to have a smooth experience with kodi.
Shield is very good for what it is, but can't compete with a computer. When I try on osx, it just insta load all widgets and infos. It's just crazy the difference.

Wish Kodi team could maybe look into Android platform if something can be done to speed up some bottlenecks

**Comment by xyzfre** [comment]
> Yeah I really wish I had a Shield or some other Android device of some type to test on because I'd be interested to know on which side the delay is -- practically everyone with a Shield reports it. 
> 
> 
> 
> From what I've seen from people's logs it is the startup of the python interpreter in Step 1 that takes the time rather than the adding of the items in Step 3 -- but it is always more difficult to work via other people's logs than to have an actual device in front of you to test things on!

Is there a way I can donate you an Nvidia shield I have a 2017 model that I used for less than a year because when the 2019 came out I bought one if there's a way let me know and I will happily donate my Nvidia Shield to you to help out us Nvidia users ,, Plus you deserve it for all those countless hours I'm sure you spent on your own time creating the skin for us end users

**Comment by JacopoV** [comment]
Hi @jurialmunkey!

I just updated to the last version since 3 weeks.
I can't find any info regarding this one, but somehow now it loads much much faster, which makes it more usable.
I just wanted to let you know 😊
I do think there's a bug by clicking the arrow down in the info page, because for a second or more, nothing happens (before was moving to the new page instantly).
This causes to have multiple overlays with the cast etc if you click again because you have no an actual feedback that something is happening 😊

**Comment by jurialmunkey** [comment]
Yes there were significant improvements made because I switched to a scripted window in tmdbhelper (similar to how extended info used to . The downside is because it is a script rather than a native skin window it can be delayed to open depending on how long kodi takes to initialise python. There's never going to be a perfect approach but I think this one is better overall as the speed benefit of a scripted window is worth the other downsides

**Comment by JacopoV** [comment]
@jurialmunkey I see 😋 it's indeed faster, also when clicking on a cast member to read the informations. It's way more usable.

About the downside and loading time for the window, not sure if possible, can the focus on the button be removed? Maybe you thought already and it's not possible!

Crazy good job man! Thanks for everything!
