### ISSUE TITLE
[Feature] Episode Number in Info Line and OSD

### ISSUE THREAD

**Issue by Kayzels** [jurialmunkey/skin.arctic.horizon.2#369]
### Skin section

Fullscreen Video OSD

### Feature description

At the moment the episode number is displayed as "Episode S6E4". If you read that out loud, that is "Episode Season 6 Episode 4".
So it would be great if the prefix saying "Episode" could be hidden, so it just says "S6E4". Another option would be to have it written out, like "Season 6 Episode 4", but I think the shorter is better.
Original:
![EpisodeLabel Original](https://user-images.githubusercontent.com/72696811/180783684-5439c463-4465-4dfe-a74e-9d04250740b9.png)
Proposed:
![EpisodeLabel Change](https://user-images.githubusercontent.com/72696811/180783740-5283f05d-5cec-4723-9607-af0f05141a9c.png)

### Why is this feature needed? Please justify and explain.

This would be nice to have, as it can reduce the width of the info line, and also improve readability.

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
> "Episode S6E4". If you read that out loud, that is "Episode Season 6 Episode 4".

Okay I never really thought about it that way but now that you've pointed it out it is really bugging me. I'll switch it to be "Episode 6x4" format instead.

The reason it states "Episode" is to make it clear what the item type is because it isn't always immediately clear whether something is a tvshow, season, or episode (especially if thumbs are hidden to prevent spoilers).

It is particularly useful in the combined season/episode view because it allows eye focus to anchor on the same spot in the info line and get immediate feedback about whether the seasons or episodes are focused without actually needing to look down at the row of items.

**Comment by ShibajiCh** [comment]
Hi @jurialmunkey,

I might sound a bit too nit picky but I think the episode format text will look better if it matches the text in the widget image. For example, in the below screenshot the episode name for "Sherlock" above the widget image is currently 1x3, whereas in the landscape image it is 1x03. So I think it will look better if both of them matches. So I'd suggest to make both the texts, i.e. above and within the image same, which should be 1x03. Hope I could explain what I meant. Please let me know if I need to open a separate ticket for this request.

![IMG20220726024138](https://user-images.githubusercontent.com/65297828/180875570-4b2eb0a4-d745-4a27-8f88-940b0b26eddd.jpg)

Thanks and Regards,
ShibajiCh.

**Comment by jurialmunkey** [comment]
> Sorry if I might sound a bit too nit picky

@ShibajiCh - No, not at all! It annoys me too. I really wish Kodi didn't 0 pad the episode number because there's no easy way for the skin to get the label formatted that way. Anyway, a workaround will be added in next update for it (basically checks if the episode is less than 0 and adds it manually if needed).

**Comment by ShibajiCh** [comment]
> > Sorry if I might sound a bit too nit picky
> 
> @ShibajiCh - No, not at all! It annoys me too. I really wish Kodi didn't 0 pad the episode number because there's no easy way for the skin to get the label formatted that way. Anyway, a workaround will be added in next update for it (basically checks if the episode is less than 0 and adds it manually if needed).

Hi @jurialmunkey,

Thank you so much! It's looking great now in the latest version. 🙂

![IMG20220726143158](https://user-images.githubusercontent.com/65297828/180968564-83359c33-74b1-420f-b49b-9e0b64137d4d.jpg)

Thanks and Regards,
ShibajiCh.
