### ISSUE TITLE
[BUG] Episode clearlogo being replaced by previous movie clearlogo

### ISSUE THREAD

**Issue by Kayzels** [jurialmunkey/skin.arctic.horizon.2#371]
### Skin section

Fullscreen Video OSD

### Current Behavior

As episodes don't seem to have their own clearlogo, when playing an episode it just displays the show name. It would be great to get the clearlogo for the TV show, but this might prove tricky. (I'm not sure if maybe it could use TMDbHelper to find the artwork)
However, if you watch a movie with a clearlogo, and then play an episode, then the clearlogo for the movie is shown instead of the name of the TV show.

### Expected Behavior

The TV show name should show, or a clearlogo for the TV show.

### Steps To Reproduce

1. Play a movie with a clearlogo.
2. Either stop playing the movie, or wait for it to end.
3. Start playing an episode, and pause to see the OSD.
4. The movie clearlogo is showing instead of the TV show.

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Clearlogo on OSD for episodes works for me. TMDbHelper will look up the artwork using fanart.tv and set it on playback. There is an issue in TMDbHelper where sometimes the previous logo does not clear properly and I'm not quite sure what the cause is yet: https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/751

But the logo itself works as you can see:
![Honeyview_screenshot00084](https://user-images.githubusercontent.com/4618719/180993460-95983f34-c85a-48ee-9407-02cd228466c3.jpg)

**Comment by alKODIque** [comment]
@jurialmunkey 
Yes,
I've noticed that percisting clearlogo issue is present when no clearlogo is available for the media being played.
I've had a similar issue before with TMDbH here: https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/659#issuecomment-1048432080

**Comment by jurialmunkey** [comment]
@Kayzels @alKODIque - Could you test v4.10.16 of TMDbHelper. Just had a bit of realisation about what the cause might be and pretty sure I've managed to fix the persistent logo issue.

@Kayzels - Not sure if this will get you logos for episodes or whether that's another issue you're having at the same time, but it should properly clear out the old logo now at least.

**Comment by alKODIque** [comment]
Unfortunately, it did not resolved the issue for me...
Clearlogo of the last tv show is there when I play IPTV channel

**Comment by jurialmunkey** [comment]
@alKODIque - Did you restart Kodi after installing new version of TMDbHelper?

**Comment by alKODIque** [comment]
No, I did not..
And I was just about to tell you that I just tried after a restart and it's working!!

So Thanks, looks like you resolved the issue 🎉

**Comment by Kayzels** [comment]
After the TMDbHelper update, and changing settings in TMDbHelper so it uses Fanart.tv instead of Tmdb, Kodi crashed when I tried to play a movie or an episode.
So I can't confirm that this fixes it or not

**Comment by jurialmunkey** [comment]
> No, I did not.. And I was just about to tell you that I,ve tried after a restart and it's working!! (I've play a tv show, then stop. Then I went to my IPTV and no more percisting clearlogo)
> 
> So Thanks, looks like you resolved the issue 🎉

Actually, from your comment I realised that if you play a movie and dont stop it and then play livetv it will still persist, so that should be fixed in 4.10.17 too.

**Comment by jurialmunkey** [comment]
> After the TMDbHelper update, and changing settings in TMDbHelper so it uses Fanart.tv instead of Tmdb, Kodi crashed when I tried to play a movie or an episode. So I can't confirm that this fixes it or not

I didn't really change much significant, I'm not sure what would cause a crash there in terms of the changes I made. Got a debug log?

**Comment by Kayzels** [comment]
Seems to be an issue when selecting a player for TMDbHelper. If I play directly from the addon, then it plays fine. And can confirm that the change did work.
I checked the kodi.log, and there were some mentions of the dummy video.
Is there something I should specifically enable for TMDBHelper debugging?

**Comment by Kayzels** [comment]
Seems I can play 1 video fine. Then when I select a second video, that sometimes plays, sometimes doesn't. And I haven't got a third video to play.
My log file is over 1000 lines, should I still send it?

**Comment by Kayzels** [comment]
[Log file for crash with playback](https://paste.kodi.tv/ahitayedoz.kodi)

**Comment by Kayzels** [comment]
Sorry for spamming. I can't reproduce the bug on my other machine, so I think I might just install Kodi from scratch.

**Comment by jurialmunkey** [comment]
@Kayzels - Can you try 4.10.18 of TMDbHelper? I think that'll fix you not getting the logo for episodes in general, also *hopefully* will fix the crash too but not certain on that front. 

I forgot about the dummy video, so I added some checks to avoid doing some unnecessary lookups while it is running and to just wait for the actual video -- also got me to spot another issue with the lookup. 

I realised that IMDb also has IDs for episodes not just tvshows. My assumption before was that the IMDb ID would always be for the parent tvshow like it was on TMDb and not the individual episode  -- so the lookup was failing when it was the episode ID because a tv ID was expected.

**Comment by Kayzels** [comment]
Can confirm that this displays the logo for episodes, and stops the crash. Can also confirm that if it doesn't find the clearlogo, it doesn't revert back to the old one. So this is fixed as of 4.10.18, from what I can tell.
