### ISSUE TITLE
[Feature] Scrolling textboxes could keep 2 lines at end, and not scroll if 2 lines

### ISSUE THREAD

**Issue by Kayzels** [jurialmunkey/skin.arctic.horizon.2#373]
### Skin section

Home Widgets

### Feature description

When the plot is shown for an item, it is shown in a textbox that scrolls. If there is only 1 line of text, it doesn't scroll. 
However, you can read 2 lines of text, so it would be great if it doesn't scroll if there are only 2 lines, so the entire plot can be read.
What happens at the moment is that it scrolls until the second line is where the first line was, and then has an empty line.
So, would it be possible to always show 2 lines? 
So if there were 3 lines of plot, it would scroll until the first line is hidden, and keep displaying the 2nd and 3rd lines, until it resets to showing the first line.

### Why is this feature needed? Please justify and explain.

It's irritating when there is a 2 line plot, with one word on the second line, and you have to wait for it to reset the scroll to read the first line. This would improve readability as well.

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
What fontset are you using? I don't see this issue using default fonts. Other possible cause is if your display isn't 16:9 ratio resolution. Resolutions other than 1920x1080 / 3840x2160 / 1280x720 are going to have issues with alignment.

As long as you're using one of those standard resolutions and the default font set then there shouldn't be any textbox scrolling issues.

**Comment by Kayzels** [comment]
Fontset I'm using is the default, which I think is Roboto Condensed.
Screen resolution is horrible: 1366x768, which is still 16:10

**Comment by jurialmunkey** [comment]
Oh I used to have one of those annoying 1366x768 TVs years ago. The 16:10 ratio is going to throw all the alignment off because the skin is design for 16:9 and Kodi tries to "fix" it by scaling the vertical -- there's not much that can be done about that short of redesigning the skin for a 16:10 ratio.

It's the same reason you're seeing the cut-off text in the video osd episodes. For me it has a clean three lines of text:

![image](https://user-images.githubusercontent.com/4618719/181007175-de9f53d9-0191-4317-aacb-5b424bda2005.png)

**Comment by Kayzels** [comment]
I read the ratio wrong. 1366x768 is 16:9 (actually a tiny bit below: 16.8995)

**Comment by jurialmunkey** [comment]
> I read the ratio wrong. 1366x768 is 16:9 (actually a tiny bit below: 16.8995)

Oh yeah you're right, that's 16:9. The 16:10 resolution I was thinking of is 1680x1050

Do you have Kodi in a window rather than fullscreen? Because your other screenshots look like the aspect ratio is squashed a bit which will throw off the text alignment -- basically Kodi will scale the dimensions according to resolution but it doesn't scale the fonts the same way. 

It's possible that the resolution not being perfect 16:9 is making the line height slightly off -- in 1080p or 4k the issue simply isn't there.

**Comment by Kayzels** [comment]
It's possible those screenshots were from kodi in windowed mode. But that was on the device I don't normally use for Kodi.
On the device I normally use, Kodi is always in full screen, but has the same issue.
Would be very irritating if it is that tiny difference that is causing these hassles

**Comment by Kayzels** [comment]
I can confirm that on my 1080p screen it doesn't show that extra line, or the text cutting off. So this does appear to be a resolution issue. That's disappointing. I think I might as well close this issue, because it doesn't seem worth it to try to solve this for a particular resolution. Unless there is an easy fix that can be done.

**Comment by Kayzels** [comment]
I just did a check with changing the plotbox font size from 30 to 29. It doesn't look significantly different, but definitely solves this issue. So I'm not sure if that is a change that could be implemented? It's a one line change. Will do a PR if you are ok with that change @jurialmunkey .

**Comment by Kayzels** [comment]
Ok. That's sad, but it makes sense. Would there maybe be a way to conditionally set it? Cuz I won't lie, I like being able to see the 2 lines. Otherwise what I'd probably end up doing each update is just manually changing it myself 😆

**Comment by jurialmunkey** [comment]
> I'm a little confused, though. Don't you already explicitly set the height? So if the font size is smaller that shouldn't change the height of the plotbox. It should still have a height of 40px, shouldn't it?

No I mean that the *linespacing* of each row of text will take 40px of height. So if you set a textbox to be 320px it will have 8 lines of text in that space.

Here's a comparison, 30px on left 29px on right. You can see how the text on the right side starts creeping up slightly each line.

![image](https://user-images.githubusercontent.com/4618719/181044092-44039c8f-5f1a-445a-8aa2-9cefec5c2f07.png)


It gets really obvious when you overlay them

![image](https://user-images.githubusercontent.com/4618719/181044551-dfe7c6c9-42df-4c37-9976-b81e33e8b9bb.png)

**Comment by Kayzels** [comment]
I see. So changing font size isn't a solution, unless the line spacing was increased, which would be messy. Maybe a solution would be to just increase the height a little. Like just add a margin of error to the height, so 81 instead of 80. As you see, the tails are quite close to the bottom of the grid, and that could be what messes up the scrolling. But that might also mess it up.
Honestly, I'm upset at the display designers who chose to not have a proper aspect ratio.

**Comment by Kayzels** [comment]
In the above, obviously the 29 font isn't centered inside the grid line, but it is still clearly inside the grid.

**Comment by Kayzels** [comment]
If you keep the size as 30, but change the line spacing from 1.14 to 1.13, it also works correctly. And I don't think that would really mess with the grid, would it?

**Comment by jurialmunkey** [comment]
> Maybe a solution would be to just increase the height a little. Like just add a margin of error to the height, so 81 instead of 80. As you see, the tails are quite close to the bottom of the grid, and that could be what messes up the scrolling

The way Kodi calculates line height is it finds the glyph with the tallest ascender and the glyph with longest descender and that becomes the bounding box height for the text row. That bounding box determines how labels align within vertical space and the linespacing value extends the bottom edge of that box when in a textbox (but not for a single line label).

A textbox doesn't scroll when the first and last rows are contained entirely within the textbox control. The problem is that the font keeps its aspectratio rather than stretching, so when the screen ratio is off by a bit then it wont match how the screen is being streched.

So the problem with extending the height of the textbox OR decreasing linespacing is that the very tallest characters will now show over the edge. You probably won't notice it ever in English as standard latin characters are not the tallest/longest ones. However, other languages with diacritics like Spanish or Arabic it will be really noticeable because those glyphs push right up against the edge of the bounding box.

There just really isn't any good solution (other than defining an entirely separate screen resolution with its own set of xml files).

**Comment by Kayzels** [comment]
Very well. To me the lesser of the evils is for it to not exactly line up with the grid, but I can manually set that up after an update. Thanks for your time. 😄

**Comment by Kayzels** [comment]
Are there any movies or something with info text with diacritics that I could test? I have set the plotheight size to 81. If the diacritic touches the bounding box, but doesn't go out of it, is that a problem? There is still spacing for the plotbox, so it shouldn't touch any other element.
I know I should probably just let this go.
I tried to figure out a way to define it as a setting, with a variable. Then I found out that you can't use variables for conditional height. So then I tried to do it using includes, but whenever I did that, the text would disappear, and you'd see a tiny white scrolling line.

**Comment by Kayzels** [comment]
Related to that, if I set a constant, say "info_plot_h" in Constants.xml, and then set the default in Info_Panel
So originally, it is
`<param name="plotheight" default="80"/>`
and I set it to
`<param name="plotheight" default="info_plot_h"/>`
then the same white scrolling line shows instead. Am I missing something?

**Comment by jurialmunkey** [comment]
> Are there any movies or something with info text with diacritics that I could test? I have set the plotheight size to 81. If the diacritic touches the bounding box, but doesn't go out of it, is that a problem? There is still spacing for the plotbox, so it shouldn't touch any other element. I know I should probably just let this go. I tried to figure out a way to define it as a setting, with a variable. Then I found out that you can't use variables for conditional height. So then I tried to do it using includes, but whenever I did that, the text would disappear, and you'd see a tiny white scrolling line.

It'd be more in other languages -- especially in Arabic the bounding box starts becoming an issue. I had a chance to have a look at things more closely today and I think you can probably get away with 1-2 px extra on the box. It is at about 4px you start seeing the tops of the next line in Arabic

This was at 4px over:
![image](https://user-images.githubusercontent.com/4618719/181252241-900e5d7b-897d-4b2c-b376-6eb03ec82bab.png)

> Related to that, if I set a constant, say "info_plot_h" in Constants.xml, and then set the default in Info_Panel ...  then the same white scrolling line shows instead. Am I missing something?

Note that you use `default=` when defining default value for the param in the include definition but you use `value=` when using the include.

e.g. 
```
<include name="MyInclude">
   <param name="myheight" default="mydefaultheightconst" />
   <definition>
   <control type="group">
         <height>$PARAM[myheight]</height>
```

```
<include content="MyInclude">
    <param name="myheight" default="mynewheightconst" />
</include>
```


Alternatively, you can just skip the default/value and do this instead:
`<param name="myheight">mydefaultheightconst</param>`

I think this approach is actually easier as it works as the default and the value. It's just the other style is the original style when params were introduced so I use it out of habit more than anything.

**Comment by Kayzels** [comment]
I have added this line to Contants.xml:
`<constant name="info_plot_h">80</constant>`

And then in Info.xml, in `<include name="Info_Panel">`,
I changed the line `<param name="plotheight" default="80"/>` to
`<param name="plotheight">info_plot_h</param>`

Instead of the plot though, I am getting a blank area:
![plot_missing1](https://user-images.githubusercontent.com/72696811/181275578-e4684181-1d63-4f0b-9b87-d4ccca6a7967.png)
![plot_missing2](https://user-images.githubusercontent.com/72696811/181275620-3e248d6a-2457-413d-ab58-9d52823929e1.png)

Am I changing the wrong files, or in the wrong place, maybe?

**Comment by jurialmunkey** [comment]
You need to define a negative value version of the constant too because if you look at the include you'll see that it uses negative bottom value to position below.

**Comment by Kayzels** [comment]
Thank you so much for your patience.

Putting constants aside, say I have an includes definition (I put it in defaults, idk where it should go)

```
<include name="Defs_Plot_Height">
    <param name="myHeight">81</param>
    <definition>
        <control type="group">
            <height>myHeight</height>
            <bottom>-myHeight</bottom>
        </control>
     </definition>
</include>
```

Then I would assume this would be added to the Info_Panel in Info.xml
But I'm not sure how to properly use it.

I think I'd need to have
```
<include content="Defs_Plot_Height">
    <param name="myHeight">plotheight</param>
</include>
```
but I'm not sure where to put it.

If I keep the line `<param name="plotheight" default="80"/>`, then the height is never changed to 81, and stays at 80.
If I remove the line, then the plot is hidden, except for a tiny scrolling white area.

If I move the line into the area where `$PARAM[plotheight]` is used:
```
<control type="group">
    <height>$PARAM[plotheight]</height>
    <bottom>-$PARAM[plotheight]</bottom>
```
then the plot shows, but it shows literally on top of the ratings. Also, it seems to scroll that extra line even if I set the number to 85.

I feel like I'm missing something. Sorry for being such a bother.

**Comment by Kayzels** [comment]
As you said 1-2px extra wouldn't run into issues, would it maybe be possible to set that to the default? Would prevent needing to write this workaround, but I understand if you don't want to do that.

**Comment by jurialmunkey** [comment]
Think of includes and params like copy paste templates

Here I define an include:

```
<include name="MyInclude">
  <param name="MyParam">MyParamDefaultValue</param>
  <definition>
  <control type="label">
    <label>$PARAM[MyParam]</label>
  </control>
  </definition>
</include>
```

Then here I use it:
```
<include content="MyInclude">
  <param name="MyParam">Foobar</param>
</include>
```

That's equivalent to me putting:
```
  <control type="label">
    <label>Foobar</label>
  </control>
```

If I didn't pass the param and just used the include
```
<include>MyInclude</include>
```

Then that's equivalent to me putting:
```
  <control type="label">
    <label>MyParamDefaultValue</label>
  </control>
```

Because that was the default value of `$PARAM[MyParam]` as defined in the include definition.

There's nothing special to includes and params. They are just very literally templates that Kodi builds into xml in memory by pasting the values you define in the params.

The params are literal. If you put `10` as the param value, 10 will be input

So you could have something like `$LOCALIZE[$PARAM[mylocalized]]`

And then if you use that include with `<param name="mylocalized">5</param>` then that will be `$LOCALIZE[5]` (which is the string "Settings")

**Comment by jurialmunkey** [comment]
So you'll see in the constants I have some negative ones like this 

```
<constant name="dialog_pad">40</constant>
<constant name="-dialog_pad">-40</constant>
```

That's because the $PARAM pastes the literal name.

So say I have
```
<include name="MyGroup">
    <control type="group">
        <bottom>-$PARAM[height]</bottom>
        <height>$PARAM[height]</bottom>
    </control>
</include>
```

Then I do:
```
<include content="MyGroup">
   <param name="height">dialog_pad</param>
</include>
```

That's equiavelnt to:
```
    <control type="group">
        <bottom>-dialog_pad</bottom>
        <height>dialog_pad</bottom>
    </control>
```

So that's why I also needed to have a constant called `-dialog_pad` because otherwise there wouldn't be any such value. The `-` here gets read as a hyphen, not a minus sign because the value is a string not a number (also skins can't do math)

**Comment by jurialmunkey** [comment]
That commit will add constants for plot height. Might help you understand how includes/params/constants work too
https://github.com/jurialmunkey/skin.arctic.horizon.2/commit/49c0c8a9efc79f6e900c1bdf9f7a5fb4c03fdbc7#

**Comment by Kayzels** [comment]
Oh my word, thank you so much. Sending a big ❤️ .
