### ISSUE TITLE
[BUG] wrong icon on first submenu item

### ISSUE THREAD

**Issue by krzysztofwinnik** [jurialmunkey/skin.arctic.horizon.2#39]
As I understand, AH2 is designed with submenu items displayd in the bottom of home view by default and there is no way to either change its position (as in AH1) or disable. That is confusing, but understandable if on purpose.
What is more confusing is that there is always at least one submenu item displayed even if there are no submenu items set in skin shortcuts. And that one submenu item is always mapped to Menu item action. So if I set menu action to 'noop' I still have one useless submenu button that does literally nothing. On top of that its icon do not corespiond with menu item icon in some cases... in other cases it does. 

Possible fix for this:
- make possible to disable 1st submenu item if there are no other submenu items
- make it display the same icon as set for menu item

<img width="1322" alt="Zrzut ekranu 2022-06-5 o 13 37 54" src="https://user-images.githubusercontent.com/679205/172048693-73a9beeb-ae6b-45ad-8b43-642ac282c854.png">

**Comment by jurialmunkey** [comment]
Option to disable submenu is available as of v0.1.5. 
You can also now add a submenu widget separately in widgets to position it instead.

The icon thing is this weird skinshortcuts quirk where sometimes it sets an icon as ListItem.Icon and other times it sets as ListItem.Thumb. That'll be fixed in 0.1.6 (commit I just made but I've got a couple of others before doing a new release)
