### ISSUE TITLE
[BUG] Watched Flags not showing on video addons (eg iPlayer WWW)

### ISSUE THREAD

**Issue by berkhornet** [jurialmunkey/skin.arctic.horizon.2#403]
### Skin section

Library Views

### Current Behavior

When an episode has been watched via an addon such as iPlayer WWW, the watched flag is not displayed - on Arctic Horizon a tick mark was displayed in this case. - originally reported under #294 and closed as a duplicate of #249. I have installed v0.3.10 of AH2 which closes #249, but the watched indicators are still not displayed.

### Expected Behavior

The watched indicator should be displayed

### Steps To Reproduce

Watch any episode, or flag as watched - the watched flag is not displayed

### Screenshots and Additional Info

![screenshot00002](https://user-images.githubusercontent.com/67786207/183277730-ad9ec6de-1fb4-4fd5-8ba6-3b9c863e660a.png)
![screenshot00003](https://user-images.githubusercontent.com/67786207/183277736-7bff5273-9d26-4fac-a58a-9dbb012b78c8.png)

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
What's the output of `Container.Content()` for this add-on?

**Comment by berkhornet** [comment]
Hi. For this addon (iPlayer WWW) the container type is episode
![screenshot00004](https://user-images.githubusercontent.com/67786207/183278218-020904ba-fff7-48e2-8c62-d2d06a58a98d.png)
s

I've also tested with YouTube and the watched indicators don't appear there either (container content videos)

Also, I checked the skin settings and within Customise Indicators, Watched is ticked, just in case of user error!

**Comment by jurialmunkey** [comment]
Okay, this is a plugin issue where the plugin isn't setting the "episode" mediatype via setInfo() for the listitems. The plugin author should fix this so that the listitem mediatype matches the container content. 

If it was set correctly you would see:
![image](https://user-images.githubusercontent.com/4618719/183279984-2d1a2dab-7a32-4a55-bc5e-1740c9a7fe9a.png)

Youtube is a different story. I just missed videos dbtype by accident.

I can workaround this iPlayer bug but please report it to the author because they need to fix this. 

Whilst the overall cost of checking Container.Content() is relatively small, it is still a waste of CPU resources for a skin to need to add these types of workaround for plugins not properly setting the listitem mediatype. 

Setting mediatype for listitems in plugins was a Kodi v16 feature -- it's been 7 years, there's no excuse anymore for plugins authors still failing to set this metadata correctly.

**Comment by berkhornet** [comment]
@***@***.***>

Many thanks for this. I will report a bug against the offending addon.

Mick

**Comment by jurialmunkey** [comment]
I will have to revert the workaround I pushed. I just remembered why I stopped doing things that way - it has adverse side-effects on plugins which do things correctly.

For example: A container filled with episodes should have Container.Content(episodes). However, there might also be items that are *not* episodes, such as a "Next Page" item.

The next page item should *not* have an indicator because it is not playable. In a plugin that sets metadata appropriately, the skin is able to determine this by checking whether the listitem has a mediatype in ListItem.DBtype and display the listitem without an indicator

![image](https://user-images.githubusercontent.com/4618719/183281502-cc7f552a-26f3-4c48-a3dc-ce2617520ca5.png)

However, when we force a workaround of checking only container content we incorrectly end up with indicators on next page items. There is no possible way to deal with this situation other than have the plugin set the mediatype for the items.

![image](https://user-images.githubusercontent.com/4618719/183281474-be7f3b35-f2d3-427d-b0e0-3a292dc0327f.png)

**Comment by berkhornet** [comment]
Ok. No worries. I have raised a bug against the offending addon.

**Comment by jurialmunkey** [comment]
I think latest commit might be a better approach to workaround these types of issues. I'm now checking for a file extension OR if the IsPlayable property has been set. Files will have a file extension and plugins need to set IsPlayable property in order to work with setResolvedURL, so that should cover most scenarios where an item is playable but doesn't have mediatype set.

It won't be perfect but it should at least cover all plugins in official repo (e.g. BBC iPlayer) because using setResolvedURL is a requirement for repo inclusion. 3rd party plugins are, of course, a different story.

**Comment by berkhornet** [comment]
Brilliant! Many thanks again.
