### ISSUE TITLE
[Feature] Homepage widget spacing

### ISSUE THREAD

**Issue by jhawkstar** [jurialmunkey/skin.arctic.horizon.2#408]
### Skin section

Home Widgets

### Feature description

Hi!

Just would like to preface this request, the skin is absolutely amazing, and I've pretty much set it up perfectly, so thanks for all your hard work and commitment to getting back to so many demanding people!

In my setup, I like to keep it pretty simple with a widget row of landscape "collection" images, then poster "in progress" widget etc.

The only slight issue I'm having is the space between the top navigation "Movies | TV etc" and the first widget is quite large.

I've attached an image showing what it looks like on the left, you can see the large space is "double" what the space is between the widgets after the first space. Is there any way of tightening this space up to look more like on the right of the attachment?

Thanks again, and look forward to hearing back from you.

### Why is this feature needed? Please justify and explain.

Reduce padding to increase viewable widgets. 

Space means that certain rows of widgets are being hidden below the fold.

### Screenshots and Additional Info

![1](https://user-images.githubusercontent.com/110822707/183400162-26659dca-42f8-4590-bf60-91f80ebcdd4c.jpg)

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
This unfortunately is not likely to be possible.

The positioning of the widgets needs to be uniform to allow for the slide animation when transitioning to the full expanded info version of widgets. If the widget position varies then the slide animation will not align correctly.

I did consider changing the positioning in general to be higher up rather than centered. The problem is that then the full expanded widget has to travel even further to slide into position -- i.e. rather than from center to bottom, it now needs to move from top to bottom which essentially doubles the distance it needs to move and doesn't look particularly great.
