### ISSUE TITLE
[Feature] Add "Hide Watched" option to the Top Rated widget

### ISSUE THREAD

**Issue by chcore** [jurialmunkey/skin.arctic.horizon.2#418]
### Skin section

Home Widgets

### Feature description

Add a "hide watched" option to the "Top Rated" widget (if it's even possible!) so that it excludes films I have already seen.

### Why is this feature needed? Please justify and explain.

I've seen too many top rated films, and don't want to have to scroll past all of them needlessly. Maybe it's possible to sort the widget items by "date last played", which would "hide" them at the end, but then I can no longer sort them by rating as I would prefer.

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Skins can't control this behaviour. 

If it is library content just make a smart playlist with the required rules and use it as the widget (ie sort by rating descending and play count is 0). 

If it is addon content then you need to ask the addon author for this feature.

**Comment by chcore** [comment]
Thanks, good tip. I think this can be closed.

**Comment by jurialmunkey** [comment]
Yeah the top rated etc. default widgets are all actually just smart playlists shipped with the skin (they're in the `extras/playlists` folder if you want to have a look at the rules - just open in a text editor).

The "Top Rated" is just this

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<smartplaylist type="movies">
    <name>Top Rated Movies</name>
    <match>all</match>
    <order direction="descending">rating</order>
</smartplaylist>
```

I personally like using the "lastplayed" rule for a lot of my widgets instead of playcount because that will stop recently watched movies showing up but still allow in movies that you haven't seen in a long time and might want to rewatch e.g. This is one I use

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<smartplaylist type="movies">
    <name>Top Rated Movies</name>
    <match>all</match>
    <rule field="lastplayed" operator="notinthelast">
        <value>90 Days</value>
    </rule>
    <order direction="descending">rating</order>
</smartplaylist>
```


Another one I like is IMDb Top250 randomised with the not in the last 90 days rule (also can swap out top250 for `rating greater than 8.5` to get a randomised top rated list).

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<smartplaylist type="movies">
    <name>Top 250 Movies</name>
    <match>all</match>
    <rule field="top250" operator="greaterthan">
        <value>0</value>
    </rule>
    <rule field="lastplayed" operator="notinthelast">
        <value>90 Days</value>
    </rule>
    <order direction="ascending">random</order>
</smartplaylist>
```
