### ISSUE TITLE
[BUG] Crash when moving mouse while playing content 

### ISSUE THREAD

**Issue by AstaFatherSatan** [jurialmunkey/skin.arctic.horizon.2#421]
### Skin section

PVR and Live TV

### Current Behavior

Kodi crashes on my celeron laptop when i move my mouse while playing a video or a IPTV stream.

### Expected Behavior

Kodi crashes while playing content when i move the mouse. This doesn't happen in the default estuary theme.

### Steps To Reproduce

Move the mouse when playing content.

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by AstaFatherSatan** [comment]
This appends onto issue #386 https://github.com/jurialmunkey/skin.arctic.horizon.2/issues/386

**Comment by jurialmunkey** [comment]
Please only report one bug per issue. The EPG crashing issue can be discussed in the existing report.

I cannot replicate this issue with the mouse. It works fine for me. Please supply a debug log of this issue.

**Comment by AstaFatherSatan** [comment]
How can i do so?

**Comment by jurialmunkey** [comment]
https://kodi.wiki/view/Log_file/Easy

**Comment by AstaFatherSatan** [comment]
[kodi.log](https://github.com/jurialmunkey/skin.arctic.horizon.2/files/9328895/kodi.log)

**Comment by jurialmunkey** [comment]
Using an old version of the skin. You have v0.3.6 installed when the most recent version is v0.3.21

Please don't tick the box saying that you're using the most recent version if you're aren't. Always update to the most recent version of the skin before reporting bugs, otherwise you're just wasting my time looking into things that are possibly already fixed.

Since you are on Linux, you are almost certainly experiencing the Linux nested include bug which was fixed in v0.3.13 -- if you had bothered to update to the most recent version of the skin you probably wouldn't have had this crash.
