### ISSUE TITLE
[BUG] TMDB Helper shows the last episode of the season on the reading information

### ISSUE THREAD

**Issue by JukeBoX87** [jurialmunkey/skin.arctic.horizon.2#428]
### Skin section

Fullscreen Video OSD

### Current Behavior

When I launch any episode of a season of a series, it always shows the last episode of the season in the current playback information. On Arctic Horizon 1 I found the same problem while on other skins I did not encounter this problem.

### Expected Behavior

I would like the reading information to match the episode read.

### Steps To Reproduce

1. Open TMDB Helper
2. Choose a series
3. Start an episode
4. Open the playback information

### Screenshots and Additional Info

![Sans titre 1](https://user-images.githubusercontent.com/104312163/184500867-ba457fa4-eea0-4a40-9926-13052ad7fedc.jpg)
![Sans titre 2](https://user-images.githubusercontent.com/104312163/184500872-8ad55569-d266-437b-a492-cd1ee5147526.jpg)

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Works fine for me. Sounds like an issue with whatever plugin you're using to play with rather than the skin or TMDbHelper.

![Screenshot 2022-08-14 123618](https://user-images.githubusercontent.com/4618719/184520135-d5269134-b3a9-44b7-9bb3-cd0b4f682fc9.jpg)

![Screenshot 2022-08-14 123529](https://user-images.githubusercontent.com/4618719/184520125-9bf86bd5-e94a-45bd-94e7-054840090b1d.jpg)

**Comment by jurialmunkey** [comment]
Most likely whatever end plugin you're using to play with does something unusual like try to pull metadata from the current ListItem. 

In the combined view, the viewtype is actually a Seasons view -- i.e. the season buttons are the viewtype and the episodes on top are a widget. So if the end plugin is trying to pull metadata about the item from the ListItem then it would be pulling from the Season button rather than Episode in the widget. For Season item, `ListItem.Episode` contains the total number of episodes for the season, hence why you'd be seeing that value.

If you actually open the end plugin you're using to play with in that same view instead of via TMDbHelper, I expect you will likely have exactly the same issue.

**Comment by JukeBoX87** [comment]
Hi! Indeed, after changing the view, everything is back to normal. Thanks a lot for your help.
