### ISSUE TITLE
[BUG] Some information missing from info dialog

### ISSUE THREAD

**Issue by Bequiet19** [jurialmunkey/skin.arctic.horizon.2#437]
### Skin section

Video Info Dialog

### Current Behavior

With the local library some information is not displayed in info dialog. It loads the list and then they disappear as if they don't exist and they do. It happens most often with genres in tv shows and with directors if there are more of one.

`ERROR <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.themoviedb.helper/?info=discover&with_genres=Science Fiction / Western&exclude_key=title&exclude_value=Westworld&nextpage=false&fanarttv=false&cacheonly=true&type=tv&query=Westworld&year=2016`

`ERROR <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.themoviedb.helper/?info=crew_in_movies&type=person&filter_key=job&filter_value=Director&query=Lilly Wachowski / Lana Wachowski&exclude_key=title&exclude_value=The Matrix&nextpage=false&fanarttv=false&cacheonly=true`

### Expected Behavior

/

### Steps To Reproduce

/

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Science Fiction is not a TV Show genre on TMDb. "Science Fiction" is only a movie genre; the tv equivalent is "Sci-Fi & Fantasy". 

*The genres currently available for TV shows are: Action & Adventure, Animation, Comedy, Crime, Documentary, Drama, Family, Kids, Mystery, News, Reality, Sci-Fi & Fantasy, Soap, Talk, War & Politics, and Western*
https://www.themoviedb.org/bible/tv/59f73eb49251416e71000024?language=en-AU

The list being empty is correct because there are no TV shows with a genre of "Science Fiction":
https://www.themoviedb.org/genre/878-science-fiction/tv

I can semi-fix the director issue by retrieving the list for the director with top billing. No particularly great way to get a list of movies where two people are directors other than writing new code for TMDbHelper 

I expect outside of the Wachowskis and the Coens there probably aren't that many director duos, so probably no worth the trouble. And in these cases they don't do many individual movies so using the top billing director should capture the majority of their catalogue anyway.
