### ISSUE TITLE
[Feature] Location of the classification icon (MPAA)

### ISSUE THREAD

**Issue by titelheld** [jurialmunkey/skin.arctic.horizon.2#441]
### Skin section

Other

### Feature description

Moving the MPAA classification logo to the left most position of the footer.

or

Moving the MPAA classification logo to either the info line or ratings line.

### Why is this feature needed? Please justify and explain.

Currently the MPAA classification icon is displayed in the **_right most location_** in the footer.

This changes its location of the MPAA classification icon depending on how many streaming providers are listed in the footer line.

By moving it to the **_left most position_** of the footer it will have a fixed place. Making it easier to find and streamlining the over all presentation of the skin.

An alternative placement could be in the info line or ratings line.

Personally i think, _**because it provides information**_ about the movie/episode it would fit better with the various ratings of the film (imdb, tmdb, rotten tomatoes etc.) or info line instead of being listed with the streaming providers in the footer.
An extra benefit of moving it to the info line or ratings line would be that the fullscreen widget would also be able to display the MPAA classification icon.

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by titelheld** [comment]
![image](https://user-images.githubusercontent.com/25116213/185863993-8f15148d-9fe2-435f-a738-583dc8e2895e.jpeg)

**Comment by titelheld** [comment]
Having thought about it a bit more I believe bottom left of the screen in the footer might be best as it avoid duplicate information in the info/ratings list. 

Because the classification mpaa is  already visible in text form In the info line.

**Comment by jurialmunkey** [comment]
It has to go at the end of the row in case the classification doesn't match an image. There's no good way to have visibility based upon whether a filename exists, so otherwise you would end up with a blank space if it doesn't sync up. 

It is especially problematic at the moment because I've inadvertently discovered an issue in the skinning engine where the `+` in some ratings breaks the variable and causes the skin engine to spam the log with errors. So I've had to remove all the matching variables for classifications such as `R18+` and `MA15+` etc. which means in a lot of countries there will be blank matches.

In terms of moving to infoline/ratings area - the image is too large. To reduce the vertical size to fit there would mean you wouldn't be able to read it which defeats the purpose. Plus, as you note, it already exists in the infoline as text.

**Comment by titelheld** [comment]
Thank you for your reply. 

What you say makes sense I also encountered cases in which there is no icon displayed such as NR [not rated].

So I guess the way it is now makes the most sense... a blank space is definitely not desirable.

**Comment by jurialmunkey** [comment]
> So I guess the way it is now makes the most sense... a blank space is definitely not desirable.

Yeah exactly. My first choice was the same as yours - left aligned at bottom but it just wasn't great. Also even when does get hidden (e.g. no MPAA value at all) it is annoying there too because it causes the codecs to jump.

> What you say makes sense I also encountered cases in which there is no icon displayed such as NR [not rated].

I think the classification pack is actually missing this icon altogether.
https://github.com/wyrm65/resource.images.classificationicons.colour/tree/master/resources

The variables are generated using a script I wrote based upon the filenames in the classification pack. For the ones that are in the pack, the only ones that cause issues with matching are the ones with the `+` since I can't use the variable matching for those.

Any with a `+` will need MPAA to match the classification perfectly -- e.g. `Australia MA15+` requires classification country to be `Australia` and the listitem MPAA field to be just `MA15+` with no prefix.

The rest will match via the variables e.g. `Rated R` `R` and `Australia R` as the MPAA value will all match `Australia R.png` if country is set as Australia. What changing the country does is change the preference when the MPAA doesn't specify as a country prefix e.g. setting country to USA will make `Rated R` and `R` match `USA R.png` instead.

**Comment by xyzfre** [comment]
Does the MPAA icon only work for library items in TMDb H,,on my end they don't show up when using TMDb H ,but with a different plugin Like Fen the MPAA icon show up for both Movies and TV Shows

**Comment by xyzfre** [comment]
So far I tried on 2 different devices a FS and Nvidia shield 2019 Pro both fresh installed Same behavior

**Comment by xyzfre** [comment]
> > Does the MPAA icon only work for library items in TMDb H,,on my end they don't show up when using TMDb H ,but with a different plugin Like Fen the MPAA icon show up for both Movies and TV Shows
> 
> 
> 
> Works fine for me.

https://user-images.githubusercontent.com/49699869/187224297-1df50cb9-6433-44e8-812f-8f61d8ebab6e.MOV TMDB H https://user-images.githubusercontent.com/49699869/187224424-4edd7803-4af0-4494-99be-16325cb1d443.MOV Fen ,, my apologies for the background noise

**Comment by xyzfre** [comment]
> > Does the MPAA icon only work for library items in TMDb H,,on my end they don't show up when using TMDb H ,but with a different plugin Like Fen the MPAA icon show up for both Movies and TV Shows
> 
> 
> 
> Works fine for me.

https://user-images.githubusercontent.com/49699869/187224872-3bd7957a-64fa-4448-8621-adf1a4a1a9b1.MOV

**Comment by xyzfre** [comment]
https://user-images.githubusercontent.com/49699869/187225244-ecb9f2d4-54f2-4816-9ecb-9b090b6c2e7d.MOV Fen

**Comment by xyzfre** [comment]
https://user-images.githubusercontent.com/49699869/187225348-7b28afee-db5b-43e4-a708-afbf9517291b.MOV

**Comment by xyzfre** [comment]
Second video is using Fen,,,, Nvidia Shield 2019 Pro K19.4

**Comment by jurialmunkey** [comment]
@xyzfre - It looks like you have an extra space in your MPAA prefix which will cause it not to match

e.g. it looks like you have
```
Rated  R
when you should have:
Rated R
```
```
Rated  PG
when you should have:
Rated PG
```

**Comment by xyzfre** [comment]
![image](https://user-images.githubusercontent.com/49699869/187245985-2eaea95d-83ae-4ae3-999c-b0e64877058b.jpeg) how can I fix it please,,this is how my MPAA is set by default is there something I should change here

**Comment by xyzfre** [comment]
> @xyzfre - It looks like you have an extra space in your MPAA prefix which will cause it not to match
> 
> 
> 
> e.g. it looks like you have
> 
> ```
> 
> Rated  R
> 
> when you should have:
> 
> Rated R
> 
> ```
> 
> ```
> 
> Rated  PG
> 
> when you should have:
> 
> Rated PG
> 
> ```

![image](https://user-images.githubusercontent.com/49699869/187249393-93d55806-0abe-44fe-a76d-8c4d51220e02.jpeg) how can I fix it please,,this is how my MPAA is set by default is there something I should change here

**Comment by jurialmunkey** [comment]
@xyzfre - Make sure that there are no spaces on either side of the "Rated" prefix. You likely have added a space on the end but a space is added automatically when the prefix is joined so you will in effect be adding two spaces.

You will also need to refresh item details for cached items to see the change.

**Comment by xyzfre** [comment]
@jurialmunkey I tried what you said about the spacing,![image](https://user-images.githubusercontent.com/49699869/187490368-c20f54f7-9c5a-48d8-aa92-e3b4bdaa0e93.jpeg)that didn't work ,I have never mess with the MPAA "Rated" Setting which I thought was weird when you mentioned the spacing but what actually work on my end was the deleting the word Rated from the Preffix and now all the MPAA icons show up

**Comment by xyzfre** [comment]
Glad I got it sorted really appreciate your response and all the hard work you put into AH2 it is truly the best skin I have ever tried lots of respect for your work

**Comment by xyzfre** [comment]
And one thing I notice it doesn't say the word Rated anymore now it shows up as example just PG-13,PG, etc.. which is better,because prior it would Display as "Rated PG-13" etc..![image](https://user-images.githubusercontent.com/49699869/187494531-f493ff61-93fc-4a29-b706-ff19234ecb48.jpeg)

**Comment by jurialmunkey** [comment]
Yeah no prefix will also work fine. No idea why you're getting a duplicated space (it is definitely two spaces, I can tell from your screenshots). I use the "Rated" prefix and I only have one.
