### ISSUE TITLE
[Feature] Expand fist widget on category hover

### ISSUE THREAD

**Issue by titelheld** [jurialmunkey/skin.arctic.horizon.2#445]
### Skin section

Home Widgets

### Feature description

Option to have the first widget expanded when hovering over the categories. 

Skin Settings > Menus > Customise home menu > *Category* > 1st/all widget always in expanded state

or

Skin Settings > Menus > Customise home menu > *Category* > Widgets > *widget* Show this widget always in expanded state

### Why is this feature needed? Please justify and explain.

I went back to Arctic Horizon 1 today just to see how my previous set up compared to the new Arctic Horizon setup.

One thing i never really liked about AH2 is that when there is only one widget present in a category the screen looks somewhat empty and uninviting because the widget is not expanded showing no information. 

By adding this feature categories with only one widget present will look fuller with less blank space and provide more information.

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by titelheld** [comment]
![image](https://user-images.githubusercontent.com/25116213/187012673-dcf3c10c-6ac0-4093-8d7e-595c92a4b767.jpeg)

AH1 - When hovering over a category the widget shows all information and the screen is filled out nicely

![image](https://user-images.githubusercontent.com/25116213/187012702-971789dd-f3a3-42ea-9c6f-8092d754ebd5.jpeg)

AH2 - Due to widget being unexpanded the screen looks empty and dull.

**Comment by titelheld** [comment]
I think this option would be a good addition for categories for which the standard full screen widget is not a good fit.

![image](https://user-images.githubusercontent.com/25116213/187012906-231aecb9-e249-4666-914f-9912aa31f727.jpeg)

![image](https://user-images.githubusercontent.com/25116213/187012909-bb641fc1-12ba-4325-ada8-846093610856.jpeg)

![image](https://user-images.githubusercontent.com/25116213/187012919-e2347972-656f-4a47-8d2e-cdc5116893b3.jpeg)

**Comment by jurialmunkey** [comment]
In a roundabout way it is the same underlying issue as here: #250

Basically there's no good way to identify the first ID in the widget grouplist. More accurately, I know what the "first" ID of the group will be but I have no way to determine if it is actually the first list OR if it is hidden (e.g. no items) and the second list is actually the first (I can check each individually - but that would be a massive condition with lots of overhead).

In AH1 I used a really dodgy hack to get around it -- that's why the info position would switch places and even the basic info was delayed in showing. Don't really want to reproduce that hack again which is why these features haven't shown up yet. They're definitely something I want to do - it is just a matter of finding a good way that doesn't reproduce the issues in AH1.

**Comment by titelheld** [comment]
I see.

If there is no problem for full screen widgets to retrieve this information then perhaps it would be possible to solve this problem by introducing a new *expanded widget* viewtype for fullscreen widgets? 

That way if one desires a menu to contain only widgets and no traditional fullscreen widget. The menu would appear to be made up only of widgets / or one expanded widget.

**Comment by titelheld** [comment]
More generally put: Additional viewtypes for fullscreen widgets could be a solution to these issues.

**Comment by jurialmunkey** [comment]
That was exactly my first approach. However, the reuse of the ID blocks navigation in the grouplist.

The fullscreen widget works because the widget itself is actually *offscreen*. Each of these offscreen widgets reuse the same ID (id=301) so that there's a static ID that infopanel and background pull metadata (i.e. `Container(301).ListItem.Plot`)

The reason fullscreen navigates fine is because the "widget" in the grouplist is just the buttons which *do* have unique IDs. The "real" widget is offscreen so you never actually navigate to it (the buttons just pass through the clicks).

The problem with the expanded widget is that the widget *itself* needs to be in the grouplist because we need to see it.

It's the most promising approach and actually works really well *except* for the navigation issue. But that is a BIG issue! What's the point of a widget you can only see and can't interact with.

**Comment by jurialmunkey** [comment]
Okay, I think I've actually got this working well. Can you try v0.4.9? Should now be able to choose a "style" for the fullscreen widget which will switch it to full expanded mode (or choose "Fullscreen" style for standard mode).

Just needed to have a short delay where the parent group the widget is in was still visible so that the widget container has a chance to evaluate its own visibility first. That gets the skin engine to unlink the ID from the widget so the ID will be available for the widget in the next group to use.

**Comment by titelheld** [comment]
I gave it a shot on v0.4.10

it looks really good, just as I would have expected it. 
‘I like that when using these viewtypes the widget does not auto-scroll. 

It really makes Menüs with just one widget. So much nice to look at. Thanks for taking the time to implement this feature. 

Should I encounter any problem with it I will report back to you.

**Comment by titelheld** [comment]
After some fiddling. 

Style
Sort type
Sort direction

seem to be working

The Limit ruction has some problems.
I first tried auto-fit to width and this function does not seem to be working (at least for square view)
I think limit 10 works , did not get around testing other limits .

Another bug, after setting the limit, the menu does not display the selected limit

**Comment by titelheld** [comment]
![image](https://user-images.githubusercontent.com/25116213/187076671-85198805-eae6-40af-9dff-b2919cd6548f.jpeg)
