### ISSUE TITLE
[BUG] Widgets move whilst navigating through them

### ISSUE THREAD

**Issue by berkhornet** [jurialmunkey/skin.arctic.horizon.2#449]
### Skin section

Home Widgets

### Current Behavior

When navigating widgets on the home page, if there is more than one widget, when pressing down to reach the second widget the widget rows move upwards. I'm not sure if this has always been the case but a recent update did alter the position of widgets.

Not a major issue, just a bit "less than easy" on the eye. I'm pretty sure this didn;t happen with AH1. Attached screenshots demonstrate the movement.

### Expected Behavior

Ideally, no movement of widget rows whilst navigating.

### Steps To Reproduce

1. Create a home page menu item with more than one widget
2. Navigate to the second widget

### Screenshots and Additional Info

![screenshot00000](https://user-images.githubusercontent.com/67786207/187286000-85e5e73f-e3fd-4ff1-9c7f-6b50a019f9e7.png)

![screenshot00001](https://user-images.githubusercontent.com/67786207/187286025-86dd16a3-9deb-4530-80a4-3584fc2c8aa5.png)
![screenshot00002](https://user-images.githubusercontent.com/67786207/187286040-94b94e06-d5e2-45e6-93f8-a7ee75667401.png)

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
These widget styles are not meant to be used how you're using them. They are intended to be a one off row in the middle of a set of widgets.

The bug itself and how it should behave is actually the opposite of what you want. Every widget should be forced into the top row to maintain fixed positioning.

If you want to use a submenu sized widget at the end of the group without moving on navigatoon, that is what the specific submenu widget option is for. Just set your second widget as the submenu widget and it will act as a boundary bumper.

**Comment by berkhornet** [comment]
Many thanks for your very detailed response. All working as I would like now. FYI, in the example shown in the screenshots, the second widget was a submenu, but I had defined it in the "widgets" section of the menu item and not the "submenu widget" section (if that makes sense!

Thanks again, I'll close the issue.

**Comment by jurialmunkey** [comment]
Yeah that makes sense. That's what I meant by they are meant to be used as a row in the middle of a set of widgets. They won't work well if they are the last widget in the set, which is why that special separate submenu widget exists.

It's a little hard to explain but basically all the widgets have exactly the same height just leaving dead space below to force it into position. Then there is an invisible spacer group underneath each widget and it has a negative height value to pull the next widget up into that dead space.

So the invisible spacer group for the apps/button etc. style has more negative space since the widget is shorter, which is what causes the misalignment at the end and why there's a need for that special submenu bumper widget instead.

**Comment by berkhornet** [comment]
Brilliant! I'm beginning to understand (I think!) Thanks again
