### ISSUE TITLE
Modify poster aspect ratio

### ISSUE THREAD

**Issue by Shawn9347** [jurialmunkey/skin.arctic.horizon.2#451]
### Skin section

Home Widgets

### Feature description

Ability to change the poster aspect ratio to match it with plex poster aspect ratio. 

### Why is this feature needed? Please justify and explain.

I am using plex kodi connect and I sync my artwork from plex with it as well. I noticed that the aspect ratio of the plex posters is just a little taller than the one kodi uses. Estuary uses even smaller aspect ratio I think. Arctic horizon 2 aspect ratio comes very close to plex's but not exactly the same. I use resolution labels on my posters created automatically with plex-meta-manager so the top part is cut off. 

### Screenshots and Additional Info

Kodi:
![image](https://user-images.githubusercontent.com/48714886/187690133-23f09d0f-f2fa-4dcd-b359-b0f730d2841f.png)

Plex: 
![image](https://user-images.githubusercontent.com/48714886/187690228-333235ac-03a6-440e-b9c4-7c0cb038b9ee.png)

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Changing the aspect ratio of the posters would mean redesigning the entire skin as you would be changing the alignment of elements.

Poster sizing is designed for 680x1000 pixel posters (0.68 ratio) which has been TVDb's standardised sizing for at least 10 years  https://support.thetvdb.com/kb/faq.php?id=8

I use TVDb's ratio because it has remained consistent over the years when many other services do not enforce sizing rules. The 0.68 ratio of TVDb also acts as a good middle ground between 1000x1500 (~0.66) and FanartTV's 1000x1426 (~0.70).
