### ISSUE TITLE
[BUG] "Manage" button missing since "Wiki" button added

### ISSUE THREAD

**Issue by berkhornet** [jurialmunkey/skin.arctic.horizon.2#461]
### Skin section

Library Views

### Current Behavior

Since the introduction of the "Wiki" button (which is a great feature!) the "Manage" button no longer appears in the Video or Music libraries.
![screenshot00001](https://user-images.githubusercontent.com/67786207/189308400-9ba928d7-a048-4aa4-949b-7e9b7c6928af.png)

### Expected Behavior

Manage button should still be visible

### Steps To Reproduce

Navigate to Video or Music library
Select video, artist or album
Navigate to Info screen

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
There's not really enough room anymore when all the buttons are visible. You should still be able to access the menu by pressing right, so I felt it was the button best sacrificed.

Will be partially fixed once #206 is added because then you'll be able to choose which buttons show. Once that goes in I'll probably force the Manage button to always be visible and allow customization of the other four positions.

![Honeyview_screenshot00165](https://user-images.githubusercontent.com/4618719/189323715-9ce7cd36-8455-47cc-9924-400aa6a3f653.jpg)

**Comment by berkhornet** [comment]
@***@***.***>

Ok, got it - thanks!

Mick

**Comment by jurialmunkey** [comment]
Fixed with recent addition of Kiosk Mode options.
