### ISSUE TITLE
[BUG] Pressing down on info page gives error

### ISSUE THREAD

**Issue by ambulancePilot** [jurialmunkey/skin.arctic.horizon.2#472]
### Describe the bug

Pressing "down" on Information page doesn't result in cast etc showing up. Instead, it results in log error.

### Steps To Reproduce

Normally when I click Information in the context menu of an item, it opens the info page, then I press down and I see cast and other information. Recently, pressing down isn't doing that anymore. It's giving a log error instead.

### Debug log

`ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--`
`Error Type: <class 'ValueError'>`
`Error Contents: not enough values to unpack (expected 4, got 2)`
`ValueError: not enough values to unpack (expected 4, got 2)`
`-->End of Python script error report<--`
`ERROR <general>: GetDirectory - Error getting -`
`ERROR <general>: Control 2060 in window 13000 has been asked to focus, but it can't`

### Screenshots and Additional Info

Any help would be greatly appreciated. I am using Arctic Horizon 2, if it matters. Thank you!

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [X] I have uploaded my debug log.

**Comment by ambulancePilot** [comment]
Sorry about that! The error that popped up said "TMDb Helper error" or something to that effect. The item I can remember it happening on is Rings of Power (the new LotR series) however I tried several items from the same (and different) Trakt lists and it was hit and miss on whether it would work. All the lists were my personal ones.

I will be able to provide a full log later this evening. Thanks so much for looking into it!

**Comment by ambulancePilot** [comment]
Debug log: http://paste.kodi.tv/ikovihuhov

Thanks again!

**Comment by jurialmunkey** [comment]
Thanks for the log. I think there must be something in the way that particular addon you're using is formatting the item titles (probably adding colour tags or something like that).

Can you install v4.11.25 -- I added some extra logging which should help me see what exactly the issue is. Could you get me a new log using the new version. Make sure to enable debug logging in TMDbHelper settings -- you'll see it outputs a report "Opening Tv Recommendations GUI" in the log.

**Comment by jurialmunkey** [comment]
Actually, nevermind. I'm pretty sure I know what the issue is. That add-on is setting ListITem.Genre incorrectly by overriding the list behaviour with commas (and commas are a reserved character because they break script arguments).

Relatively easy fix but will need to update skin, plugin and module. (all minor changes but needed to make changes across each)

https://github.com/jurialmunkey/script.module.tmdbhelper/releases/tag/v0.0.6
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/releases/tag/v4.11.26
https://github.com/jurialmunkey/skin.arctic.horizon.2/releases/tag/v0.4.26

**Comment by ambulancePilot** [comment]
Wow, thanks for your dedication to your work. I'll update all those add-ons when I get home from work and report back, though I trust you've nailed it! 🙌🏻

**Comment by ambulancePilot** [comment]
Sorry I never commented back, it's all working as intended of course. Thanks again!
