### ISSUE TITLE
[BUG] Some video addons do show addon fanart instead episode thumbs

### ISSUE THREAD

**Issue by peat80** [jurialmunkey/skin.arctic.horizon.2#473]
### Skin section

Library Views

### Current Behavior

Some video addons seems to not load episode thumbs on landscape views and only show fanart.jpg of the addon instead on all episodes.

I have experienced this on the following addons:

South Park (plugin.video.southpark_unofficial)
JOYN (plugin.video.joyn)

Both are available in the official kodi repo. 

### Expected Behavior

Each episode should show its episode thumb.
I've checked with both plugins on estuary skin and there they do show the correct images.

### Steps To Reproduce

Open one of the mentioned plugins,
select a series and choosen a landscape view to show episode thumbs.

### Screenshots and Additional Info

![Kodi_20220920_234623](https://user-images.githubusercontent.com/32403292/191373836-929fc79a-9ebc-427e-8b5f-f990c4f386f7.png)
![Kodi_20220920_234701](https://user-images.githubusercontent.com/32403292/191373864-e8869545-7caf-4342-8fe6-b97129bd57ce.png)
![Kodi_20220920_235139](https://user-images.githubusercontent.com/32403292/191373882-88585029-599e-4413-b602-f9773cd82a8a.png)
![Kodi_20220920_235239](https://user-images.githubusercontent.com/32403292/191373919-74eedb25-a80a-4b3c-b932-63d43189c5a0.png)

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
It's because these addons are not correctly setting the mediatype for their listitems (I checked South Park addon but I assume it is the same with the others). Without mediatype (ListItem.DBType infolabel) the skin cannot determine if the item is an episode/video (display thumb) or a movie/tvshow/season (display fanart/landscape). The reason it "works" in Estuary is because that particular view in Estuary *only* displays thumbs and never displays fanart/landscape.

The ability for plugins to set ListItem.DBType (mediatype infolabel) was added 7 years ago in Krypton (2016). Since then, changes in the skinning engine for Krypton have meant that skins have been required to check ListItem.DBType instead of Container.Content() to determine the content type of an individual item: 
https://forum.kodi.tv/showthread.php?tid=299107

I can't keep making workarounds for addon authors who fail to code their plugins correctly when these requirements are nearing a decade old now. I recommend speaking to the addon authors and request that they set mediatype correctly for their listitems.
Kodi v16+ method: https://xbmc.github.io/docs.kodi.tv/master/kodi-dev-kit/group__python__xbmcgui__listitem.html#ga0f1e91e1d5aa61d8dd0eac90e8edbf18
Kodi v20+ method: https://xbmc.github.io/docs.kodi.tv/master/kodi-dev-kit/group__python___info_tag_video.html#ga4fdfd291958a0563ec380dc43419b1b5
