### ISSUE TITLE
[BUG] Slow response after marking an episode as watched on Trakt

### ISSUE THREAD

**Issue by juanma-cvega** [jurialmunkey/skin.arctic.horizon.2#508]
### Skin section

Library Views

### Current Behavior

Whenever I manually mark an episode as watched on Trakt when on the 'Next up' section of a TV show (I haven't actually tried inside a specific season), it takes between 30s and a minute just to finish loading on a Nvidia Shield 2019 Pro wired. After that, it shows the list but without that episode. Is there any way this can be sped up? I guess it is just reloading the list to get the maximum number of episodes that can be fit per page but maybe there is a way to cache the previous loaded list?

### Expected Behavior

The list to be refreshed faster.

### Steps To Reproduce

1. Go to a TV show
2. Go to the 'Next up' section.
3. Mark an episode as watched.
4. Wait. 

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by juanma-cvega** [comment]
I just realized this issue is more related to the addon than to the skin. Should I move it there?

**Comment by jurialmunkey** [comment]
Sorry, I thought I replied but obviously didn't!

Yeah, this would be add-on related rather than skin related. More to the point though, there's not much I can do about it on the TMDbHelper side either - that's just how long it takes to calculate the Next Up list.

Trakt annoyingly doesn't provide this list via the API and instead asks developers to calculate it themselves client side. For most apps that is fine because the app runs as a single instance with a central database. In most apps when hen you update watched status it will just update the data locally and then sync back to Trakt in the background.

The problem with Kodi is that each plugin entry is treated as a separate instance and has no idea what is happening in the other instances. Reloading the container makes it a new instance of the script, so it has to run through the whole routine of checking for new sync data and then recalculating and caching it.
