### ISSUE TITLE
[Feature] Local "Continue Watching" Widget

### ISSUE THREAD

**Issue by cboRD181** [jurialmunkey/skin.arctic.horizon.2#523]
### Skin section

Home Widgets

### Feature description

I'd like to suggest a custom widget for displaying a user's "Next Up" episodes from their library without needing to link Trakt.

### Why is this feature needed? Please justify and explain.

The Trakt "Your Next Episodes" list in TMDB Helper has several drawbacks in my experience:  Resume points are not consistently scrobbled, .strm files from my Kodi Library do not display correctly in the player (they list the raw file name without metadata, e.g. "exampleshowS01E01.mkv.strm", and don't work with the "Up Next" service to play subsequent episodes), the widget doesn't reload automatically upon an episode being watched, and it is somewhat slow to populate on lower power devices.  A solution that uses Kodi's internal watched status database would be more performant. 

The best option that exists without external dependencies as far as I can tell is Embuary Helper's "Next Up" list, but it [doesn't consistently sort correctly](https://github.com/sualfred/script.embuary.helper/issues/66) and isn't well maintained.  

If it's helpful the [Unfussy skin](https://github.com/louisbraun/script.unfussy.helper/blob/1771f53fcf7a442347d08014bc3ca0a13fb7e15f/resources/lib/plugin_content.py#L18) has an example of the logic needed to correctly list episodes "where you left off."

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Skin can't do anything about this. Kodi would need to provide a proper method to provide this list via a smart playlist.

I'm not interested in writing plugins for library content only because I use a mixture of online streaming services such as Netflix and local content - hence why I made tmdbhelper as I needed a way to mix content. I have no issue playing local content via tmdbhelper and it sounds like you have a configuration issue.

**Comment by cboRD181** [comment]
Appreciate the quick response.  I'll look into things on my end again

**Comment by MoojMidge** [comment]
I added an Up Next video listing to a fork of UpNext that I use, because I had the same issue with Embruary. It is not a bug, but a preference of the developer, and I can see why some people may prefer it the way.

I will eventually try and create a PR for the official UpNext add-on, but in the meantime you can try it [here](https://github.com/MoojMidge/service.upnext)

**Comment by cboRD181** [comment]
> I added an Up Next video listing to a fork of UpNext that I use, because I had the same issue with Embruary. It is not a bug, but a preference of the developer, and I can see why some people may prefer it the way.
> 
> I will eventually try and create a PR for the official UpNext add-on, but in the meantime you can try it [here](https://github.com/MoojMidge/service.upnext)

You're a legend mate! Can't tell you how long I've been looking for something like this and it works perfectly. Thanks a million
