### ISSUE TITLE
Flixart and Fanart

### ISSUE THREAD

**Issue by adamosborne83** [jurialmunkey/skin.arctic.horizon.2#536]
### Skin section

Home Widgets

### Feature description

I am after a little advice and hope I can explain it well enough with the below pictures.

So currently I Flixart with allows background fanart, but when I go into a movie, there is nothing in the back ground.

Or on the flip side, I have nothing on the main screen and then fanart when I click the movie 

As shown in the pictures, what I would like is to be able to have pictures for both.

Is there a setting at all?

https://imgur.com/a/aYJM3Ri

### Why is this feature needed? Please justify and explain.

Give a visually nicer interface.

Basically Flixart for widgets, then Fanart when movie is selected.

### Screenshots and Additional Info

![20221016_102316](https://user-images.githubusercontent.com/78307374/196039878-d93e956f-e0b5-4c7a-9be2-cc3de35d7c33.jpg)
![20221016_102321](https://user-images.githubusercontent.com/78307374/196039884-68b208a8-0db6-4e38-8d80-48576a456ee4.jpg)
![20221016_102346](https://user-images.githubusercontent.com/78307374/196039885-8ae1fc2f-2b0f-42ac-b2c5-7e1943a77050.jpg)
![20221016_102424](https://user-images.githubusercontent.com/78307374/196039886-0c2750ae-f024-4dc9-aa40-eb4cdb115384.jpg)
![20221016_102428](https://user-images.githubusercontent.com/78307374/196039887-dffcfe5a-54eb-437a-943e-464b222a6d77.jpg)
![20221016_102353](https://user-images.githubusercontent.com/78307374/196039889-a97cd739-0e25-403a-b2b7-b291ca7a7df9.jpg)

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
You cannot mix flixart + fanart modes. However, you can have fanart in both. 

Customise Appearance > Fanart (enable)
Customise Appearance > Customise Background > Simple background for widgets (disable)

**Comment by jurialmunkey** [comment]
Combing the two is not an option because the setting determines which background layout to include. Including two lots of backgrounds would be incredibly slow because Kodi would need to draw it twice. 

Fanart has a darker overlay to assist with readability when text is overlayed. Flixart by contrast looks bad in the info dialog because it is brighter and so clashes with the text making it unreadable.

**Comment by jurialmunkey** [comment]
Okay I had a bit more of a look and decided to add an option in Background settings to allow flix art in the info dialog.

I'm going to leave it disabled by default because if the background is light or is busy then the text gets hard to read but on simpler backgrounds it looks quite nice -- really just takes curating good artwork for it.

**Comment by adamosborne83** [comment]
> Okay I had a bit more of a look and decided to add an option in Background settings to allow flix art in the info dialog.
> 
> I'm going to leave it disabled by default because if the background is light or is busy then the text gets hard to read but on simpler backgrounds it looks quite nice -- really just takes curating good artwork for it.

Thanks for this, with all my enhancements etc, you can definitely tell I'm trying to leave AuraMod. Thanks again.

**Comment by xyzfre** [comment]
I used AuraMod for 4years once I tried AH2 I knew it was definitely time to change and I am so glad I did AH2 has so much more to offer and still going💯 Thank you @jurialmunkey for Sharing this amazing project with the community
