### ISSUE TITLE
[BUG] Homescreen widget fanart broken in 0.5.26

### ISSUE THREAD

**Issue by meesterexx** [jurialmunkey/skin.arctic.horizon.2#540]
### Skin section

Home Widgets

### Current Behavior

Fanart on homescreen widgets is missing/blurred out (see pics), but is fine inside addon sections after updating to 0.5.26

Flixart:
![flixart](https://user-images.githubusercontent.com/13154733/196484302-8c8bcb38-49f7-461c-b3d3-c6a74bd94e00.png)

Classic:
![classic](https://user-images.githubusercontent.com/13154733/196484340-35857e14-a6c9-434b-ae9d-542d9c99881e.png)

Keyart:
![keyart](https://user-images.githubusercontent.com/13154733/196484371-62159d53-4233-4e03-9cd0-476da45a36e6.png)

### Expected Behavior

Expect to see fanart on Homescreen widgets

### Steps To Reproduce

1. Upgraded to 0.5.26, immediately on returning to homescreen fanart was blurred/missing.
2.  Downgraded to 0.5.24, fanart was visible again (fixed).
3. Upgraded to 0.5.25, fanart still visible (fixed)
4. Upgraded to 05.26 again, fanart broke again
5. . Downgraded to 0.5.25 again,  fanart fixed again. 

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by meesterexx** [comment]
FYI, here's fanart fixed on downgrade to 0.5.25:
![fixed](https://user-images.githubusercontent.com/13154733/196485987-ba0056ec-9fad-4952-85e0-b86fc0aeeeb8.png)

**Comment by xyzfre** [comment]
What system are you using I'm on a Nvidia shield 2019 pro also on the current version .26 but all the proper fanart on home screen and within TMDb is working just as the previous update,, did you try exiting Kodi right after updating to .26 and then powering up Kodi again

**Comment by xyzfre** [comment]
Another thing make sure you're on the most current update of script.texturemaker

**Comment by krzysztofwinnik** [comment]
Same problem here on my CoreElec setup. I had a decent configuration with simple background for widgets + flixart for full expanded widgets, which worked like a charm untill .26 release. Currently I see blurred background for widgets instead of simple background (even though 'simple background for widgets' is still checked in skin settings) and no flixart for expanded widgets. 
Suprisingly, flixart works fine in videonav window - like in movies library or TMDBhelper.

AS for the script.texturemaker - it is up to date.

**Comment by meesterexx** [comment]
> What system are you using I'm on a Nvidia shield 2019 pro also on the current version .26 but all the proper fanart on home screen and within TMDb is working just as the previous update,, did you try exiting Kodi right after updating to .26 and then powering up Kodi again

PC, Win11 22H2, Kodi 19.4. Yes I exited and restarted kodi. I also tried deleting kodi cache and thumbnails. I haven't tried on my shield yet, I always test on PC before updating shield. I've also done multiple upgrade/downgrade tests now both with and without restarting kodi, doesn't make a difference. When I go back to 0.5.25 it works, when I go to 0.5.26 it breaks. 

> Another thing make sure you're on the most current update of script.texturemaker
![image](https://user-images.githubusercontent.com/13154733/196534540-cfd84078-71e1-4136-a514-3e2793b7621c.png)

**Comment by jurialmunkey** [comment]
You need to turn *off* simple background for widgets. The previous behaviour was broken.

Simple background *enabled* means a background WITHOUT artwork is shown on widgets - ie a "simple" rather than "complex" background is used.

You need to *disable* the simple background to see artwork on widgets.

**Comment by meesterexx** [comment]
Thank you. That fixed it. 
Would it make sense to have the Flixart/Keyart pre-set buttons in Appearance>Customize Appearance disable the "use simple backgrounds for standard widgets" option if enabled? Is there a use case where someone enables Flixart/Keyart if they don't want to see the art?

**Comment by jurialmunkey** [comment]
Please try v0.5.27

Note that background options have now changed.

![screenshot00002](https://user-images.githubusercontent.com/4618719/196594623-5a32cc58-a4a5-4555-92be-bb2053e33259.jpg)

**Comment by krzysztofwinnik** [comment]
@jurialmunkey - thanks for the update and re-organizing 'customise background settings'.
However my problem is only partly solved now. 

My setup is: 
'Simple' set for background in 'customise appearance settings; 
'simple background' and 'expanded widget artwork' for widgets in customise background. 

Despite those settings video widgets (e.g. big landscape row of 'your next episodes' grom TMDBhelper) still have blurred background which changes whenever I change focus on another widget. Is it intended to work like that? What is the difference betweeen blur background and simple bg then?
Another issue is related to a row of video addons styled as Apps. Whenever an item gets focus, background changes so that blurred fanbart is rendederd as a background. I'd rather expect to have one simple background that does not change whenever focus changes.

**Comment by jurialmunkey** [comment]
@krzysztofwinnik - What are your foreground artwork settings? None or FlixArt?

**Comment by krzysztofwinnik** [comment]
> @krzysztofwinnik - What are your foreground artwork settings? None or FlixArt?

FlixArt

**Comment by jurialmunkey** [comment]
That's working as expected then. When FlixArt is enabled the Simple background does a fake blur by stretching the fanart to a massive size.

**Comment by jurialmunkey** [comment]
Ah sorry. I misread your original comment. No that's a bug. It should display the simple background on standard widgets, not the blurred one. The fake blur should only be active when flixart is with those settings.

**Comment by krzysztofwinnik** [comment]
Excellent, works great again! Thx @jurialmunkey

**Comment by vermope** [comment]
Yes works, indeed, but no more in 'combined view'

**Comment by jurialmunkey** [comment]
> Yes works, indeed, but no more in 'combined view'

Should be fixed in latest main branch. Will make a new release soon with the fix.

**Comment by vermope** [comment]
Thanks!
