### ISSUE TITLE
Welcome Hubs ❤️

### ISSUE THREAD

**Issue by alKODIque** [jurialmunkey/skin.arctic.horizon.2#542]
### Skin section

Other

### Current Behavior

This is not a bug..
I just want to thank you @jurialmunkey  for amazing TMDbH Hubs we can enjoy since last updates..

I Particulary enjoy the fact that we can ''Jump'' from a Hub to another and the new hub for Discovery section

Looks amazing!! 🎉🎉🎉

https://vimeo.com/761512749

### Expected Behavior

..

### Steps To Reproduce

 ..

### Screenshots and Additional Info

 ..

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by Kayzels** [comment]
This looks amazing. How do you set it up? I never really got the hang of hubs when I was using AuraMod or Arctic Horizon. Your video finally makes sense.

**Comment by jurialmunkey** [comment]
Thanks guys! Glad you like it. Got a lot of things planned for these. There will also be a library equivalent soon. For now they're going to have a set configuration but a customisable version will be available eventually.

Would like to hear thoughts on what works and what doesn't. Also suggestions for what each widget section should contain. For instance: I find the Movies decades selector really useful, but not so sure about the TV one so would like ideas for something else for TV.

Also @alKODIque I changed the side selector behaviour a bit to hide it off to the side now and move the focus back to first position rather than second. I'm wondering how you're finding that change?

**Comment by alKODIque** [comment]
@jurialmunkey 
Yes, I notice the change you made for the side selector and I think it's visualy much more attractive. I also notice that you remove the fiirst row where we had list of video addons --> Perfect for me, since we now have Hubs who stricly contain movies OR TV Shows 👍 

I saw that you open a ''discussion'' section on your Github and I guess it's a good place to give feedback about using hubs .. So let me use it 2 ou 3 days and it will be a pleasure for me to let you know what was my user experience 

Thanks again for all the amazing work

**Comment by jurialmunkey** [comment]
Yeah that was my thinking for removing the addon row - now each section specifically relates to one type. 

Also now clicking the movie or tv icon will open the discover section for that type and the end section has changed to a random mixed content type of section (can't rememver if I pushed that change yet - if not it'll be in the next update)
