### ISSUE TITLE
display bug in TMDb Hubs

### ISSUE THREAD

**Issue by alKODIque** [jurialmunkey/skin.arctic.horizon.2#568]
### Skin section

Other

### Current Behavior

I notice a little bug in Hubs, when navigate from item to another.
Some part of the title is lost, as seen on this video:

Uploading Kodi_20221025_135234_Enregistrer.mp4…

### Expected Behavior

Complete display of the title 

### Steps To Reproduce

1- go to TMDb Hubs
2 - navigate from an item to an other
3- Display bug occur sometime for some reason I ignore :P

### Screenshots and Additional Info

(see video)

Thank you !

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by alKODIque** [comment]
https://user-images.githubusercontent.com/49578130/197847929-d7210342-0980-4278-91f6-0b688d3be178.mp4

**Comment by jurialmunkey** [comment]
Yeah I've noticed this too. It's because when a container reloads with new content then Kodi will try to focus the list to the previously focused title.

Most of the time it makes sense because when a widget reloads you want to stay focused on the same item. Problem here is that when the list is slid out like this you get that little bit of overhang if the list isn't at position 0.

So far I haven't found anyway to force kodi to ignore this behaviour and reset lists back to 0 when reloading. I'm not sure if there's going to be anyway to fix it.

**Comment by jurialmunkey** [comment]
Oh wait I just realised you're talking about a different thing with the title text disappearing. Never seen that before! 

No idea what would cause that - that's really strange.

**Comment by alKODIque** [comment]
Thank's @jurialmunkey , 
I think the bug came from the same issue that you explained in your first comment..
... _because when a container reloads with new content then Kodi will try to focus the list to the previously focused title_.

So when we go up again, the title test desappere at the same place

If it can not be resolve, that's no bid deal you know.. ;)

**Comment by jurialmunkey** [comment]
I can't reproduce it on Windows. 

I think it must be a draw issue on Android (and I think you're right - it looks like the text cuts where the slide animation would push it off screen).

As far as I can tell, it is impossible to override the Kodi's position focusing. There used to be a trick to override it by having another container with the same ID but it doesn't seem to work anymore.

So sadly, doesn't seem to be fixable (at least not easily)

**Comment by alKODIque** [comment]
Ok then,
Thank you for your time!
