### ISSUE TITLE
[Feature] Compact Home Menu Buttons

### ISSUE THREAD

**Issue by starseed420** [jurialmunkey/skin.arctic.horizon.2#581]
### Skin section

Home Widgets

### Feature description

Having a more compact button width, maybe depending on the TextLabel length, would be awesome. Result would be a nicely spaced-out button with a consistent border to icon to TextLabel spacing. This would also result in different button widths dependent on the TextLabel.

### Why is this feature needed? Please justify and explain.

The benefit would be a more compact looking, less "torn apart" UI look with beautiful spacing.

### Screenshots and Additional Info

![IMG_20221101_175635](https://user-images.githubusercontent.com/107289029/199292352-d3038056-2dd6-4704-a0fa-874d09466b52.jpg)

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by starseed420** [comment]
quick sketch on the idea...

![IMG_20221101_180318](https://user-images.githubusercontent.com/107289029/199293025-1676f6d7-4945-4032-9e48-12e44b449f25.jpg)

**Comment by jurialmunkey** [comment]
Not really possible.

The menu is a list not buttons. Kodi doesn't allow for autosized list items.

In an early prototype I did try out using buttons instead for autosizing but it was horrible because the positions of the unfocused icons to the right would jump around and move depending on the width of the focused button. It was really disorientating.
