### ISSUE TITLE
Ultrawide Support

### ISSUE THREAD

**Issue by ewanw58385** [jurialmunkey/skin.arctic.horizon.2#598]
### Skin section

Fullscreen Video OSD

### Feature description

Proper 21:9 and 32:9 support for ultrawide monitors :)

### Why is this feature needed? Please justify and explain.

Being genuinely such an amazing skin, the immersion is greatly reduced when having to force to 16:9 on ultrawide monitors (to prevent stretching) as you're stuck with black bars on either side. Proper ultrawide support would be greatly appreciated for us ultrawide users :)

There is yet to be a modern/ flix like skin with ultrawide support. The only real contender is Scope Nox, which is not even comparable!

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [x] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Unfortunately it is practically impossible to support different aspect ratios without writing a skin especially for it.

There's a technical issue in that coordinates need to be set in a specific way to allow adjusting positions to suit.

Then there's also a design issue where certain layouts only work in certain screen ratios -- e.g. some list views and plotbox would become ridiculously wide and unreadable. Also some views would have alignment issues -- e.g. wall plus info would not align properly to screen edges. 

A lot of the things which look good in AH2 are only possible because it is specifically limited to a 16:9 canvas. Basically anything that involves vertical scrolling (rather than horizontal) won't adapt well to a wider display.
