### ISSUE TITLE
[BUG] Browse button opening video info dialog in fullscreen widget

### ISSUE THREAD

**Issue by ShibajiCh** [jurialmunkey/skin.arctic.horizon.2#629]
### Skin section

Home Widgets

### Current Behavior

Hi @jurialmunkey,

In the fullscreen widget the Browse button is opening the video info dialog instead of the seasons view. Could you please check?

### Expected Behavior

The Browse button in the fullscreen widget should open the seasons view.

### Steps To Reproduce

Click on the Browse button in the fullscreen widget.

### Screenshots and Additional Info

![IMG20221110225555](https://user-images.githubusercontent.com/65297828/201168253-59644080-01c6-433d-b096-f34044a50871.jpg)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Change your kodi default select action from shwo information to select.

The play/browse button does the default select action. Skins can't override it.

**Comment by ShibajiCh** [comment]
Hi @jurialmunkey,

Okay, thanks for the info, but then how does the Browse button inside the video info dialog opens the Seasons view correctly? Please advise.

Thanks and Regards,
ShibajiCh.

**Comment by jurialmunkey** [comment]
Because it is a built in button that does that command.

**Comment by ShibajiCh** [comment]
Hi @jurialmunkey,

Thanks, so I assume the Browse button (beside the More Information butto) in the fullscreen widget can't be changed similarly to a built in button that does the same command of opening the Seasons view like that within the video info dialog? Please bear with me if I'm bothering you a lot with this. I just wanted to understand the process.

Thanks and Regards,
ShibajiCh.

**Comment by jurialmunkey** [comment]
Built-in buttons are specific controls in specific windows. It wouldn't be "built-in" if you could move to a different place. That's like asking why you can't put your built-in wardrobe in the swimming pool.

The "built-in" part isn't what's important here though. Built-in functions can be replicated other ways. You can get a wardrobe from Ikea to replicate a built-in one. That still doesn't make it a good idea to put it in the swimming pool.

---

To explain the issue:

There is no way to interact with the fullscreen widget directly because it is in the background. You can't click on the fullscreen widget or scroll through it like you might with a normal widget row.

That's where the buttons come in. They allow a way to do the most basic of interactions with the fullscreen widget:

- Play/Browse = Action(Select)
- Information = Action(Info)
- Left/Right = Action(Left) and Action(Right)
- (I had also considered a "Context Menu" button originally but felt it cluttered things too much)

So the problem is that if we override what the Play/Button action does then we end up with the same problem we started with: How does the user actually CLICK on the fullscreen widget?

There's a lot of scenarios where commands like PlayMedia (to simulate play) or ActivateWindow (to simulate browse) are not suitable and a plugin instead expects a click.

**Comment by ShibajiCh** [comment]
Hi @jurialmunkey,

Got it. Thanks for the detailed explanation!

Regards,
ShibajiCh.
