### ISSUE TITLE
Duplicate episodes whereas one of them is unwatchable

### ISSUE THREAD

**Issue by Weevild** [jurialmunkey/skin.arctic.horizon.2#64]
In practice what I see is two episodes, e.g "1x08" & "1x08" but only one of them will have an image while the other one is just grey. Trying to play the one lacking an image will sometimes return an error message and other times just load (on the home page, not in the video player) and do nothing.

My theory is that they (the unwatchable episodes) "spawn" when the first episode file gets replaced by my Sonarr instance. The episodes that I experience this issues with are ones that have been recently replaced. So something with the skin not liking that is probably at play.

**Comment by jurialmunkey** [comment]
Are you talking about the episode selector in the video OSD (the pop-up on stop/next button)? 

Can you grab me a screenshot? I don't think I've seen this issue before.

**Comment by Weevild** [comment]
Yes here you go:
![20220606_122601](https://user-images.githubusercontent.com/89477083/172144077-a54480de-8fab-4e42-9e55-d9366eb06097.jpg)
It might be Jellyfin-related if you can't troubleshoot it.

**Comment by jurialmunkey** [comment]
Oh that's in the Library view. That won't be caused by the skin. That'll be the plugin that you're using. You'll probably have the same issue in Estuary which is how you can test if it is a skin issue or not -- if it also happens in Estuary then it isn't a skin issue.

> I could try to uninstall the Kodi but is there a way to preserve my settings and skin-changes if so?

The `kodi/userdata/` folder contains all your settings, databases etc.

In `kodi/userdata/addon_data` you can back up data for specific addons. These are the main ones for AH2 configuration:

`skin.arctic.horizon.2` (skin settings)
`script.skinshortcuts` (menus/widgets configuration)
`script.skinvariables` (library view settings)

Optionally you might also want to back up `plugin.video.themoviedb.helper` addon_data folder. 
Also in `userdata`, the `guisettings.xml` file contains all your Kodi settings.

**Comment by Weevild** [comment]
I've reinstalled everything but kept the data you pointed me at and no similar issues to report thus far.
