### ISSUE TITLE
[Feature] Album title should be the primary text in an album view.

### ISSUE THREAD

**Issue by jbelew** [jurialmunkey/skin.arctic.horizon.2#644]
### Skin section

Library Views

### Feature description

The album title should be the primary text (title font) in an album view, as opposed to the artist. 

### Why is this feature needed? Please justify and explain.

The artist's name is already represented in the track listing. Additionally, for compilations with multiple artists, having "Various Artists" being the primary label provides almost no value. 

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
I see where you're coming from but I disagree about the title showing the album name.

The music library functions in the same way as the tvshow library. The title is always the *parent* node (tvshow or artist) and the infoline adapts based upon context. That way there are consistent focal points for information to provide orientation

- Header = The current node or section
- Title = The name of the *(grand)parent* item
- Infoline+Plot = Further contextual information about the item connecting it to the (grand)parent
- Item area = The child item and its siblings.

Artist > Album > Song (or Show > Season > Episode) are always hierarchical relationships (in contrast to rhizomatic relationships like Genre or Year). My approach is that information involving hierarchies should be displayed in a way which reflects how the current item is connected to its ancestors. The information should build as you drill down into the hierarchy.

I get where you're coming from with compilation albums though as they do change the hierarchical relationship a bit. However, I've always hated the "Various Artists" organisation method in general because it *is* largely meaningless. My personal opinion is that compilations be classified under the studio responsible -- e.g. Ministry of Sound compilation albums should be listed under "Ministry of Sound" rather than "Various Artists".

**Comment by jbelew** [comment]
My preference is probably based on the way I navigate music; using an album view vs, artist view. Compounding the issue is that if I navigated to an album by selecting the artist Brigitte Fassbaender for instance, I get something like this (a very common occurrence with classical music). Probably no correct answer and you rightly win by default on any difference of opinion.  

![screenshot00023](https://user-images.githubusercontent.com/4211774/202395700-7a73999a-6580-4f03-b951-100ec2568f8d.png)

**Comment by jbelew** [comment]
I'm getting the reverse with music videos (yeah I got sucked into that media type). Closing to clean up the list.

**Comment by jurialmunkey** [comment]
> I'm getting the reverse with music videos (yeah I got sucked into that media type). Closing to clean up the list.

Ugh, yeah I hate the musicvideos dbtype! I used to try to maintain a music video library but gave up on it because that whole music/video split library thing sucks.

Now I only bother with live concert dvds which I put under movies and then split off with a library node.
