### ISSUE TITLE
[BUG] Date parsing issue with full screen artist view.

### ISSUE THREAD

**Issue by jbelew** [jurialmunkey/skin.arctic.horizon.2#648]
### Skin section

Home Widgets

### Current Behavior

Date parsing appears to be hit or miss (mostly miss) on the full-screen artist widget view. Unsure if this is a skin issue or a metadata issue coming from the Kodi library. See screenshots --

### Expected Behavior

Dates should be clear and consistent. 

### Steps To Reproduce

1. Populate the music library with MusicBrainz-tagged items.
2. Scan the library with the default music scraper, Generic Album Scraper.
3. Configure a home screen with a full-screen widget to display random artists in the library. 

### Screenshots and Additional Info

![screenshot00019](https://user-images.githubusercontent.com/4211774/202286472-88b1d13d-3e20-4296-a6dc-fb86c8c286f0.png)

![screenshot00020](https://user-images.githubusercontent.com/4211774/202286546-7184b03d-d457-4160-8d44-cea6f96de3ee.png)

![screenshot00021](https://user-images.githubusercontent.com/4211774/202287138-0c0800c3-c666-4b0b-b50c-5cf0f11de8d8.png)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jbelew** [comment]
Looking at Estuary, the dates are a bit weird. Most artists have a "born" and "died" field. Bands tend to have a "formed" and "disbanded" field with some also showing a "born" field that duplicates the "formed" field information.

**Comment by jurialmunkey** [comment]
Yeah it's a bit frustrating as there's two separate sets of fields -- formed/disbanded and born/died -- and scrapers don't use these consistently or correctly. For instance, the Universal scraper appear to only fill born/died and doesn't use formed/disbanded.

The skin formats the label under the assumption that only one *set* of properties is filled. The formatting is
`{artist_formed} (disbanded {artist_disbanded}) {artist_born} (disbanded {artist_died})`

With Elton John you're getting an artist_formed and an artist_born label. I guess there's some logic to filling the artist_formed label with the date of his first album but it isn't technically correct (a band forms *before* they make an album not when). 

Either an artist is a person and so is born not formed; OR an artist is a group and so is formed not born. It can't be both

For the Sugarcubes you're getting artist_formed, artist_disbanded, and artist_died. That's plain incorrect. The band is disbanded but Bjork is still alive.

For Haydn you're getting artist_disbanded, artist_born, and artist_died. That's also plain incorrect. How can a person be "disbanded". 

I'm not really sure what the solution is here. Scrapers and addons incorrectly filling infolabels to force a particular behaviour in skins rather than talking to the skinner about accomodating the correct metadata is a massive issue. It frustrates me to no end.

**Comment by jbelew** [comment]
As I mentioned in my first comment, you can figure out what fields to show using the `strType` field of the artist. From my spot checks, the scraper seems pretty consistent in populating the right fields based on type, but there can be garbage in the other entries. Since the type for Sugarcubes is `group`, using the `strFormed `and `strDisbanded` fields would and indeed have the correct values. Since `strType` for Haydn is `person`, `strBorn `and `strDied` are populated with the correct data.

**Comment by jbelew** [comment]
Extending on the other back and forth we had, at least this one involves properties, `ListItem.Property(Artist_Type)`.
