### ISSUE TITLE
[BUG] Movie Genre addon missing from addon.xml

### ISSUE THREAD

**Issue by berkhornet** [jurialmunkey/skin.arctic.horizon.2#658]
### Skin section

Other

### Current Behavior

I've just rebuilt my Kodi set up and noticed that the movie genre icons were missing. I installed resource.images.moviegenreicons.transparent and solved the bug. 

I wondered if this addon should be installed automatically (if not present) when installing AH2.

### Expected Behavior

Genre icons displayed

### Steps To Reproduce

1 Install AH2 into a Kodi setup without the resource.images.moviegenreicons.transparent addon
2 Navigate to Movies/Genres

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
I'll add them to the dependencies section to make it easier to install.

I don't want to add it to addon.xml to auto-install it because then it can't be uninstalled. It's not strictly required for the skin so it's good to have the option to save space (same goes with weather fanart). 

Also there's the option to install the Horizon genre pack and the skin will use that instead - https://github.com/Swageroni/resource.images.moviegenreicons.horizon
