### ISSUE TITLE
[Feature] Change icon to FHD/4k with frame rate in video player OSD

### ISSUE THREAD

**Issue by juanma-cvega** [jurialmunkey/skin.arctic.horizon.2#673]
### Skin section

Fullscreen Video OSD

### Feature description

Currently, there is an icon next to the release date in the video player OSD that shows 'HD' for 1080 or 720 files. Would it be possible to show a different icon for 1080? I've normally seen other players show either FullHD or simply FHD. Given the space available, I guess FHD would be better.
Apart from that, would also be possible to show the framerate next to the number? 

### Why is this feature needed? Please justify and explain.

The reason for asking for these features is specially for the PVR. There are many channels that are either 720/25 fps or 1080/50 or even 720/50 or 1080/25. There is a big difference, specially for sports channels, when moving from 25 to 50 fps and I used to check this with the icons that were removed from underneath the player controls. There is still the option to check this in the OSD but it takes more than one click to get there. 

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
I'll add an FHD tag to the infoline as that's no trouble.

It'll be a no on the FPS though. The FPS is only available when the video is playing, not before you select it. The info line needs to display consistent information in both fullscreen and media windows.

FYI - it's only two clicks to see FPS because the controls wrap around the ends. Click to open OSD then press Left to focus Video Settings pop-up.

**Comment by ivarbrandt** [comment]
Piggybacking off of this request, could you please also add a 4K HDR icon to differentiate between standard 4K and 4K HDR files?
