### ISSUE TITLE
[Feature] Show the subtitles offset in the video OSD menu when hovering over the settings button

### ISSUE THREAD

**Issue by juanma-cvega** [jurialmunkey/skin.arctic.horizon.2#674]
### Skin section

Fullscreen Video OSD

### Feature description

Would it be possible to show the subtitles offset slider, the same way it is possible now with the audio speed slider, when in the OSD settings button?

### Why is this feature needed? Please justify and explain.

I actually find this slider more useful than the other one in my case. I normally watch everything in a different language than my own and download subtitles using a Kodi addon. Sometimes subtitles need to be adjusted so this slider would be helpful.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
The audio speed slider isn't visible though... Are you talking about the *video* speed/tempo control?

If youre talking about the video tempo control - that's not a real slider. It is just a button where pressing left and right are linked to tempoup/tempodown actions (or fastforward/rewind if video settings). The "slider" is positioned based on the tempospeed value. 

Doing the same with subs would be difficult because you need precision control. I'm not sure if there are even subtitle offset actions.

**Comment by jurialmunkey** [comment]
Okay there are sub offset actions but unfortunately still not possible. There's no infolabel that gives the subtitle offset position.

Without an infolabel it's impossible for the skin to display the offset value or reposition the slider.
