### ISSUE TITLE
[Feature] Custom Title Length

### ISSUE THREAD

**Issue by dm2912** [jurialmunkey/skin.arctic.horizon.2#682]
### Skin section

Home Widgets

### Feature description

Can we possibly have a setting to customise the visible title length. 

So "Set title length" and anything from 12-14 to about 30

### Why is this feature needed? Please justify and explain.

At the moment, on a large resolution TV the current limit of around 16 characters is fairly small, and truncates titles that don't really need it. 

(I appreciate the "wrap" setting but honestly, that makes titles look really really cramped)

### Screenshots and Additional Info

![screenshot00055](https://user-images.githubusercontent.com/25871666/205457709-bb279ba3-ad0d-4657-bbbc-7a7ea4860f08.png)

As an example, truncating this takes up nearly as much space as just putting the full title. Would be helpful for large resolution devices if we could specify a character limit at which either truncating, or wrapping takes place, because on a 1080-4k screen there really is no reason for that title to be truncated

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by dm2912** [comment]
Also applies to library items. 

Replacing "ors" with "..." is just annoying 
![screenshot00056](https://user-images.githubusercontent.com/25871666/205457838-ca502889-f519-477f-95c3-4d75c6dfe6a5.png)

but on the flip side, putting wrapping on makes the band title in this instance, TINY
![screenshot00056](https://user-images.githubusercontent.com/25871666/205457872-2e99e39b-3613-4788-ac52-4b9fa80fed64.png)

**Comment by jbelew** [comment]
I know you're very protective of your gird, but with each release, I've been patching my font sizes to font_info_black at 97 and font_info_black_doublerow to 64, staying with your Pentatonic scale. It gives the double-line presentation a lot more prominence than the native size and just seems to fit better IMHO.

**Comment by jurialmunkey** [comment]
The skinning engine does not allow variable values for coordinates. All coordinates require predefined constant values. It simple isn't possible to allow user customisation of control width. 

There's three main reasons the particular width has been chosen. 

- it must allow space fore flixart/clear styles
- it can't be wider than plot and very wide textboxes are difficult to read so there is a limit. 
- it needs to be consistent with the info dialog where there is less horizontal space

**Comment by dm2912** [comment]
hmmmm, ok, I don't really have any, um, well.. lol..

In the two examples it just looks whack. Lady Chatterly's... just looks weird only taking up half the screen when there is clearly room for more title (but i appreciate the issue over textboxes then having to be wider)

In the case of 13th floor elevators its just downright annoying that 3 letters are replaced by 3 dots... taking up exactly the same amount of space lol. 

I don't really have a constructive followup I'm afraid 

I guess the "followup" would be that Kodi team need to sort their theming engine out, and modernise it to be able to adapt to higher resolution devices and variable settings rather than a 2007 one size fits all approach. :D

**Comment by jbelew** [comment]
I'll try and do a pull request with my "patched" changes tomorrow. It's a hack and could probably be coded better, but it sticks to the grid, at least my interpretation, and gives character descenders a bit more room against the infoline. The only drawback is that the info screen isn't perfectly aligned but I think it's a good tradeoff.

**Comment by jurialmunkey** [comment]
> In the case of 13th floor elevators its just downright annoying that 3 letters are replaced by 3 dots... taking up exactly the same amount of space lol.

Yeah this annoys me too. Kodi determines when to truncate and unfortunately there's no leeway -- if a character glyph is even a single pixel over the width the skin defines for the label control then Kodi will truncate.

Nexus should offer a bit of improvement with these "on the line" type calls because the skinning engine now generates a more tightly packed font atlas with less whitespace around character glyphs. Less empty whitespace in the bounding box for each glyph means fewer places where a label gets unnecessarily truncated on what is essentially trailing whitespace of the last character.

e.g. see Matrix vs Nexus font texture atlas:
https://user-images.githubusercontent.com/30039775/172252076-047689ab-d787-4c62-a816-0fe977843425.png
https://user-images.githubusercontent.com/30039775/172252106-be42478a-c3b5-4a21-911a-fc3b4237ab6d.png


> I guess the "followup" would be that Kodi team need to sort their theming engine out, and modernise it to be able to adapt to higher resolution devices and variable settings rather than a 2007 one size fits all approach. :D

I'm struggling to see how the resolution is relevant. A 55inch tv at 720p and a 55inch tv at 8k are the same physical size. The 8k will obviously look nicer owing to its higher density DPI but in terms of skin proportions will be functionally identical to the 720p.

When you use a different resolution from the base 1080p, the skinning engine simply multiplies the pixel values of coordinates to scale the textures accordingly (0.67x for 720p; 1.33x for 1440p; 2x for 4k; 4x for 8k; etc.). Fonts are rendered to a texture atlas and so scale with the resolution. A higher resolution will give crisper font rendering but won't change the physical size.


> is this a technical limitation or a design choice? in other words can i manually edit the title lengths without affecting textboxes below?

Design choice. 

However, since this was an intentional choice, throughout the skin the title width uses the same constant as the plot width. Doesn't mean it can't be changed but does make it a bit more complicated than change the values in the constants.

**Comment by jurialmunkey** [comment]
> I know you're very protective of your gird, but with each release, I've been patching my font sizes to font_info_black at 97 and font_info_black_doublerow to 64, staying with your Pentatonic scale, along with raising the container another few pixels. It gives the double-line presentation a lot more prominence than the native size and just seems to fit better IMHO.

This won't work. 97pt will not be remotely close to 3 grid lines height. And 64pt for double row will cause descender overlap with the info line. If the bounding box is adjusted upwards, then it will go outside the defined view. And if linespacing is adjusted to condense to fit vertical height then it will overlap its own ascenders.

Also the break point of the wrapping relies on the font being double size. A 64:97 ratio does not translate cleanly to a percentage, which will cause cases where it is not calculated correctly by the skinning engine due to rounding errors.

**Comment by jbelew** [comment]
I've been running with those fonts size and some small tweaks to the control include for weeks and can't go back personally (come on Kodi dev team, where is aligny bottom?!?). Looks for the pull request and sit on it for a bit.

**Comment by jurialmunkey** [comment]
After thinking about it for a bit, I think I've come up with a decent compromise/solution where the skin will use a wider value if flixart is disabled (in v0.7.11)

Our two main limiting factors on the width are (1) flixart and (2) info dialog. When flixart is enabled, we only have 880px of horizontal space available to us. However, in the info dialog there is an additional 240px available (1120px total). When flixart is disabled there's less concern about text clashing because the background is dimmer, so we can use up that additional space.

There's a bit of a loss of that quadrant symmetry but that's not less important when flixart is disabled. If anything the width expandsion helps the balance when fanart is enabled because that top right quadrant is otherwise always bare.

**Comment by 0x464e** [comment]
Hi, I stumbled upon this issue. And yes, I too find it quite annoying how the titles cut/wrap so early when there's lots of space left. But I understand the reason, shame there can't be variables to customize the values.

Is there a value I can change myself manually to customize the wrap off point? Maybe something in the xmls? I could just make an automatic workflow for my personal use so that updates get patched to which ever values fit my screen. @jbelew @jurialmunkey

**Comment by jurialmunkey** [comment]
Like above, solution is to switch to fanart background (ie disable flixart) and you will have longer titles.

**Comment by 0x464e** [comment]
> Like above, solution is to switch to fanart background (ie disable flixart) and you will have longer titles.

While (unsuccessfully) trying to find where and how I can do this, I found out about  
`Skin Settings` -> `Appearance` -> `Customise appearance` -> `Options` -> `Clearlogo`, and this is actually much nicer. I will stick with clearlogos. 

Thanks, and thanks for your great work on this skin. I keep learning more and more things I can do with it.  
There must still be so much more potential, but I just don't know how to do it since I don't know it exists.
