### ISSUE TITLE
Similar Movies Tag

### ISSUE THREAD

**Issue by adamosborne83** [jurialmunkey/skin.arctic.horizon.2#716]
### Skin section

Home Widgets

### Feature description

So, on my main page, I use Similar Movies widget from Skin Helper(marcelveldts repo), and on Aura will say 'Similar to.........' then the Movies are based in that. Would it be possible to add that?

### Why is this feature needed? Please justify and explain.

It will then tell me what movie the selection is based on.

### Screenshots and Additional Info

![16724016968596216053793843232817](https://user-images.githubusercontent.com/78307374/210068209-440cad18-824d-4f32-9cff-62eff8a03c68.jpg)

I use this widget from Skin Helper Services, purely due to the fact that it gathers the recommended list from my library movies.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
According to the SH docs you can get the title with `$INFO[Container.ListItem.Property(originaltitle)]` so simply add it to your widget label -- e.g. `Because you watched $INFO[Container.ListItem.Property(originaltitle)]`

Because there's no ID specified for the container, it will use whatever container is focused. Not an issue for a full expanded widget like you have because you can't see any other widgets. If you want to use it for widgets that aren't fullscreen expanded then you can specify the widget container ID with: `$INFO[Container(ID).ListItem.Property(originaltitle)]`

The ID numbers for widgets are calculated with the formula `mainmenu_position * 1000 + 600 + widget_position` -- for example,  the third widget on the second menu item will be 2603

Note that the special "fullscreen" widget at the top always has 301 as its ID (and it doesn't count in terms of calculating widget_position).

**Comment by adamosborne83** [comment]
> According to the SH docs you can get the title with `$INFO[Container.ListItem.Property(originaltitle)]` so simply add it to your widget label -- e.g. `Because you watched $INFO[Container.ListItem.Property(originaltitle)]`
> 
> Because there's no ID specified for the container, it will use whatever container is focused. Not an issue for a full expanded widget like you have because you can't see any other widgets. However, if you want to use it for widgets that aren't fullscreen expanded then you can specify the widget container ID with: `$INFO[Container(ID).ListItem.Property(originaltitle)]`
> 
> The ID numbers for widgets are calculated with the formula `mainmenu_position * 1000 + 600 + widget_position` -- for example, the third widget on the second menu item will be 2603. Also note that the special "fullscreen" widget at the top always has 301 as its ID (and it doesn't count in terms of calculating widget_position).

Thanks for the above, you know I am always grateful for any advice, and I do try and I am learning. Although, the above does not seemed to have worked for me.

I understand, this is more than likely only a 'me' request, but does improve the UI for myself, as auramod did this without the above.


![20221231_084705](https://user-images.githubusercontent.com/78307374/210130993-259ffe34-1c2c-4c66-9cd1-200f13c15e42.jpg)
![20221231_084748](https://user-images.githubusercontent.com/78307374/210130995-ca9ac22f-ed44-4f9f-8e7f-661f431e28da.jpg)
![20221231_084825](https://user-images.githubusercontent.com/78307374/210130997-2f7b8881-95da-497c-b149-24cab55e5a59.jpg)

**Comment by adamosborne83** [comment]
OK, stick with me here. I removed the ] at the end, and attached video shows it as HOME, But also if you can see, where the other widgets 'glide' as such, when it goes to the widget named 'home' it almost thuds into the widget.


https://imgur.com/a/VSUl5zk

**Comment by jurialmunkey** [comment]
The Skin Helper docs are wrong. 
The docs incorrectly list the property as `Property(originaltitle)` but according to the code it is `Property(similartitle)`

https://github.com/kodi-community-addons/script.skin.helper.widgets/blob/4717176b146ca54483a94100380bcbbe5b4473ab/resources/lib/movies.py#L174

https://github.com/kodi-community-addons/script.skin.helper.widgets/blob/b4c480effc9c8d62b914205f200029d501627ae2/resources/lib/tvshows.py#L198

**Comment by adamosborne83** [comment]
That's worked...... thank you so much for this, and doing the leg work that I could not.

I did post on your forum, but if you do need additional support with K20 and android crashes let me know.

**Comment by jurialmunkey** [comment]
> I did post on your forum, but if you do need additional support with K20 and android crashes let me know.

There is a version of TMDbHelper with a workaround to use MiniDOM instead of ElementTree which should hopefully fix the OMDb issues. It does need some testing to confirm that is working correctly

More details and tracking the issue is in this thread:
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/948

Specific details about the new test version in this comment:
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/948#issuecomment-1368710929

**Comment by adamosborne83** [comment]
> > I did post on your forum, but if you do need additional support with K20 and android crashes let me know.
> 
> There is a version of TMDbHelper with a workaround to use MiniDOM instead of ElementTree which should hopefully fix the OMDb issues. It does need some testing to confirm that is working correctly
> 
> More details and tracking the issue is in this thread:
> https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/948
> 
> Specific details about the new test version in this comment:
> https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/948#issuecomment-1368710929

I will give it a go now, I will try it with Umbrella first and see if get crashes, but, then without umbrella, as I know he uses elements for the library aspect.
