### ISSUE TITLE
OSD Info unreadable

### ISSUE THREAD

**Issue by Blackysbd** [jurialmunkey/skin.arctic.horizon.2#748]
### Skin section

Fullscreen Video OSD

### Current Behavior

When checking out an actor whilst watching and background video still playing, if I look at a movie or tv role the actor was in and press info I can't read the info, it needs a background.

### Expected Behavior

It should be possible to read the info

### Steps To Reproduce

1. Watch a video
2. press down for actor info
3. highlight a movie or tv show 
4. bring up context and press information

### Screenshots and Additional Info

![Kodi_20230112_173235](https://user-images.githubusercontent.com/53400821/212175031-b412e684-47f9-4fb8-89f6-ca14b8594b62.png)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Oh weird, I don't seem to be able to override the `<oninfo>` action anymore in Nexus.

This will fix the background. However, you will notice that because I can't reroute the oninfo action there is less information than if you had clicked on the item (ratings and some other extra details won't be available).

**Comment by Blackysbd** [comment]
Thank you, I only use it briefly whilst watching so no worries with extra info.
Very useful feature, skins great.
