### ISSUE TITLE
[Feature] Higher resolution assets

### ISSUE THREAD

**Issue by chcore** [jurialmunkey/skin.arctic.horizon.2#777]
### Skin section

Other

### Feature description

On 4k screens some of the skin UI elements are noticeably blurry. I am guessing this is because the skin is built for 1080p and does not have assets for higher resolution screens? Here are a few screenshots that have not been resized. Compare the volume meter to the text next to it (which is sharp at 4k) :

![image](https://user-images.githubusercontent.com/83099052/214814812-0921c93d-e29f-4954-a1b6-e285bd605c91.png)

![image](https://user-images.githubusercontent.com/83099052/214814951-c921fa60-ad0e-4f06-a946-6e6bd869c86f.png)

### Why is this feature needed? Please justify and explain.

It will make the skin prettier on bigger and high resolution displays.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Unfortunately Kodi is really bad at downscaling images so the skin has to be designed for 1080p otherwise it looks horrible if textures are downscaled from 4K (much worse than the slight bluriness on upscaling). It gets even worse if someone has a 720p display.

There was some internal discussion about svg style vector based textures which would solve this sort of thing but that's unlikely to happen until after Omega. Until then (or until 4K becomes the norm for TVs) I need to make the assets for 1080p to support the widest range of devices.
