### ISSUE TITLE
[Feature] fullscreen widget stacked widget

### ISSUE THREAD

**Issue by A3006B** [jurialmunkey/skin.arctic.horizon.2#787]
### Skin section

Home Widgets

### Feature description

Loving the new stacked widgets jurial!
Do you think it is possible for a fullscreen widget to have a stacked widget below it? I’ve had to change the fullscreen widget to a normal widget but now this has removed the widgets background when the menu item is selected, until you click down into the widget

### Why is this feature needed? Please justify and explain.

Stacked widgets to be able to be used below fullscreen widgets (my stacked widgets would be set to full expand information so I don’t think that would affect a fullscreen widget?)

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Unfortunately not possible. I had thought about it but it's a problem because all the fullscreen widgets reuse the same id (it's how they can display info even unfocused because I know what the ID is ahead of time).

Basically when you switch menu items the stacked widget will try to reload based on the other menu. If you got a few setup like that based on the fullscreen widget then you get some really odd janky behaviour that I can't solve.
