### ISSUE TITLE
[Feature] [Widgets] Add "Show More..." widget item

### ISSUE THREAD

**Issue by ShibajiCh** [jurialmunkey/skin.arctic.horizon.2#79]
Hi @jurialmunkey,

Could you please add the "Show More..." widget item similar to the Arctic Horizon skin? It's very useful.
![IMG20220606192425](https://user-images.githubusercontent.com/65297828/172174695-3d279adf-8f36-47d9-87b9-6ea1d9abb420.jpg)

**Comment by jurialmunkey** [comment]
Why not just show all the items in the widget itself? Why even have a "Show more" at all?

**Comment by ShibajiCh** [comment]
Hi @jurialmunkey,

Actually, I create lists like Top 10, etc. to show as widgets. Plus the watchlist I put as random under widget and another sorted by list as sub menu. In these cases the Show More widget item is very helpful for me and I guess maybe for many others. So it will be really kind of you if you add that feature in this skin as well, unless it's too much of trouble. I'll be really grateful to you if you add the feature. Thank you!

**Comment by Goldenfreddy0703** [comment]
Having a "Show more" option in skin settings would help significantly cause when i limit my tmdb widgets, I don't have a "Show more" at the end when limiting and i even have the tmdb widget "Show more" option enabled.

**Comment by SamDW96** [comment]
I would really appreciate this too. 
I populate my home screen with some widgets, for example a random selection of my watchlist. Since the full list is very long, I like having a random subset shown (10-25), and then all the rest accessible after scrolling through them via the 'Show more' button. When I click the button, I can get into the full list and view them in wall mode if I want. That's not possible in the widget itself, and so much easier to navigate the list in full when I want to.
Thank you for all your efforts!

**Comment by ShibajiCh** [comment]
Thank you @jurialmunkey !
