### ISSUE TITLE
[BUG] Classification (MPAA) is showing wrong rating system

### ISSUE THREAD

**Issue by tsteven9** [jurialmunkey/skin.arctic.horizon.2#803]
### Skin section

Other

### Current Behavior

In the settings, the classification is set to USA but the movie and TV show ratings displayed are using UK ratings system (12, 15, 18, etc.)

### Expected Behavior

The classification should be in line with the USA rating system (if set to USA), i.e. PG, PG-13, R, etc. There are some instances where the correct classification is displayed.

### Steps To Reproduce

1. Go to settings
2. Go to Skin Settings
3. Go to Furniture
4. Go down to Classification (MPAA) and set it to USA
5. Exit the settings
6. Go to a movie or TV show library and you will notice that the rating is not showing in USA system (See screenshots for more details)

### Screenshots and Additional Info

![Settings Menu Screenshot](https://user-images.githubusercontent.com/47198427/216794168-73c0aedb-ccb7-464b-8893-d26258b5768b.png)
![Movie Library Screenshot](https://user-images.githubusercontent.com/47198427/216794172-4b7c9cde-787f-40f9-86f7-5eb098918c65.png)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Behaviour is correct. "15" is not a USA rating. USA ratings are G, PG, PG-13, NC-17 and R. 

Since the addon you are using is reporting a UK rating and there is no corresponding USA rating, the skin displays the UK rating.

If the addon you are using is providing UK ratings, I can't magically make them USA ratings. You need to change the addon settings to get USA ratings, or speak to the addon author if it doesn't have a setting.

**Comment by Dragoopai** [comment]
1. If it is just depends on the addon he is using why is there even an option in the skin? What is the purpose of it at all?
2. Wouldn't it be another solution to not show the ratings if it does not match instead of falling back to UK.

PS: Sorry for hopping in. I am not into this rating stuff and I am some kind of a newbie in this Kodi. But that cam into my mind when I saw this issue.

**Comment by jurialmunkey** [comment]
@Dragoopai 

> If it is just depends on the addon he is using why is there even an option in the skin? What is the purpose of it at all?

Because many countries share the same names for classifications but the classification have different icons and meanings. For example: 'Australia', 'Canada', 'Ireland', 'New Zealand', 'UK', 'USA' all have a "PG" classification.

Australia PG is slightly different to USA PG because the next Australian classification is M which is "recommended for 15+" whereas in USA the next classification is PG-13 which is "restricted to 13+". In Australia a 10yo can watch an M movie unsupervised, whereas they cannot watch a PG-13 movie in USA -- that also changes which movies get classified PG.

> Wouldn't it be another solution to not show the ratings if it does not match instead of falling back to UK.

It doesn't "fallback" to UK. The "15" text in the info line comes from the addon. The skin only chooses which icon to display in the bottom right. 

There is no such thing as a "15" rating in USA. 15 is a UK rating so the skin shows the 15 UK icon to match the text from the addon.

**Comment by tsteven9** [comment]
My apologies for the delayed response. I appreciate the explanation provided regarding the issue and now understand that the cause is most likely the addon I am using. I will reach out to the addon's author for further assistance. Thank you for your time and assistance.
