### ISSUE TITLE
[Feature] Option for having "Blur" be applied to the entire screen (including the footer) when using Blur + FlixArt

### ISSUE THREAD

**Issue by OneAngryMan** [jurialmunkey/skin.arctic.horizon.2#829]
### Skin section

Home Widgets

### Feature description

Hi,
currently the footer section of the background is always kept in a neutral grey when using "Blur" and "FlixArt" in combination. In general this is fine, but in the case of a lack of items for the footer and/or only a reduced number of items for the respective widget, it does result in a somewhat dull look. Take this for example:
![Screenshot (494)](https://user-images.githubusercontent.com/83606678/219477065-09bddf91-708e-4096-b229-f1aca31d19ea.png)
I think this would look better if the entire background was blurred, based on the FlixArt in the top right corner. Therefore an option to have "Blur" be applied to the entire background would be lovely, unless of course there are good reasons for the current behavior (which I fear there are).

### Why is this feature needed? Please justify and explain.

see above

### Screenshots and Additional Info

see above

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
> unless of course there are good reasons for the current behavior (which I fear there are).

Yep, good reasons for it.

It's mainly to do with text visibility on light backgrounds and masking some visual artificats. Either you have to increase background dim dramatically (which puts us back to square one in terms of "dullness"), or suffer difficult to read text and ugly backgrounds as seen in these examples:

![screenshot00272](https://user-images.githubusercontent.com/4618719/219827839-b3a65ffb-f66e-4d20-867e-8f4961f5bfd7.jpg)

![screenshot00273](https://user-images.githubusercontent.com/4618719/219827843-63d8ca3b-6d38-4f93-bdba-1d4a90c2ffb9.jpg)


By comparison, you can see how the gradient floor helps mask the rough edges and improve readability dramatically. You can see here in particular how it helps smooth out the blockiness of the blur by introducing some gradient noise.

![screenshot00274](https://user-images.githubusercontent.com/4618719/219827875-243bdf2d-4eb1-43b4-9c2f-b1548747e384.jpg)

**Comment by jurialmunkey** [comment]
@OneAngryMan - 

v0.8.11 changes the floor fade to use a bezier curve mask instead of a plain linear gradient. Must have BLUR enabled to use it (STRETCH/NONE still needs to use the old floor for masking reasons).

It's subtle but I think makes a big difference (below screenshots use Poster List as simpler to demonstrate but same effect in Row). It brings a lot more clarity to the image and cleans up a lot of the dullness. The transition also feels softer and more natural whilst still masking blur artifact blockiness. Readability does slightly suffer in the info dialog but not an unbearable amount.

Here's the UPDATED approach:

![screenshot00286](https://user-images.githubusercontent.com/4618719/221332760-9d4afbb6-98dc-454d-972e-b77432c8a950.jpg)

Here's the ORIGINAL approach for comparison:

![screenshot00287](https://user-images.githubusercontent.com/4618719/221332767-a29e5e78-af48-4fed-affd-43d78c16caa9.jpg)
