### ISSUE TITLE
[BUG] Random movie clearlogo not updated during screensaver

### ISSUE THREAD

**Issue by TheTyrius** [jurialmunkey/skin.arctic.horizon.2#836]
### Skin section

Home Widgets

### Current Behavior

I use the default (semi-transparent) screensaver. When it kicks in on the random movie widget, the clearlogo no longer updates (while the rest continues to cycle). It updates as soon as woken up.

### Expected Behavior

Either cycling should be completely suspended, or the clearlogo should update. The joice is not mine to make ;)

### Steps To Reproduce

After starting, do nothing until the default screensaver kicks in.

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Tmdbhelper suspends whilst screensaver is active to avoid wasting resources while idle, so the clearlogos will not update.

I can probably disable autoscroll on screensaver

**Comment by TheTyrius** [comment]
I see. If I understand correctly, local clearlogos are also handled through tmdbhelper, so the same applies to them?
Another possibility would be to fallback to text-titles, but it'd probably be best to go for the easiest fix for such a minor issue.

Thanks alot for creating and maintaining this skin, I love using it!

**Comment by jurialmunkey** [comment]
> I see. If I understand correctly, local clearlogos are also handled through tmdbhelper, so the same applies to them?

In a roundabout way yes but for a different reason.

TMDbHelper crops the logos. The skin has a fallback to the uncropped logo if the cropped logo hasn't been set. 

The problem here is that when the screensaver activates, TMDbHelper's service pauses. So any details it had loaded into properties are also paused rather than cleared.

>  Another possibility would be to fallback to text-titles, but it'd probably be best to go for the easiest fix for such a minor issue.

Yeah I think preventing autoscroll is probably best approach.

Even if there were a fallback to the title or local logo, the other details from TMDbHelper will also be paused (e.g. ratings, tvshow status etc.) so some of the details onscreen will be incorrect.

It's the same reason why there's a slight delay after exiting the screensaver before the details update properly.

The other option could be to have TMDbHelper clear all its properties when the screensaver activates but I can imagine that being a bit annoying visually.
