### ISSUE TITLE
[Feature] South Asian fonts especially Hindi, Tamil and Thai

### ISSUE THREAD

**Issue by aseanic** [jurialmunkey/skin.arctic.horizon.2#837]
### Skin section

Fonts and Languages

### Feature description

Indian and Thai fonts to be included. Currently they are either empty or replaced by funny characters

### Why is this feature needed? Please justify and explain.

There are around 1.4 billion indians and 70 million thais in the world should get similar justification like chinese & korean got their font.

### Screenshots and Additional Info

![Kodi_20230218_220821](https://user-images.githubusercontent.com/79122869/220233683-dcb9e645-6d3e-4ef6-b246-9e46486fe4ce.jpg)
![4](https://user-images.githubusercontent.com/79122869/220233694-006108aa-5b2d-48a1-a18e-5c097744f0a2.jpg)

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Unfortunately it is currently not possible to designate fallback fontsets in Kodi. The CJK font used in AH2 is already at full character limit so it is impossible to add more characters.

The "Arial" font used by Estuary is not a good solution because it is very different stylistically from the base font used in AH2, and there is currently no good way to cater to both font sets at the same time. 

If there were a Devanagari/Thai fontset, then you would not be able to see the CJK characters in your screenshot - so it just replaces one problem with another.

The only solution is waiting for something along the lines of this PR to be merged in Kodi core: https://github.com/xbmc/xbmc/pull/20552
