### ISSUE TITLE
[Request] Zoom out on flixart fanart

### ISSUE THREAD

**Issue by rizreflects** [jurialmunkey/skin.arctic.horizon.2#840]
### Skin section

Home Widgets

### Feature description

I currently use the flixart option in your skin. Whilst browsing through my widgets I can't help but notice that the fanart seems slightly too zoomed in. Sometimes you can miss key elements of the actual fanart because the bottom and sides of the image can be cut off. 

Take a look at this example:
![image](https://user-images.githubusercontent.com/76912707/220969616-635ce75f-e257-4974-8a6a-415c8219ce87.png)

There is a character at the bottom left of the picture that is totally cropped out because the image is zoomed in too much. Would it be possible for you to zoom out a little more so more of the image can be displayed? 

I'm very grateful for your skin and appreciate all the work.

### Why is this feature needed? Please justify and explain.

Purely cosmetic

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Flixart doesn't zoom fanart at all as long as your art is 16x9 and your screen is 16x9

Flixart is scaled to 1280x720 which is a 16x9 resolution. Obviously there's some fading on the edges to blend it with the blur but you should still see practically the full image.

Are you sure you haven't enabled "keyart" instead?

Also what's your screen resolution? Because if you're not using a 16x9 res then Kodi can warp some elements.

**Comment by jurialmunkey** [comment]
It really looks like you're using Keyart here not Flixart. The dimensions look like key art. Change to Flixart.

**Comment by rizreflects** [comment]
> It really looks like you're using Keyart here not Flixart. The dimensions look like key art. Change to Flixart. 

Here are my settings. I have flixart enabled.

![20230223_232541.jpg](https://user-images.githubusercontent.com/76912707/221054945-0c48679a-0f8e-4973-b1ab-9b20a8099bfc.jpg)

I'm currently running kodi on a 49 inch 4k TV.

**Comment by rizreflects** [comment]
Its a lot more noticeable in this picture. The posters on the bottom cut off the boat completely.

![image](https://user-images.githubusercontent.com/76912707/221055532-27a3df48-3f4d-4eac-8f12-2da1541ad939.png)

**Comment by rizreflects** [comment]
![20230223_234247.jpg](https://user-images.githubusercontent.com/76912707/221056553-17468082-1a69-437d-b44d-5c5487fcbf04.jpg)

This is the original image as you can see here. It's a lot more zoomed out. I'm using my PC to send you the screenshots, but it's worth noting I have the same issue on my coreleec device.

**Comment by jurialmunkey** [comment]
Are you just talking about the posters overlapping?

Because I'm not going to change the dimensions. I experimented with smaller dimensions in the past and this is by far the best balance of size. Additionally 720p scales really well from 1080p as it is 2:3 ratio (and 1:3 from 4k)

**Comment by rizreflects** [comment]
> Are you just talking about the posters overlapping? That is different to being "zoomed" in. Nothing is being "cropped" out here - it is just being obscured by the posters. 
> 
> I'm not going to change the dimensions to avoid posters overlapping. I experimented with smaller dimensions in the past and this is by far the best balance of size. 
> 
> Also 720p scales really well from 1080p as it is 2:3 ratio (and 1:3 from 4k). Other dimensions make the image look far worse because they do not have good rescaling ratios
> 
> If you want an unobstructed view of fanart then you should use something like big landscape or media info list which puts the artwork in the foreground. 

I'm doing quite a bad job at explaining this. 

Here is a picture taken straight off Netflix:
![20230224_105645.jpg](https://user-images.githubusercontent.com/76912707/221163958-900f5e95-8003-4d57-85c3-9ddd8f175de6.jpg)
Focus on those 4 objects in the background behind her.

Now here's that same fanart displayed through Arctic horizons flixview 

![20230224_110134.jpg](https://user-images.githubusercontent.com/76912707/221164522-79c739fb-2eca-40e6-b55c-3abddc15d7ec.jpg)
![20230224_105855.jpg](https://user-images.githubusercontent.com/76912707/221164547-e98f41ff-6138-494b-adce-ef4bed1945ba.jpg)

Those 4 objects are no longer visible at all. This is what I meant by 'zoomed in'. When we compare the 2 images, Netflix shows the entire image in the top right corner, whereas on Arctic horizon we always lose out on whatevers displayed at the bottom of the image (e.g. those 4 objects which are no longer present). This is all I was referring to. Ultimately you've done a great job on this skin and if you feel it's better as it currently is, then I'm happy to trust your decision. This is just something I've always noticed and felt I should point out to you, as you do seem to be quite the perfectionist when it comes to your skins. I apologise for doing a bad job at explaining, but this is the best I can do.

**Comment by jurialmunkey** [comment]
No I understood what you're saying. I don't think you're understanding what I'm saying.

The image is NOT zoomed or cropped. However, the left+bottom edges are *faded* to blend with the blurred background. That means the left+bottom fanart edges appear blurred and lose some detail. Additionally, the poster positioning obscures the bottom edge of the fanart.

Netflix has several advantages here in terms of making the edges of the artwork more visible:

- Black background. 
  - In Netflix, a short gradient fade-to-black transition can work because background is a uniform colour
  - In Kodi, the fade to blur requires a longer gradient transition to fade seamlessly
- Netflix has control over the style of their artwork. 
  - In Netflix fanart is specifically chosen to work well with the fade-to-black transition.
  - In Kodi I do not have that luxury and must accomodate a wider range of artwork which is why blur is preferred.
- Netflix has control over the dimensions of their artwork
  - In Netflix, the designers control what dimensions artwork is made in and so can choose dimensions according to design
  - In Kodi, all artwork is going to be 1080p or 4k. Kodi is bad at downscaling in complex ratios, so I need to use dimensions that downscale from 1080p using a simple ratio -- e.g. 720p is 1080*2/3 so works well; 640p is 1080*16/27 so downscales poorly.
- Netflix *only* uses row views. In Kodi I need to design for a wider variety of views and so need to make sure the background looks good in all of them.

**Comment by rizreflects** [comment]
I understand now. Thanks for explaining in great detail.
