### ISSUE TITLE
Widget refresh will not start at beginning 

### ISSUE THREAD

**Issue by adamosborne83** [jurialmunkey/skin.arctic.horizon.2#842]
### Skin section

Home Widgets

### Current Behavior

Hopefully the video can also explain it. When the widgets refresh, they will not all start at the 1st one.

### Expected Behavior

All widgets to have the 1st movie selected 

### Steps To Reproduce

Have library video widgets and refresh skin.

### Screenshots and Additional Info

https://imgur.com/a/5jPnyJ8

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
I can't control this behaviour.

Kodi automatically refocuses the last focused item in the list when it reloads. It will only reset to the first position if the item no longer exists after reloading.

Skins have no control over this behaviour.

**Comment by adamosborne83** [comment]
I hope you get this notiforcation,  I was reading something on the tikipeter github, in regards to fentastic, and he gave the gent that mods it some help, in regards to this issue....... is this the same?



This is another action that can be fixed quite easily in python code (we can re-set the list position to 0 everytime we load a new bottom stack list) but I couldn't see a way to do it using just the skin. Why hadn't I done it yet in the service code?..... I only just remembered the way to do it. :) In python, it's as easy as

window.getControl(int(list_id + '1')).selectItem(0)

**Comment by jurialmunkey** [comment]
You dont need a python script to focus a specific position in a list. You can just do `setfocus(list_id,0,absolute)` in a skin

The problem is triggering the command. A skin doesn't have an "onreload" action trigger.

Even if you were to use a script service , it would be incredibly inefficient because you would need to have a loop constantly monitoring every container for reloading. 

It would also be a disaster for the user because it would be constantly stealing focus and sending you to different list ids (even if focus was bounced back it would flicker and be a bad user experience).
