### ISSUE TITLE
[Feature] Stacked Widget for custom hubs

### ISSUE THREAD

**Issue by JacopoV** [jurialmunkey/skin.arctic.horizon.2#845]
### Skin section

Home Widgets

### Feature description

Hi @jurialmunkey !

Great work on the constant evolving skin! Love it a lot!

I just wanted to ask you if you're planning (or if is not technically possible) to open soon the stacked widgets in the custom hubs.

I noticed that stacked widgets based on the prev selected item is not available as option.

Thanks a lot 🙏

### Why is this feature needed? Please justify and explain.

Considering how useful stacked widgets are, they will give even more freedom and customization for custom hubs.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Because the widgets in the hubs are effectively already "stacked", it would only work for items that have at least two levels of subfolders.

I was going to say - "it's *possible* but I'm not sure how useful it would be" - but thinking about it more now it might be useful for tvshows:

- Top widget side contains nodes for tvshows (e.g. recently added etc.)
- Top widget main then contains tvshows from node
- "Stacked" widget side contains seasons from above tvshow
- "Stacked" widget main contains episodes of seasons on the side

Let me see if I can add it in. I just didn't before because it didn't really see a use for it.

**Comment by jurialmunkey** [comment]
Done. In v0.8.12

Actually works really nicely for TV Shows. I tested with a TV Genres widget as the top node and it worked great. You'll have to be judicious in how you use it because obviously a lot of scenarios where it won't work correctly but it works great for tvshows.

**Comment by JacopoV** [comment]
@jurialmunkey thanks a lot, as always. 

You nailed the use case i was trying to achieve yesterday, when i open this ticket :) I bumped into this one exclusively for TV Shows. 

Thanks again for your amazing work and the lighting speed for improvements and changes :)
