### ISSUE TITLE
slow initial load due to not caching widget lists

### ISSUE THREAD

**Issue by djay** [jurialmunkey/skin.arctic.horizon.2#847]
### Skin section

Home Widgets

### Feature description

This might a skinhelper feature but it would be great on first load if the last known list of items in a widget could be displayed instead of waiting for the addon to load?
I did write the code to add kind of caching to autowidget but have since realised that it's really multiple instances of the addon all starting which is the slow down, almost doesn't matter which one. So caching really needs to be before any widget is loaded.
If this caching was able to be done it would also be helpful to limit the number of lists being loaded at once in the background to reduce the load on startup. I know this isn't a problem for high end systems and widgets aren't recommended for lowend systems but still, would be nice to help prevent crashing and still have the nicest skin around.

### Why is this feature needed? Please justify and explain.

It seems that on a system with a slower disk (firestick 4k with usb2) having many widgets means much addon loading which means slow widget initial load while nothing is displayed

### Screenshots and Additional Info

takes about 1min to load maybe 10 widget lists from 2 plugins on my system. Can get logs if needed

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
This is not something a skin can have any control over. Skins control appearance and navigation of the user interface, not the underlying functions. 

Painting your car red or giving it a new speedometer won't make it go faster. You need to change what's under the hood. 

Plugin loading time is entirely dependent on how long kodi takes to initialise the python interpreter and then how long each addon takes to initialise. And as you point out, there are then several instances of python loading at once. These aspects have nothing to do with appearance or navigation. 

If you want fast widgets on startup then you need to use the Kodi library.

**Comment by djay** [comment]
@jurialmunkey Thanks for the explanation. I didn't realise skins have no code and don't have any hooks into how widgets get loaded. I thought there would be due to how they can put limits on widget length etc.

So thinking out load. if the way to get fast load is to use library then what I need is something like autowidget to convert lists like latest episodes as a folder in a library rather than converting them into list in another plugin. I think plugins I know of that sync to library now create big folders off all your collection or watchlists but don't categorise it for you. I think this lists as folders is something I can add. Thanks.

**Comment by jurialmunkey** [comment]
@djay - yeah unfortunately not much control from the skin side at all in terms of when widgets load. I can't even prevent widgets reloading after playback stops which is why I don't implement an auto trailer function.

Have a look at tmdbhelpers library functionality. Any trakt list you monitor/add will have a corresponding smart playlist created - eg if you add watchlist then it makes a watchlist playlist which you can then add as a widget.

I think this is probably best approach - add everything to main library then filter with smart playlists. You won't want to create separate physical folders otherwise you end up with duplicate items in your library if two lists have the same item.

I also recommend using several small curated lists rather than trying to bulk add 1000s of items because the larger the library the slower it will be.

**Comment by djay** [comment]
@jurialmunkey I put down the options I could think of in https://github.com/drinfernoo/plugin.program.autowidget/issues/145. TMDB Helper is not really a great solution since I want to show paths like Recent Trending Movies from plugins, and games from IAGL etc, not just trakt lists. I also couldn't see how to sync more than one trakt list, or how to sync my up coming episodes.

**Comment by djay** [comment]
@jurialmunkey I'm trying to figure out the code but does https://github.com/kodi-community-addons/script.skin.helper.service do the calling of addon to turn it into a virtual directory and then a widget? or thats kodi directly like you suggest?

**Comment by jurialmunkey** [comment]
> TMDB Helper is not really a great solution since I want to show paths like Recent Trending Movies from plugins, and games from IAGL etc, not just trakt lists. I also couldn't see how to sync more than one trakt list, or how to sync my up coming episodes.

You can sync as many Trakt custom lists as you like. Either create a Trakt custom list yourself, or use one of the many lists available on Trakt -- https://trakt.tv/search/lists

Any custom lists or liked lists in your Trakt account automatically appear in TMDbHelper as selections

![screenshot00294](https://user-images.githubusercontent.com/4618719/222679223-8b36a64c-6c8d-4b06-9fd6-d37bc06b112e.jpg)

You can like a list on Trakt by clicking thumbs up icon and then it will appear in your TMDbHelper liked lists
![image](https://user-images.githubusercontent.com/4618719/222678825-b2ce5f3f-de84-4ee1-9eec-de97312e8fff.png)

If no existing lists serve your purpose and you don't want to make custom lists manually, you can use a service like MDbList or listrr to create custom lists based upon automated filters and then sync these back to Trakt to add in TMDbHelper
https://mdblist.com/
https://listrr.pro/

Any lists you add in TMDbHelper are then created as smart playlists e.g. here's my watchlist:

![screenshot00296](https://user-images.githubusercontent.com/4618719/222679305-693697b2-cc5e-4c7b-bcfe-30d15d2d13cb.jpg)

> I'm trying to figure out the code but does https://github.com/kodi-community-addons/script.skin.helper.service do the calling of addon to turn it into a virtual directory and then a widget? or thats kodi directly like you suggest?

Anything in Python is going to have a slow startup. Skin helper service is an addon using python so you have to wait just the same.

The reason the library is fast is because it is a SQL database and Kodi has been coded specifically to make library metadata available from the database as quickly as possible.

You aren't going to be able to add Games because they are not video library items. TMDbHelper works by creating a `.strm` file which is a text file shortcut to TMDbHelper's play function but appears to Kodi as any other video file. When you scan the .strm, the library scans it like any other video. The difference is that when you click it to "play" it, Kodi will instead run the command inside the .strm file (i.e. TMDbHelper's player functionality). 

That way you get fast loading of library content but can still route it through a plugin on playback.

**Comment by djay** [comment]
> Anything in Python is going to have a slow startup. Skin helper service is an addon using python so you have to wait just the same.
@jurialmunkey yes you are right but is there just one skin helper service running or one per widget refresh? 
Caching in the skin helper is going to be slower than the library but if there is only one running for all widgets then it's going to be a lot faster than waiting for all the addon instances and would would for any kind of widget.

**Comment by jurialmunkey** [comment]
Kodi launches each container directory as a separate instance. That means every widget using a plugin launches its own separate subinterpreter instance. 

Just like there is no way for two separate plugin subinterpreters to talk directly to each other, there also no way to talk to a separate central service subinterpreter directly either. 

The only real way is to create a socket server which is constantly listening on a port. A socket server is generally slower than each instance simply writing to shared sql database using sqllite3 and/or memory cache using kodi window properties.

And regardless, the slowest part on startup is simply waiting for python to initialise. Kodi always reloads ALL widgets at the SAME time after playback etc - - so you can compare how long it takes to reload after watching something versus on startup to see how much of impact startup time has. Sometimes service can take 5 or more seconds to start.

Believe me when I say there is simply no way you are going to solve slow widget startup times using python. The only way is to modify Kodi itself to provide a new method of writing plugins that is not reliant on python.

**Comment by djay** [comment]
@jurialmunkey yes I get all that. Just trying to understand where skin helper gets called and skin shortcuts too. I will work out.

**Comment by jurialmunkey** [comment]
Arctic Horizon 2 doesn't use Skin Helper at all.

If you use Skin Helper for widgets, this is an entirely different addon and functions just like any other plugin
https://github.com/kodi-community-addons/script.skin.helper.widgets

>skin shortcuts too

Not sure what the relevance of Skin Shortcuts is here. All it does is build skin XML includes from templates. It has no bearing on performance of widgets.

**Comment by djay** [comment]
> And regardless, the slowest part on startup is simply waiting for python to initialise. Kodi always reloads ALL widgets at the SAME time after playback etc - - so you can compare how long it takes to reload after watching something versus on startup to see how much of impact startup time has. Sometimes service can take 5 or more seconds to start. The service having not started will simply slow down all your widgets while they wait for your server to start listening on a port.
> 
> Believe me when I say there is simply no way you are going to solve slow plugin startup times using python. The only way is to modify Kodi itself to provide a new method of writing plugins that is not reliant on python.

@jurialmunkey I proposed reusing the existing menu caching, so startup can be faster - https://forum.kodi.tv/showthread.php?tid=373577&pid=3157158#pid3157158. ie show stale cached plugin menus from disk on teh widgets initially on startup and then in the background refresh them, perhaps only loading a few plugins at a time.

I think it could make kodi a lot more usable on slower hardware but not really sure if someone's considered it before or how to champion it. Or maybe I brush up on my c++ :)

or does that solution not make sense? for example, if kodi has no way to know how to get the widgets or menus to reload once the fresh version has been generated?
