### ISSUE TITLE
[bug] Disable textbox autoscroll when manually controlling via scrollbar

### ISSUE THREAD

**Issue by OneAngryMan** [jurialmunkey/skin.arctic.horizon.2#858]
### Skin section

Other

### Feature description

Separate autoscroll options for textviewer windows (using a textviewer.xml window to display a changelog for example) and textbox elements like the plot in widgets or the video info dialog.

### Why is this feature needed? Please justify and explain.

To even be able to read the full plot description for a title (without having to navigate to the "plot view" from the video info dialog) you need to have "Autoscroll textboxes" activated, as there is no way to manually scroll down. This is different for textviewer windows where you can scroll manually but then eventually just end up fighting against autoscroll all the time. Having separate autoscroll options for the two would be appreciated.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Oh this is actually a bug. The autoscroll should be disabled automatically when the scrollbar for the textbox is focused. I probably just missed a condition in the text viewer dialog.

Is that the only place it's happening - ie only place where it will still autoscroll when you have manual control?

**Comment by jurialmunkey** [comment]
A scripted window is trickier because the scrollbar ID could be anything.

I don't really understand why an addon would need to create a separate text viewer instead of using the built in but there must be a reason for it. 

Anyway, since it's not part of AH2, that would need to be fixed in the addon itself by adding `<autoscroll>false</autoscroll>` to their textbox control to override the default behaviour. I can't address it in the skin because it's not part of the skin (and I can't provide skin files for it because it's a banned addon)
