### ISSUE TITLE
No text label on OSD

### ISSUE THREAD

**Issue by SirRickie** [jurialmunkey/skin.arctic.horizon.2#859]
### Skin section

Fullscreen Video OSD

### Current Behavior

Fresh Kodi 20 install, arctic horizon 0.8.15, wn11. Weird issue (playing a movie) : on the OSD, there is an audio button and a subtitle button. Underneath these 2 buttons, there should be a small text label (ENG, DUT ...). These 2 labels are **not** displayed (which is very annoying). 
Also there are no text labels underneath the buttons of the info dialog (play, trailer, details ...).
Is this a setting somewhere, do I miss something ? Can you plse help and advise me a solution. Drives me nuts. Tnx.

### Expected Behavior

Text labels on audio and subtitle buttons.

### Steps To Reproduce

Playing a movie, bring up OSD.

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Have you changed the fonts from the default set?

**Comment by SirRickie** [comment]
Problem solved (how stupid of me). The installation is on a PC (17") with Wn11 (second device). When playing a movie, the Windows taskbar at the bottom is displayed. When changing the display mode of Kodi into fullscreen (instead of windowed), so the taskbar is gone, then the text labels appear on the OSD.
Strange though. On another PC (15") with the same installation and **with** the taskbar displayed, the text labels do appear on the OSD. Don't know the reason for this. But anyway, tnx for your reply.
Btw, I really like your great work. Soon you will receive a coffee.
Regards.

**Comment by jurialmunkey** [comment]
Ah it would've been because displaying kodi windowed changes the aspect ratio of the screen. Because vertical res changes then it's going to change the height of a newline of text. The button text just uses three newline characters to position the text under the button, so it'll either be not high enough and still under the button or too high and falling completely out of bounds of the control. 

The skin only supports 16:9 resolution. Any other ratio you'll likely get mixed results because it will change the dimensions.

Probably your other laptop where it works has 16:10 fullscreen res, so when you show the taskbar it actually makes kodi 16:9

**Comment by SirRickie** [comment]
Tnx for your explanation. It's clear to me now.
Btw : if I buy you a coffee, do I need to have a Paypal account ? I don't have one.

**Comment by jurialmunkey** [comment]
> Tnx for your explanation. It's clear to me now. Btw : if I buy you a coffee, do I need to have a Paypal account ? I don't have one.

Hey sorry, I missed this comment.

My Ko-Fi page only accepts PayPal unfortunately. They have an option to use Stripe instead of PayPal but I don't have a Stripe account.
