### ISSUE TITLE
[BUG] randomly playing first title under stacked widget

### ISSUE THREAD

**Issue by ddsarad** [jurialmunkey/skin.arctic.horizon.2#869]
### Skin section

Home Widgets

### Current Behavior

Whenever stacked widgets are loaded the first item in the list which is currently highlighted automatically plays without me pressing it.

### Expected Behavior

Movies not randomly playing

### Steps To Reproduce

Load stacked widget with movies underneath

### Screenshots and Additional Info

I experience this on fire stick 4k max and Nvidia shield pro, using fen and umbrella addons

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
It sounds like your using a list that is not folders for the base widget above the stacked widget.

**Comment by ddsarad** [comment]
I have the root fen menu as the first widget with movies , tv shows etc folders with 3 stacks below it. So with the base widget having movies selected then the first stack below it will have inprogress highlighted, and the next stack below will have my in progress movies. The first one which is highlighted in this list will automatically play.

**Comment by ddsarad** [comment]
I’m not sure what I’m doing wrong

**Comment by jurialmunkey** [comment]
Using one too many stacked widgets.

**Comment by ddsarad** [comment]
Do you plan on making it possible to use multiple stacks?

**Comment by jurialmunkey** [comment]
You can already, you just need to make sure that a stacked row isn't trying to open a playable item in the row above.

For instance if you have
Movie Genres
Stacked
Stacked

The the second stack will cause kodi to play the movie in the first stack.

However you could have the above with tvshow genres instead because the second stack will be seasons.

The issue is if you have a stacked which is get based upon a playable item instead of a folder then when kodi tries to add it to the container it will cause the addon to play instead because that's the action for that item the stack is based on.
