### ISSUE TITLE
[BUG] Stacked widget fails after the Nth record

### ISSUE THREAD

**Issue by Mr-7mdan** [jurialmunkey/skin.arctic.horizon.2#877]
### Skin section

Home Widgets

### Current Behavior

Basically, the stacked widgets behaves as expected  when selecting an item between (1-23) from the above widget. 
But when the user reaches the 24th item, the stacked widget turns blank. And doesn’t show anything even if the user select previous items (1-23).

### Expected Behavior

To continue to show the stacked widget

### Steps To Reproduce

1. Create a widget with 40 items or so.
2. Add a stacked widget
3. Go to home screen and start scrolling the main widget until the stacked widget turns blank

### Screenshots and Additional Info

I tried to load a video but it fails everytime.

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
It sounds like it's a problem with the 24th item in your list not having content.

A widget container hides when it has 0 items and is not updating. Once a widget container hides, kodi will not refresh it again even if its path changes. The only time it will update is on a reload (eg skin reload or after playback). 

There is no solution because I must hide the container when it is empty otherwise you will have a massive blank spot in your widgets where focus gets stuck


That means you must only use widgets for stacking where the items are guaranteed not to have empty folders.
