### ISSUE TITLE
Search keyboard 

### ISSUE THREAD

**Issue by bassemhelal18** [jurialmunkey/skin.arctic.horizon.2#918]
### Skin section

Library Views

### Current Behavior

am using a plug-in it use landscape combined view
In search when I search for a series and get into it 
And I try to get back (…) and use that button 
The keyboard pop up 

### Expected Behavior

..

### Steps To Reproduce

..

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
The reason the search pop-ups is because the parent folder ".." is the search, so when you focus that button in combined view then Kodi tries to run that command.

Skin works best with parent folder items disabled. If you need parent folder items then you should not use combined views.
https://kodi.wiki/view/Settings/Media/General#Show_parent_folder_items
