### ISSUE TITLE
Crashing on Library playback 

### ISSUE THREAD

**Issue by adamosborne83** [jurialmunkey/skin.arctic.horizon.2#952]
### Skin section

Home Widgets

### Current Behavior

Good Morning Jurial, I am hoping you might be able to shed some light onto this. I am using a FireCube 3 and I have numerous crashes on playback from library files.

This has been happening for about 6 months now, and the Umbrella Dev has kindly been working on it with me at some great depth.

He has even purchased an FC3 and used all my settings to try and replicate. 

This seems to mainly happen on auto play too, as if I use source select ot plays fine. 

### Expected Behavior

When playing from library no crashes. 

### Steps To Reproduce

Install every widget and movie strm in the world (4500)

Select movie

Boom

### Screenshots and Additional Info

The log belows show me playing Warcraft and it crashing on AH2

Https://paste.kodi.tv/lofikeyable

The log below shows the same film and file playing with Source Select

Https://paste.kodi.tv/guwujuihi

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Your logs are empty.

**Comment by adamosborne83** [comment]
Typical me, be with you soon.

**Comment by jurialmunkey** [comment]
A few questions:

1. Are these .strm via TMDbHelper?
2. If so, do you have the setting to get extra info from Kodi library enabled in TMDbHelper?
3. And what about the Kodi library player?
4. Are these from a widget or from the library?
5. Does it happen in other skins with multiple widget setup?
6. Does it happen in Estuary?

For Q1-3, the reason I ask is because you mentioned having a large library. Very possible that JSON-RPC request is crashing when TMDbHelper attempts to retrieve data from Kodi. Also very possible that caching such a massive library is causing mem issues.

For 4-5, mostly asking because of reuselanguageinvoker issues with widgets. If it happens in other skins where youve setup using reuselanguageinvoker addons as widgets then it rules out AH2 by itself as the problem.

Likewise for 6, if it also crashes in Estuary then it means not a skin problem at all and either a Kodi or Addon problem.

**Comment by adamosborne83** [comment]
Thanks for your reply, i will get those logs to you, i just had to pop into work.

Although, i can answer the above questions.

1, no these are directly done through Umbrella, although i have done this through .strm and it still crashed, although if makes any difference Umbrella created the STRM, only because you have a limit on import.

2. Yes i do have extra info enabled (have tried without too)

3. Stuck on this....????

4. The crashes happen straight from widget or the library.

5. It never use to happen on Auramod, but, this was when i was using the FireCube 2

6. No.

Also if it makes any differnce Invoker is turned off in Umbrella.

**Comment by adamosborne83** [comment]
So, all thumbnails are saved to usb, to save physical hard drive space, also, i often check the amount of RAM free, and it is never less than 350mb, inc when trying to resolve and play the files.

**Comment by jurialmunkey** [comment]
Okay, if it's not a TMDbHelper strm then 2 and 3 won't matter. Also if it crashes in the library in AH2 but not in Estuary then that rules out a lot of issues.

I'll wait to see the logs, though I'd say probably going to be fairly difficult to know what the issue is.

One thing to try would be to disable TMDbHelper and SkinVariables and see if you still get crashes. You should be able to do this by removing the dependency lines from the skins addon.xml and then restarting Kodi and disabling the addons and then restarting again. 

Obviously parts of the skin will not work with these disabled but it will work enough for the purposes of playing from the library and if you're still getting crashes then that rules out a conflict between the addons (and, likewise, if you don't get crashes anymore then we know it's not the skin and some addon conflict).

Also one more question - how are you playing items? Is this playback from the info dialog or directly from the item? If it's from the info dialog, have you tried switching default action to play instead of using info?

**Comment by adamosborne83** [comment]
I will try both your suggestions when i get home.

It is from info dialog.

Ok i will get a few logs sent to you to see if you can shed any light on it.

Thanks for this Jurial,

**Comment by jurialmunkey** [comment]
> It is from info dialog.

Please try just normal playback with default select action set to play and not from info dialog first. I have a strong hunch it's because of the scripted playback method used in the info dialog.

**Comment by adamosborne83** [comment]
> > It is from info dialog.
> 
> Please try just normal playback with default select action set to play and not from info dialog first. I have a strong hunch it's because of the scripted playback method used in the info dialog.

Right, home now and trying your suggestions...... I have just tried 10 films, with it set to play and not info dialog...... No crash at all!!!
So is the only 'Fix' do not use info dialog?

**Comment by adamosborne83** [comment]
The ONLY crash I have had, is trying to resume playback on a movie, log is below (and checked)
I have tried to crash Kodi, and this is the only way it would crash. Umbrella Dev will kick off at me for trying to crash this, as he knows that's my fav job.

Https://paste.kodi.tv/fafuyakevu

**Comment by adamosborne83** [comment]
May had spoken a little too soon,

Https://aqubezodef

**Comment by adamosborne83** [comment]
May had spoken a little too soon,

Https://aqubezodef

**Comment by adamosborne83** [comment]
This log, shows Interstella playing from resume in Estuary

Https://paste.kodi.tv/jumudicopu

**Comment by adamosborne83** [comment]
This log, shows Interstella playing from resume in Estuary

Https://paste.kodi.tv/jumudicopu


Another crash from widget in AH2.

Https://paste.kodi.tv/idemibuqas

**Comment by jurialmunkey** [comment]
> May had spoken a little too soon,
> 
> [Https://paste.kodi.tv/aqubezodef](Https://paste.kodi.tv/aqubezodef)

Is this from normal playback in the library (i.e. with default action as play and not in the info dialog)? If so, that rules out what I thought it was. 

Log's not giving me much. Really would need a backtrace to have any idea (not sure how to do that on Android).

I think next thing to test is disabling TMDbHelper and SkinVariables to see if that makes any difference.

**Comment by adamosborne83** [comment]
Correct, this is just on 'play'. Ok, I will ask umbrella dev to sort it so tmdbh isn't a dependent etc.

@umbrella_dev

**Comment by jurialmunkey** [comment]
> Correct, this is just on 'play'. Ok, I will ask umbrella dev to sort it so tmdbh isn't a dependent etc.

These are dependencies of the skin *not* the addon. You need to follow my instructions I gave about removing them from the addon.xml

**Comment by jurialmunkey** [comment]
You need to remove these lines from `skin.arctic.horizon.2/addon.xml` and then disable the addons and restart Kodi

https://github.com/jurialmunkey/skin.arctic.horizon.2/blob/6127b45163957c2ea9670fbd0e5c2cf7cdc89452/addon.xml#L5-L7

**Comment by adamosborne83** [comment]
Thanks for this, I am away for couple days, but I can guarantee I will try this as soon as I can.

**Comment by adamosborne83** [comment]
Hi Jurial,
I have followed the steps above, and there have been no crashes. Even on resume playback on my in progress films.

Https://paste.kodi.tv/avicopomet

Don't know if this helps at all?

**Comment by jurialmunkey** [comment]
Please try reenabling them one by one until you find which two addons are conflicting.

Logs aren't going to give me any info. I need a back trace.

**Comment by adamosborne83** [comment]
Just a quick heads up, I had crashing with tmdbh enabled, I only got an hour worth of testing in, so will give it a better go today.

**Comment by jurialmunkey** [comment]
Need a stack trace to be able to determine cause of an addon crash.

Most likely conflict is the usage of xbmc.Player monitor. A lot of these addons do funky things with setresolveurl and xbmc.Player which can cause issues when Kodi's player monitor attempts to retrieve duration details. 

I suspect what happens is a file resolves to nothing, the player monitor attempts to retrieve duration and then Kodi crashes because there is no playing file despite playback being started. That's just a hunch though and impossible to know the problem without a stack trace.

**Comment by adamosborne83** [comment]
Okay. i don't see a way to get a stack trace from android. I can try changing the advancedsettings logging back on to 1 again, I have done this before. Do you know of a way to setup a firecube to do a stack trace log, or would adding the advanced logging would be sufficient?

**Comment by jurialmunkey** [comment]
No not sure for android as I don't use it.

No a log won't be sufficient because it doesn't tell you the process which caused the crash. Stack trace is only way to get that.

**Comment by adamosborne83** [comment]
OK, I will make some enquiries about it and I'll get back to you. 
Thanks as always.

**Comment by adamosborne83** [comment]
Hi Jurial, feel free to close this, as it does not seem this is possible on Fricube, I have reached out to numerous people, including Fritsch who has helped me on issues before, and noone can seem to help with StackTrace.

**Comment by adamosborne83** [comment]
Also, after a lot more testing, with skin variables OFF kodi does not crash.

**Comment by adamosborne83** [comment]
I got a friend of mine to look into this toonfor me, he posted on Kodi forum, 
So will try and get the info you need..

Thanks so much

https://forum.kodi.tv/showthread.php?tid=373708

**Comment by umbrellaplug** [comment]
I've been trying to stay out of this one.
@adamosborne83  i have sent you a pm with a link to download a kodi 20.2 version for 32bit android with debug enabled. I know this is a clean working edition because I compiled it for you from the kodi github using the master branch.

@jurialmunkey thank you for your help so far. I've checked through my playback monitoring code and I don't see anything that could be leading to a conflict, but I'm open to any suggestions to help this user out. I will get with him to duplicate the issue with the debug edition and see if he can generate a stack trace with this version.

**Comment by jurialmunkey** [comment]
> I've checked through my playback monitoring code and I don't see anything that could be leading to a conflict, but I'm open to any suggestions to help this user out.

@umbrellaplug - I think it's the reverse of that. TMDbHelper requests details from xbmc.Player when playback starts and some underlying Kodi bug in the xbmc.Player interface causes a crash.

I don't think either addon is doing something "wrong"-- just some unusual/unexpected combo of behaviour that hasn't been properly accounted for in Kodi's C API.

I know from a very frustrating troubleshooting experience a few years back that it is possible to cause the xbmc.Player monitor to crash Kodi if the player fails to start playback at the same moment details are requested from the player (Kodi is meant to raise an exception, which it mostly does, but very very occasionally would crash instead). 

I avoid that scenario with a precautionary check for `isPlayingVideo()` but my hunch is that this issue here is related to whatever that same underlying bug is in xbmc.Player -- very much only a hunch though, hence why stack trace is important.

**Comment by adamosborne83** [comment]
Gents I am grateful for the help from you both, I will try and set an hour or 2 aside this weekend to test this.

**Comment by adamosborne83** [comment]
I'm now beginning to think this is to do with Universal Movie Scraper and the amount of information it has, so I will see.

**Comment by adamosborne83** [comment]
Think that I am going to close this.

I think that Universal Movie Scraper just overloaded Firecube3, which I find add as I never had an issue with Firecube 2.

But, using the basic kodi scraper, I've had 0 issues in 3 days.

The whole situation is a bit odd... thanks to you both.
Beers have been paid for 😀

**Comment by adamosborne83** [comment]
https://Ko-fi.com/home/coffeeshop?txid=c5802c43-bce3-4ed0-812b-4b829d124113&mode=public&img=ogiboughtsomeone
