### ISSUE TITLE
ClearLogo resizing 

### ISSUE THREAD

**Issue by adamosborne83** [jurialmunkey/skin.arctic.horizon.2#971]
### Skin section

Home Widgets

### Current Behavior

Please see the attached video.

Is it normal for clear logo to resize and move position as it does?

I ask this, because I do not have this happen on other skins I've used in the past.

It happens on library movies and movies pointed at widgets.

### Expected Behavior

Seemless flow between movies 

### Steps To Reproduce

Enable clear logo with AH2 skin

### Screenshots and Additional Info

https://imgur.com/a/2BANRHA

These are tmdbh settings too

![firetv_2023-08-15_17_33_06](https://github.com/jurialmunkey/skin.arctic.horizon.2/assets/78307374/1df2b076-678d-40c3-902e-8ac16b6e4415)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Yes this is normal. This is the delay between Kodi displaying the original clearlogo, and TMDbHelper cropping it and providing the cropped version.

The image control is not actually resizing or changing position. The bounding box stays the same, it's the image inside which changes -- because the transparent pixels around the edges are cropped it appears to become larger as more of the actual image can fill the space.

If you pre-crop your clearlogos (or select ones without deadspace around them) then you won't see this at all. Also once cropped, they should be cached and the transition should be much faster.

On my NUC I never see this transition at all for cached logos -- Annoyingly I don't have any ARM devices to test on. I think there must be a python library I use in TMDbHelper which is poorly optimised for ARM chipsets because the performance always seems to be a lot worse on those devices than I would expect.

**Comment by adamosborne83** [comment]
Thanks for the info, bloody android.
