### ISSUE TITLE
Use ListItem.Premiered instead of ListItem.Year by default

### ISSUE THREAD

**Issue by Hawkedon** [jurialmunkey/skin.arctic.horizon.2#98]
Hi @jurialmunkey, is it possible to use ListItem.Premiered instead of ListItem.Year by default for the skin? The reasons for this:

1. For movie/tv show/episode/music, Premiered will have the full information, there is no need to add the "Released" info anymore
2. For video plugins (YouTube, for example), Premiered will get the actual date of the item, with only the Year information, it's hard to get which video publish date information

**Comment by jurialmunkey** [comment]
Released info comes from TMDb and tells you your regions specific release date based upon region settings in tmdb. It also updates the label to tell you the status for upcoming items (eg in-production; cancelled etc). Next aired info for tvshows also displays in that position. Basically it is a release radar type of thing. 

Happy to add premiered to info line specifically for YouTube because that's different info.

**Comment by Hawkedon** [comment]
Thanks @jurialmunkey!
